// VocabUp — [word, pos, thai, example, level, synonyms, antonyms, collocations]
const VOCAB = [
["about","prep/adv.","เกี่ยว, ประมาณ","Tell me about yourself.","A1","concerning|regarding","—","talk about|think about"],
["above","prep/adj.","เหนือ","The sky is above us.","A1","over|higher than","below|under","above all"],
["after","prep/conj.","หลัง","See you after class.","A1","following|later","before","after all"],
["again","adv.","อีกครั้ง","Try again tomorrow.","A1","once more|repeatedly","—","again and again"],
["all","det/pron.","ทั้งหมด","That's all.","A1","everything|whole","none|nothing","all day|all night"],
["also","adv.","เช่นกัน","I also want to go.","A1","too|as well","—","—"],
["always","adv.","เสมอ","Always be honest.","A1","forever|constantly","never|rarely","always remember"],
["and","conj.","และ","Tea and coffee.","A1","plus|with","—","—"],
["answer","n/v.","คำตอบ, ตอบ","Answer the question.","A1","reply|respond","question","answer back"],
["any","det/pron.","ใดๆ","Any questions?","A1","some|every","none|no","any time|any way"],
["area","n.","พื้นที่","A large area.","A1","region|zone","—","residential area"],
["ask","v.","ถาม","Ask for help.","A1","inquire|request","answer|tell","ask about|ask for"],
["away","adv.","ไกล","Go away!","A1","distant|far","near|close","right away"],
["bad","adj.","ไม่ดี","Bad weather.","A1","poor|terrible","good|nice","bad luck|bad habit"],
["bag","n.","กระเป๋า","Put it in the bag.","A1","sack|container","—","shopping bag|handbag"],
["ball","n.","ลูกบอล","Kick the ball.","A1","sphere|orb","—","football|basketball"],
["bank","n.","ธนาคาร","Money in the bank.","A1","financial institution","—","bank account|bank loan"],
["because","conj.","เพราะ","Because I said so.","A1","since|as","—","because of"],
["become","v.","เป็นไป","What will you become?","A1","turn into|grow","—","become famous"],
["before","prep/adv.","ก่อน","Before noon.","A1","prior to|earlier","after|later","before long"],
["begin","v.","เริ่ม","Let's begin now.","A1","start|commence","end|finish","begin with"],
["believe","v.","เชื่อ","I believe you.","A1","trust|accept","disbelieve|doubt","believe in"],
["below","prep/adv.","ใต้","Below the surface.","A1","under|beneath","above|over","below zero"],
["best","adj/adv.","ดีที่สุด","The best day.","A1","finest|greatest","worst|poorest","best friend"],
["better","adj/adv.","ดีกว่า","Feel better now.","A1","superior|improved","worse|inferior","get better"],
["between","prep.","ระหว่าง","Between you and me.","A1","among|in the middle of","—","between them"],
["big","adj.","ใหญ่","A big house.","A1","large|great","small|little|tiny","big deal"],
["book","n/v.","หนังสือ, จอง","Read a book.","A1","novel|text","—","bookshelf|bookmark"],
["both","det/pron.","ทั้งคู่","Both are correct.","A1","the two|each","neither|none","both of"],
["break","v/n.","หัก, พัก","Take a break.","A1","snap|crack","fix|repair","break down|break up"],
["bring","v.","นำมา","Bring a friend.","A1","carry|transport","take|remove","bring back"],
["build","v.","สร้าง","Build a house.","A1","construct|make","demolish|destroy","build up"],
["business","n.","ธุรกิจ","Run a business.","A1","company|trade","—","business card"],
["but","conj.","แต่","I like it but...","A1","however|yet","—","—"],
["buy","v.","ซื้อ","Buy a car.","A1","purchase|acquire","sell|vend","buy out"],
["call","v/n.","เรียก","Call me later.","A1","phone|summon","answer","call back|call for"],
["can","v.","สามารถ","I can swim.","A1","able to|may","cannot","—"],
["car","n.","รถยนต์","Drive a car.","A1","automobile|vehicle","—","sports car"],
["care","v/n.","ใจใส่, ดูแล","Care about me.","A1","concern|look after","ignore|neglect","care for|take care"],
["change","v/n.","เปลี่ยน","Change clothes.","A1","alter|modify","keep|maintain","spare change"],
["character","n.","ลักษณะ, ตัวละคร","Good character.","A1","trait|personality","—","main character"],
["check","v/n.","ตรวจสอบ","Check again.","A1","verify|examine","—","check up|check in"],
["choose","v.","เลือก","Choose wisely.","A1","select|pick","reject|refuse","choose from"],
["city","n.","เมือง","Big city.","A1","metropolis|urban area","village|countryside","city center"],
["class","n.","ชั้นเรียน","In class.","A1","classroom|course|group","—","first class"],
["clean","adj/v.","สะอาด","Clean room.","A1","neat|tidy|pure","dirty|messy","clean up"],
["clear","adj/v.","ชัดเจน","Clear sky.","A1","obvious|transparent","unclear|vague","make clear"],
["close","v/adj.","ปิด, ใกล้","Close the door.","A1","shut|seal","open|unlock","close to"],
["come","v.","มา","Come here!","A1","arrive|approach","leave|go away","come back|come true"],
["common","adj.","ธรรมดา","Common sense.","A1","usual|ordinary","rare|uncommon","common ground"],
["company","n.","บริษัท","Work for a company.","A1","firm|business","—","good company"],
["continue","v.","ต่อ","Continue reading.","A1","go on|proceed","stop|cease","continue with"],
["correct","adj/v.","ถูก, แก้ไข","Correct answer.","A1","right|accurate","incorrect|wrong","politically correct"],
["cost","v/n.","ราคา","How much does it cost?","A1","price|expense","—","cost of living"],
["country","n.","ประเทศ","My country.","A1","nation|land","city|town","developing country"],
["course","n.","หลักสูตร","Take a course.","A1","class|curriculum","—","of course"],
["cry","v/n.","ร้อง","Don't cry.","A1","weep|shed tears","laugh|smile","cry out"],
["culture","n.","วัฒนธรรม","Japanese culture.","A1","civilization|tradition","—","pop culture"],
["cut","v/n.","ตัด","Cut the paper.","A1","slice|sever","join|connect","cut off|cut down"],
["day","n.","วัน","Nice day.","A1","24 hours|daytime","night|evening","day care|holiday"],
["dead","adj.","ตาย","Dead battery.","A1","deceased|lifeless","alive|living","dead end"],
["deal","v/n.","ข้อตกลง, จัดการ","Make a deal.","A1","agreement|transaction","—","big deal|good deal"],
["different","adj.","แตกต่าง","Different colors.","A1","distinct|unlike|various","same|similar","different from"],
["difficult","adj.","ยาก","Difficult task.","A1","hard|challenging","easy|simple","difficult time"],
["dinner","n.","เย็น","Eat dinner.","A1","evening meal|supper","breakfast|lunch","dinner party"],
["do","v.","ทำ","What do you do?","A1","perform|execute","—","do well|do damage"],
["doctor","n.","หมอ","See a doctor.","A1","physician|surgeon","—","family doctor"],
["dog","n.","สุนัข","Walk the dog.","A1","canine|pet|animal","cat","guide dog"],
["dream","v/n.","ฝัน","Sweet dream.","A1","aspiration|fantasy","reality|fact","bad dream|dream of"],
["drink","v/n.","ดื่ม, เครื่องดื่ม","Drink water.","A1","beverage|sip|consume","fast|abstain","have a drink"],
["eat","v.","กิน","Eat healthy.","A1","consume|feed on","fast|starve","eat out|eat up"],
["end","n/v.","จบ, ปลาย","The end.","A1","finish|stop|conclusion","start|begin","in the end"],
["enjoy","v.","สนุก","Enjoy the day.","A1","love|like|have fun","suffer|dislike","enjoy yourself"],
["enough","adj/adv.","พอ","Enough food.","A1","sufficient|adequate","insufficient|too little","good enough"],
["event","n.","เหตุการณ์","Major event.","A1","occasion|happening","—","sporting event"],
["every","det.","ทุก","Every day.","A1","each|all","none|no","every time"],
["example","n.","ตัวอย่าง","For example.","A1","instance|case","—","good example"],
["family","n.","ครอบครัว","My family.","A1","relatives|household","—","family member"],
["fast","adj/adv.","เร็ว","Drive fast.","A1","quick|rapid","slow|sluggish","fast food"],
["feel","v.","รู้สึก","Feel great.","A1","sense|experience","—","feel like"],
["find","v.","พบ","Find the answer.","A1","discover|locate","lose|miss","find out"],
["food","n.","อาหาร","Delicious food.","A1","meal|nutrition|eat","—","fast food"],
["free","adj/v.","ฟรี, อิสระ","Free time.","A1","no cost|liberate","captive|costly","free of charge"],
["friend","n.","เพื่อน","Best friend.","A1","companion|buddy","enemy|foe","close friend"],
["future","n/adj.","อนาคต","Bright future.","A1","upcoming|tomorrow","past|history","in the future"],
["give","v.","ให้","Give me a hand.","A1","provide|offer","take|receive","give up|give in"],
["go","v.","ไป","Go away!","A1","travel|move|proceed","stay|remain","go on|go out"],
["good","adj.","ดี","Good morning.","A1","nice|excellent|fine","bad|poor","good luck|as good as"],
["group","n.","กลุ่ม","Work in a group.","A1","team|bunch|collection","individual|alone","peer group"],
["grow","v.","เติบโต","Grow quickly.","A1","develop|increase|expand","shrink|decrease","grow up"],
["happen","v.","เกิดขึ้น","What happened?","A1","occur|take place","—","happen to"],
["happy","adj.","มีความสุข","Happy birthday!","A1","joyful|glad|pleased","sad|unhappy","happy hour"],
["hard","adj/adv.","ยาก, หนัก","Work hard.","A1","difficult|solid|firm","easy|soft","hard work"],
["have","v.","มี","I have a car.","A1","possess|own","lack|not have","have to"],
["help","v/n.","ช่วย","Can you help me?","A1","assist|support","hinder|obstruct","help out"],
["home","n.","บ้าน","Go home.","A1","house|residence","work|office","home town"],
["hope","v/n.","หวัง","Hope for the best.","A1","wish|expect","despair|give up","hope for"],
["house","n.","บ้าน","Nice house.","A1","home|building","—","house work"],
["idea","n.","ความคิด","Great idea!","A1","thought|concept","—","no idea"],
["if","conj.","ถ้า","If you want.","A1","when|provided that","—","what if"],
["important","adj.","สำคัญ","Very important.","A1","significant|crucial|major","unimportant|trivial","most important"],
["interest","n/v.","ความสนใจ","Show interest.","A1","attention|concern|hobby","boredom|apathy","rate of interest"],
["job","n.","งาน","Great job!","A1","work|career|task","unemployment","job application"],
["keep","v.","เก็บ, รักษา","Keep going.","A1","maintain|continue|hold","give up|stop","keep up|keep in touch"],
["kind","adj/n.","ใจดี, ประเภท","Very kind.","A1","nice|gentle|type","cruel|mean","kind of|what kind"],
["know","v.","รู้","I know the answer.","A1","understand|be aware","not know|ignore","know how|know about"],
["large","adj.","ใหญ่","Large group.","A1","big|huge|great","small|tiny","large scale"],
["last","adj/v.","สุดท้าย, ยืน","Last chance.","A1","final|previous|endure","first|next","last minute"],
["learn","v.","เรียนรู้","Learn English.","A1","study|gain knowledge","forget|ignore","learn by heart"],
["leave","v.","ออกจาก","Leave the room.","A1","depart|go","arrive|come","leave out|take leave"],
["let","v.","อนุญาต","Let me try.","A1","allow|permit","forbid|prevent","let go|let down"],
["life","n.","ชีวิต","My life.","A1","existence|living","death","daily life"],
["like","v/prep.","ชอบ","I like it.","A1","enjoy|love|similar to","dislike|hate","like that|feel like"],
["live","v/adj.","อยู่","Live well.","A1","reside|exist|alive","die|dead","live in|live up to"],
["long","adj/adv.","ยาว","Long road.","A1","lengthy|extended","short|brief","long ago|long time"],
["look","v/n.","มอง, ดู","Look at me.","A1","see|observe|appearance","—","look for|look out"],
["lose","v.","แพ้, ทำหาย","Don't lose hope.","A1","misplace|fail|defeat","find|win","lose track"],
["love","v/n.","รัก","I love you.","A1","adore|care for","hate|dislike","fall in love"],
["make","v.","ทำ","Make a wish.","A1","create|produce","break|destroy","make sure|make sense"],
["man","n.","ผู้ชาย","Young man.","A1","male|gentleman","woman|female","businessman"],
["mean","v/adj.","หมายความ, ใจร้าย","What does it mean?","A1","signify|indicate|unkind","nice|kind","mean to"],
["meet","v.","พบ","Meet me here.","A1","encounter|gather","miss|avoid","meet up|meet with"],
["mind","n/v.","จิตใจ, ห้ามใจ","Change your mind.","A1","brain|intellect|care","—","never mind"],
["money","n.","เงิน","Save money.","A1","cash|currency","—","money back"],
["most","det/adv.","มากที่สุด","Most people.","A1","greatest|maximum","least|minimum","most of all"],
["move","v/n.","เคลื่อนที่","Move forward.","A1","go|shift|transfer","stay|remain","move on|move in"],
["much","det/adv.","มาก","Too much.","A1","a lot|plenty","little|few","very much|how much"],
["must","v.","ต้อง","You must go.","A1","have to|need to","can avoid|optional","—"],
["name","n/v.","ชื่อ","What's your name?","A1","title|label","—","first name|last name"],
["need","v/n.","ต้องการ","I need help.","A1","require|want","have|possess","basic need"],
["never","adv.","ไม่เคย","Never give up.","A1","not ever|no time","always|forever","never mind"],
["new","adj.","ใหม่","New ideas.","A1","recent|fresh|modern","old|ancient","brand new"],
["next","adj/adv.","ถัดไป","Next week.","A1","following|coming","previous|last","next to|next time"],
["night","n.","กลางคืน","Good night.","A1","evening|darkness","day|morning","last night|night shift"],
["now","adv.","ตอนนี้","Do it now.","A1","at this moment|immediately","later|then","right now"],
["off","adv/prep.","ออก","Turn off.","A1","away|not working","on|running","off duty|day off"],
["old","adj.","เก่า, แก่","Old house.","A1","ancient|aged","new|young","old enough"],
["open","adj/v.","เปิด","Open the door.","A1","unlock|access","close|shut","open up|wide open"],
["other","det/pron.","อื่น","Other people.","A1","different|additional","same|this","on the other hand"],
["over","prep/adv.","เหนือ, เสร็จ","Game over.","A1","above|finished|across","under|below","over and over"],
["own","adj/v.","เป็นเจ้าของ","My own car.","A1","possess|have|personal","borrow|rent","on your own"],
["part","n/v.","ส่วน","Take part.","A1","section|piece|role","whole|all","part of|take part"],
["pay","v/n.","จ่าย","Pay attention.","A1","spend|compensate","receive|earn","pay off|pay back"],
["people","n.","ผู้คน","Many people.","A1","persons|humans|individuals","—","people skills"],
["place","n/v.","สถานที่","A nice place.","A1","location|spot|put","—","in place|take place"],
["plan","n/v.","แผน","Make a plan.","A1","design|organize","—","plan ahead"],
["play","v/n.","เล่น","Let's play!","A1","participate|drama","work","play a role"],
["please","v/interj.","กรุณา, ทำให้พอใจ","Please help.","A1","satisfy|delight","annoy|displease","please yourself"],
["put","v.","วาง","Put it down.","A1","place|set|lay","remove|take","put on|put off"],
["read","v.","อ่าน","Read a book.","A1","study|look over","write","read out"],
["ready","adj.","พร้อม","Are you ready?","A1","prepared|set","unprepared|not ready","get ready"],
["really","adv.","จริงๆ","Really nice.","A1","truly|very|actually","not really","—"],
["reason","n/v.","เหตุผล","Good reason.","A1","cause|logic|justification","—","for a reason"],
["remember","v.","จำ","Remember this.","A1","recall|recollect","forget|overlook","remember to"],
["right","adj/adv.","ถูก, ขวา","Turn right.","A1","correct|proper|exact","wrong|left","right away"],
["room","n.","ห้อง","Nice room.","A1","space|chamber","—","living room"],
["same","adj.","เดียวกัน","The same one.","A1","identical|equal|similar","different|other","same as"],
["say","v.","พูด","What did you say?","A1","speak|tell|utter","listen|hear","say goodbye"],
["school","n.","โรงเรียน","Go to school.","A1","institution|educational facility","—","school day"],
["see","v.","เห็น","I can see it.","A1","observe|look at|understand","miss|overlook","see through"],
["seem","v.","ดูเหมือน","It seems hard.","A1","appear|look|feel","—","seem like"],
["show","v/n.","แสดง","Show me.","A1","display|demonstrate|present","hide|conceal","show off"],
["small","adj.","เล็ก","Small house.","A1","tiny|little|minor","large|big|great","small talk"],
["start","v/n.","เริ่ม","Start again.","A1","begin|commence|launch","stop|end|finish","fresh start"],
["still","adj/adv.","ยังคง","Still here.","A1","continuing|quiet|calm","moving|changed","stand still"],
["stop","v/n.","หยุด","Stop right now.","A1","halt|cease|finish","start|continue","stop sign"],
["student","n.","นักเรียน","Hard student.","A1","learner|pupil","teacher|instructor","college student"],
["study","v/n.","เรียน","Study hard.","A1","learn|research|investigation","forget|ignore","study abroad"],
["sure","adj/adv.","แน่นอน","Are you sure?","A1","certain|definite","unsure|uncertain","make sure"],
["take","v.","เอา, ใช้","Take a break.","A1","grab|bring|spend","give|leave","take care|take off"],
["talk","v/n.","พูดคุย","Let's talk.","A1","speak|discuss|chat","be silent|listen","talk about"],
["tell","v.","บอก","Tell the truth.","A1","say|inform|narrate","ask|wonder","tell apart"],
["thing","n.","สิ่งของ","What's that thing?","A1","object|item|matter","—","the thing is"],
["think","v.","คิด","Think carefully.","A1","consider|believe|imagine","—","think about"],
["time","n.","เวลา","What time is it?","A1","period|moment|duration","—","on time|free time"],
["together","adv.","ด้วยกัน","Work together.","A1","jointly|as one|combined","apart|separately","get together"],
["try","v.","พยายาม","Try again.","A1","attempt|endeavor|test","give up|quit","try out"],
["turn","v/n.","เลี้ยว, หมุน","Turn left.","A1","rotate|change|go","—","in turn|turn off"],
["understand","v.","เข้าใจ","Do you understand?","A1","comprehend|grasp|follow","misunderstand|confuse","understand that"],
["use","v/n.","ใช้","Use it carefully.","A1","utilize|apply|employ","—","make use of"],
["wait","v.","รอ","Wait for me.","A1","hold on|pause","proceed|go","wait for|can't wait"],
["want","v.","อยาก","I want more.","A1","desire|wish|need","have enough","—"],
["watch","v/n.","ดู, นาฬิกา","Watch a movie.","A1","observe|look at|timepiece","—","watch out"],
["way","n.","ทาง, วิธี","Find a way.","A1","method|road|direction","—","by the way"],
["well","adj/adv.","ดี","Do well.","A1","good|fine|healthy","badly|poorly","as well|well done"],
["what","pron/det.","อะไร","What is this?","A1","which|that|—","—","what if|so what"],
["when","adv/conj.","เมื่อ","When is it?","A1","at the time","—","since when"],
["where","adv/conj.","ที่ไหน","Where are you?","A1","in what place","—","where to"],
["who","pron.","ใคร","Who is that?","A1","which person","—","who else|know who"],
["why","adv.","ทำไม","Why not?","A1","for what reason","—","why not"],
["will","v.","จะ","I will try.","A1","going to|shall","won't","—"],
["with","prep.","กับ, ด้วย","Come with me.","A1","together|using","without|alone","—"],
["woman","n.","ผู้หญิง","Young woman.","A1","female|lady","man|male","businesswoman"],
["word","n.","คำ","Every word.","A1","term|expression","—","key word"],
["work","v/n.","ทำงาน","Hard work.","A1","job|labor|function","rest|play","work out|teamwork"],
["world","n.","โลก","Around the world.","A1","earth|globe|universe","—","world class"],
["write","v.","เขียน","Write a letter.","A1","compose|record","erase|delete","write down"],
["year","n.","ปี","Every year.","A1","twelve months|annual period","—","this year|last year"],
["young","adj.","เยาว์","Young people.","A1","youthful|new","old|aged","young man|young at heart"],
// A2
["ability","n.","ความสามารถ","Natural ability.","A2","skill|talent|capacity","inability|weakness","ability to"],
["achieve","v.","บรรลุ","Achieve the goal.","A2","accomplish|attain|succeed","fail|lose","achieve success"],
["action","n.","การกระทำ","Take action.","A2","activity|deed|step","inaction|passivity","take action|course of action"],
["active","adj.","กระตือรือร้น","Active lifestyle.","A2","energetic|lively|busy","passive|lazy|inactive","active role"],
["activity","n.","กิจกรรม","Fun activity.","A2","pursuit|exercise|event","inactivity|idleness","physical activity"],
["actually","adv.","จริงๆ","Actually no.","A2","in fact|truly|really","apparently|seemingly","—"],
["affect","v.","ส่งผลกระทบ","Affect behavior.","A2","influence|impact|touch","—","seriously affect"],
["afraid","adj.","กลัว","Afraid of dark.","A2","scared|fearful|frightened","brave|fearless|bold","afraid of"],
["age","n.","อายุ","School age.","A2","years old|era|period","—","come of age"],
["agree","v.","เห็นด้วย","I agree with you.","A2","consent|accept|concur","disagree|refuse|oppose","agree to|agree with"],
["air","n.","อากาศ","Fresh air.","A2","atmosphere|breeze","—","open air|air conditioning"],
["alone","adj/adv.","คนเดียว","Live alone.","A2","by oneself|solo|isolated","together|with others","leave alone"],
["amount","n.","ปริมาณ","A large amount.","A2","quantity|volume|sum","—","amount of"],
["animal","n.","สัตว์","Wild animal.","A2","creature|beast","—","domestic animal"],
["appear","v.","ปรากฏ","Appear suddenly.","A2","seem|come into view","disappear|vanish","appear on"],
["apply","v.","สมัคร, นำไปใช้","Apply for job.","A2","request|use|implement","ignore|refuse","apply for"],
["arrange","v.","จัดการ","Arrange meeting.","A2","organize|plan|prepare","disrupt|confuse","arrange for"],
["art","n.","ศิลปะ","Modern art.","A2","artwork|creative work","science","work of art"],
["article","n.","บทความ","Read an article.","A2","piece|text|essay","—","newspaper article"],
["assistant","n.","ผู้ช่วย","Teaching assistant.","A2","aide|helper","boss|supervisor","executive assistant"],
["attention","n.","ความสนใจ","Pay attention.","A2","focus|concentration","neglect|ignorance","pay attention|draw attention"],
["authority","n.","อำนาจ","Legal authority.","A2","power|control|expert","weakness","authority figure"],
["avoid","v.","หลีกเลี่ยง","Avoid mistakes.","A2","evade|steer clear|shun","face|confront","avoid doing"],
["basic","adj.","พื้นฐาน","Basic skills.","A2","fundamental|essential|simple","advanced|complex|sophisticated","basic knowledge"],
["behavior","n.","พฤติกรรม","Good behavior.","A2","conduct|manner|action","—","human behavior"],
["benefit","n/v.","ผลประโยชน์","Great benefit.","A2","advantage|profit|help","disadvantage|harm","for the benefit"],
["busy","adj.","ยุ่ง","Very busy.","A2","occupied|active|engaged","free|idle|available","busy schedule"],
["career","n.","อาชีพ","Build a career.","A2","profession|vocation|job","hobby|pastime","career path"],
["certain","adj.","แน่นอน","I'm certain.","A2","sure|definite|confident","uncertain|unsure","for certain"],
["choice","n.","ตัวเลือก","Your choice.","A2","option|selection","—","make a choice"],
["communicate","v.","สื่อสาร","Communicate clearly.","A2","convey|express|connect","misunderstand","communicate with"],
["community","n.","ชุมชน","Local community.","A2","society|neighborhood|group","individual","community service"],
["competition","n.","การแข่งขัน","Stiff competition.","A2","rivalry|contest|race","cooperation","fair competition"],
["complete","adj/v.","สมบูรณ์","Complete the task.","A2","finish|accomplish|whole","incomplete|unfinished","complete with"],
["confident","adj.","มั่นใจ","Confident speaker.","A2","assured|bold|self-assured","shy|timid|nervous","confident about"],
["consider","v.","พิจารณา","Consider this.","A2","think about|contemplate|regard","ignore|disregard","consider as"],
["copy","v/n.","สำเนา","Make a copy.","A2","duplicate|reproduce|replica","original","copy from"],
["create","v.","สร้าง","Create something new.","A2","make|design|produce","destroy|demolish","create opportunities"],
["decide","v.","ตัดสินใจ","Decide now.","A2","choose|determine|conclude","hesitate|undecide","decide on"],
["develop","v.","พัฒนา","Develop skills.","A2","grow|advance|create","decline|regress","develop into"],
["discuss","v.","พูดคุย","Discuss options.","A2","talk about|debate|converse","ignore|avoid","discuss with"],
["education","n.","การศึกษา","Good education.","A2","learning|schooling|knowledge","ignorance","higher education"],
["effort","n.","ความพยายาม","Great effort.","A2","attempt|work|exertion","laziness|inaction","make effort"],
["encourage","v.","สนับสนุน","Encourage students.","A2","motivate|inspire|support","discourage|prevent","encourage to"],
["environment","n.","สิ่งแวดล้อม","Clean environment.","A2","surroundings|nature|setting","—","protect the environment"],
["experience","n/v.","ประสบการณ์","Work experience.","A2","knowledge|skill|undergo","inexperience","learning experience"],
["explain","v.","อธิบาย","Explain clearly.","A2","describe|clarify|tell","confuse|complicate","explain to"],
["express","v.","แสดงออก","Express feelings.","A2","show|convey|voice","suppress|hide","express yourself"],
["failure","n.","ความล้มเหลว","Learn from failure.","A2","defeat|loss|mistake","success|victory|achievement","failure rate"],
["familiar","adj.","คุ้นเคย","Familiar face.","A2","known|recognized|common","unfamiliar|strange","familiar with"],
["focus","v/n.","เน้น","Focus on work.","A2","concentrate|center|emphasize","distract|scatter","focus on"],
["follow","v.","ติดตาม","Follow the rules.","A2","obey|comply|pursue","lead|disobey|ignore","follow up|follow through"],
["force","n/v.","แรง, บังคับ","By force.","A2","power|pressure|compel","weakness|persuade","by force|air force"],
["form","n/v.","แบบฟอร์ม, ก่อร่าง","Fill in a form.","A2","document|shape|create","—","take form"],
["forward","adj/adv.","ไปข้างหน้า","Move forward.","A2","ahead|onward|progress","backward|behind","look forward"],
["gather","v.","รวมตัว","Gather together.","A2","collect|assemble|meet","scatter|separate","gather information"],
["goal","n.","เป้าหมาย","Set a goal.","A2","target|aim|objective","—","achieve goal"],
["government","n.","รัฐบาล","Local government.","A2","authority|administration|state","people|citizens","central government"],
["grade","n/v.","คะแนน, ระดับ","Good grade.","A2","mark|score|level","—","grade school"],
["habit","n.","นิสัย","Good habit.","A2","custom|routine|practice","—","healthy habit"],
["health","n.","สุขภาพ","Good health.","A2","wellness|fitness|wellbeing","illness|sickness","mental health"],
["healthy","adj.","สุขภาพดี","Healthy lifestyle.","A2","fit|well|nutritious","unhealthy|sick|ill","healthy diet"],
["history","n.","ประวัติศาสตร์","World history.","A2","past|record|background","present|future","history lesson"],
["include","v.","รวมถึง","Include everyone.","A2","contain|involve|incorporate","exclude|omit","include in"],
["increase","v/n.","เพิ่มขึ้น","Prices increase.","A2","rise|grow|expand","decrease|fall|drop","sharp increase"],
["information","n.","ข้อมูล","Useful information.","A2","data|facts|knowledge","—","exchange information"],
["instead","adv.","แทน","Do this instead.","A2","in place of|rather|alternatively","—","instead of"],
["join","v.","เข้าร่วม","Join the club.","A2","participate|connect|become member","leave|quit","join forces"],
["knowledge","n.","ความรู้","General knowledge.","A2","understanding|information|wisdom","ignorance","base knowledge"],
["language","n.","ภาษา","Foreign language.","A2","tongue|speech|dialect","—","body language"],
["leader","n.","ผู้นำ","Strong leader.","A2","head|chief|commander","follower","team leader"],
["local","adj.","ท้องถิ่น","Local market.","A2","nearby|community|regional","foreign|distant","local government"],
["manage","v.","จัดการ","Manage time well.","A2","handle|control|organize","fail|lose control","manage to"],
["media","n.","สื่อ","Social media.","A2","press|communication|broadcast","—","mass media"],
["message","n/v.","ข้อความ","Leave a message.","A2","note|communication|text","—","text message"],
["method","n.","วิธีการ","New method.","A2","way|approach|technique","—","learning method"],
["modern","adj.","สมัยใหม่","Modern life.","A2","contemporary|current|new","old|ancient|outdated","modern technology"],
["moreover","adv.","ยิ่งกว่านั้น","Moreover, it helps.","A2","furthermore|also|additionally","—","—"],
["natural","adj.","ธรรมชาติ","Natural beauty.","A2","organic|native|normal","artificial|man-made|unnatural","natural resource"],
["note","n/v.","บันทึก","Take notes.","A2","remark|record|notice","—","make a note"],
["notice","v/n.","สังเกต","Did you notice?","A2","observe|see|detect","ignore|miss|overlook","notice that"],
["offer","v/n.","เสนอ","Make an offer.","A2","propose|suggest|give","withdraw|refuse","job offer"],
["often","adv.","บ่อย","Often late.","A2","frequently|regularly|usually","rarely|seldom|never","very often"],
["opinion","n.","ความเห็น","My opinion.","A2","view|belief|perspective","fact","in my opinion"],
["particular","adj/n.","เฉพาะ","Particular problem.","A2","specific|special|certain","general|common|typical","in particular"],
["perhaps","adv.","บางที","Perhaps tomorrow.","A2","maybe|possibly","certainly|definitely","—"],
["popular","adj.","ได้รับความนิยม","Popular song.","A2","well-known|liked|common","unpopular|disliked","become popular"],
["position","n.","ตำแหน่ง","Job position.","A2","place|role|stance","—","first position"],
["possible","adj.","เป็นไปได้","Is it possible?","A2","feasible|achievable|likely","impossible|unlikely","as soon as possible"],
["prepare","v.","เตรียม","Prepare carefully.","A2","get ready|organize|plan","ignore|neglect","prepare for"],
["present","adj/v/n.","ปัจจุบัน, นำเสนอ","Present your idea.","A2","current|show|gift","absent|past","at present"],
["problem","n.","ปัญหา","Solve the problem.","A2","issue|difficulty|challenge","solution|answer","serious problem"],
["process","n/v.","กระบวนการ","Learning process.","A2","procedure|method|develop","—","in process"],
["produce","v.","ผลิต","Produce results.","A2","make|create|generate","consume|destroy","produce evidence"],
["progress","n/v.","ความก้าวหน้า","Make progress.","A2","advancement|development|improvement","regression|decline","track progress"],
["proper","adj.","ถูกต้อง","Proper behavior.","A2","correct|appropriate|suitable","improper|wrong|inappropriate","proper way"],
["protect","v.","ปกป้อง","Protect the planet.","A2","guard|defend|shield","attack|endanger|expose","protect from"],
["prove","v.","พิสูจน์","Prove your point.","A2","demonstrate|show|verify","disprove|deny|refute","prove that"],
["public","adj/n.","สาธารณะ","Public opinion.","A2","open|community|people","private|personal","general public"],
["purpose","n.","จุดประสงค์","What's the purpose?","A2","aim|goal|intention","—","on purpose"],
["realize","v.","ตระหนัก","I realize now.","A2","understand|recognize|become aware","ignore|overlook","realize that"],
["recent","adj.","เร็วๆ นี้","Recent news.","A2","latest|current|new","old|ancient|past","in recent years"],
["relationship","n.","ความสัมพันธ์","Good relationship.","A2","connection|bond|association","separation|conflict","close relationship"],
["rely","v.","พึ่งพา","Rely on friends.","A2","depend|count on|trust","self-sufficient|independent","rely on"],
["respect","v/n.","เคารพ","Earn respect.","A2","honor|admire|regard","disrespect|insult","mutual respect"],
["responsibility","n.","ความรับผิดชอบ","Take responsibility.","A2","duty|obligation|accountability","freedom|irresponsibility","personal responsibility"],
["result","n/v.","ผลลัพธ์","The result is good.","A2","outcome|consequence|effect","cause","as a result"],
["role","n.","บทบาท","Important role.","A2","part|function|position","—","key role|play a role"],
["serve","v.","รับใช้","Serve the community.","A2","help|assist|provide","—","serve as"],
["share","v/n.","แบ่งปัน","Share knowledge.","A2","divide|give|portion","keep|take","share with|market share"],
["simple","adj.","ง่าย","Simple task.","A2","easy|basic|clear","complex|complicated","keep it simple"],
["situation","n.","สถานการณ์","Difficult situation.","A2","condition|circumstance|case","—","current situation"],
["skill","n.","ทักษะ","Learn a new skill.","A2","ability|expertise|talent","weakness|inability","develop skills"],
["social","adj.","ทางสังคม","Social media.","A2","community|public|society","personal|private","social life"],
["solve","v.","แก้ปัญหา","Solve the problem.","A2","fix|resolve|answer","create|cause","solve together"],
["speak","v.","พูด","Speak clearly.","A2","talk|say|communicate","be silent|listen","speak to|speak out"],
["special","adj.","พิเศษ","Special offer.","A2","unique|extraordinary|specific","ordinary|normal","special occasion"],
["state","n/v.","รัฐ, ระบุ","State your name.","A2","condition|declare|nation","—","mental state"],
["subject","n.","เรื่อง, วิชา","Favorite subject.","A2","topic|theme|course","object","subject matter"],
["suggest","v.","แนะนำ","I suggest this.","A2","recommend|propose|advise","oppose|reject","suggest that"],
["support","v/n.","สนับสนุน","Support each other.","A2","help|back|assist","oppose|hinder","financial support"],
["technology","n.","เทคโนโลยี","New technology.","A2","innovation|tools|digital","—","modern technology"],
["themselves","pron.","ตัวเอง","Do it themselves.","A2","on their own|personally","—","by themselves"],
["though","conj/adv.","แม้ว่า","Even though.","A2","although|despite|however","—","as though"],
["throughout","prep/adv.","ตลอด","Throughout the day.","A2","all through|during|everywhere","partly","throughout the year"],
["topic","n.","หัวข้อ","What's the topic?","A2","subject|theme|issue","—","hot topic"],
["trade","n/v.","การค้า","International trade.","A2","commerce|exchange|deal","—","free trade"],
["type","n/v.","ประเภท, พิมพ์","What type?","A2","kind|sort|category","—","blood type"],
["typical","adj.","ปกติ","Typical day.","A2","normal|usual|ordinary","unusual|atypical","typical behavior"],
["various","adj.","หลากหลาย","Various options.","A2","different|diverse|several","same|identical|uniform","various types"],
["view","n/v.","มุมมอง, ดู","Point of view.","A2","perspective|opinion|see|look at","—","in view of"],
["write","v.","เขียน","Write an essay.","A2","compose|record|put down","erase|delete","write down"],
// B1 — Core exam words
["absence","n.","การขาดหาย","Long absence.","B1","lack|non-attendance|missing","presence|attendance","in the absence"],
["abstract","adj/n.","บทคัดย่อ, นามธรรม","Abstract concept.","B1","theoretical|conceptual|summary","concrete|physical","abstract art"],
["accommodate","v.","จัดหาที่","Accommodate guests.","B1","house|adjust|adapt","reject|refuse","accommodate needs"],
["accomplish","v.","บรรลุ","Accomplish goals.","B1","achieve|complete|fulfill","fail|miss","accomplish task"],
["accumulate","v.","สะสม","Accumulate wealth.","B1","collect|gather|build up","distribute|spend","accumulate experience"],
["accurate","adj.","ถูกต้อง","Accurate data.","B1","precise|correct|exact","inaccurate|wrong|incorrect","highly accurate"],
["achieve","v.","บรรลุ","Achieve success.","B1","accomplish|attain|reach","fail|miss","achieve goal"],
["acquire","v.","ได้มา","Acquire skills.","B1","obtain|gain|get","lose|give away","acquire knowledge"],
["adapt","v.","ปรับตัว","Adapt to change.","B1","adjust|modify|accommodate","resist|reject","adapt to"],
["adequate","adj.","เพียงพอ","Adequate supply.","B1","sufficient|enough|satisfactory","insufficient|inadequate","adequate resources"],
["adjust","v.","ปรับ","Adjust the plan.","B1","modify|change|adapt","keep|maintain","adjust to"],
["administration","n.","การบริหาร","School administration.","B1","management|organization","—","business administration"],
["admit","v.","ยอมรับ","Admit mistake.","B1","confess|accept|acknowledge","deny|refuse","admit to"],
["adopt","v.","ยอมรับ, รับเลี้ยง","Adopt new approach.","B1","accept|take on|embrace","reject|abandon","adopt a child"],
["advance","v/n.","ก้าวหน้า","Technology advance.","B1","progress|improve|develop","retreat|decline","advance in"],
["advocate","v.","สนับสนุน","Advocate change.","B1","support|promote|urge","oppose|reject","advocate for"],
["affect","v.","ส่งผลกระทบต่อ","Affect results.","B1","influence|impact","—","greatly affect"],
["aggressive","adj.","ก้าวร้าว","Aggressive behavior.","B1","hostile|violent|assertive","passive|gentle","aggressive stance"],
["aid","v/n.","ช่วย","Provide aid.","B1","help|assist|support","hinder|obstruct","financial aid"],
["allocate","v.","จัดสรร","Allocate resources.","B1","distribute|assign|allot","withhold","allocate funds"],
["alter","v.","เปลี่ยนแปลง","Alter the plan.","B1","change|modify|adjust","keep|preserve","alter course"],
["alternative","n/adj.","ทางเลือก","Seek alternative.","B1","option|choice|substitute","mandatory","as an alternative"],
["ambitious","adj.","ทะเยอทะยาน","Ambitious goals.","B1","aspiring|driven|motivated","unambitious|lazy","ambitious plan"],
["analyse","v.","วิเคราะห์","Analyse data.","B1","examine|study|evaluate","—","carefully analyse"],
["annual","adj.","รายปี","Annual report.","B1","yearly|recurring","one-time","annual meeting"],
["anxiety","n.","ความวิตกกังวล","Social anxiety.","B1","worry|unease|nervousness","calm|peace","anxiety about"],
["appealing","adj.","น่าสนใจ","Appealing offer.","B1","attractive|tempting|inviting","unappealing|boring","visually appealing"],
["appropriate","adj.","เหมาะสม","Appropriate answer.","B1","suitable|fitting|proper","inappropriate|unsuitable","appropriate for"],
["approximately","adv.","ประมาณ","Approximately 200 people.","B1","roughly|about|around","exactly|precisely","approximately equal"],
["arise","v.","เกิดขึ้น","Problems may arise.","B1","occur|emerge|appear","disappear|vanish","arise from"],
["aspect","n.","ด้าน","Every aspect.","B1","side|facet|element","whole","every aspect"],
["aspire","v.","ปรารถนา","Aspire to succeed.","B1","hope|aim|strive","abandon|give up","aspire to"],
["assessment","n.","การประเมิน","Risk assessment.","B1","evaluation|judgment|appraisal","—","needs assessment"],
["asset","n.","สินทรัพย์","Valuable asset.","B1","property|resource|advantage","liability|burden","financial asset"],
["assign","v.","มอบหมาย","Assign roles.","B1","allocate|designate|give","withhold","assign to"],
["assist","v.","ช่วย","Assist customers.","B1","help|aid|support","hinder|obstruct","assist in"],
["associate","v.","เชื่อมโยง","Associate with group.","B1","connect|link|relate","separate|disconnect","associate with"],
["assume","v.","สมมุติ","Assume responsibility.","B1","suppose|presume|take on","know|verify","assume that"],
["atmosphere","n.","บรรยากาศ","Friendly atmosphere.","B1","environment|mood|air","—","earth atmosphere"],
["attempt","v/n.","พยายาม","Attempt to solve.","B1","try|endeavor|effort","give up|succeed","attempt to"],
["attitude","n.","ทัศนคติ","Positive attitude.","B1","opinion|perspective|outlook","—","attitude toward"],
["attract","v.","ดึงดูด","Attract attention.","B1","appeal|draw|interest","repel|bore","attract to"],
["authority","n.","อำนาจ","Government authority.","B1","power|control|expertise","weakness","authority figure"],
["available","adj.","สามารถหาได้","Resources available.","B1","accessible|obtainable|free","unavailable|scarce","immediately available"],
["average","adj/n.","เฉลี่ย","On average.","B1","mean|typical|normal","exceptional|extraordinary","on average"],
["aware","adj.","ตระหนัก","Stay aware.","B1","conscious|mindful|informed","unaware|ignorant","be aware of"],
["background","n.","ภูมิหลัง","Family background.","B1","history|setting|experience","—","educational background"],
["barrier","n.","อุปสรรค","Language barrier.","B1","obstacle|wall|hurdle","path|gateway","break barrier"],
["behaviour","n.","พฤติกรรม","Expected behaviour.","B1","conduct|manner|action","—","human behaviour"],
["benefit","v/n.","ประโยชน์","Benefit others.","B1","advantage|profit|gain","disadvantage|harm","mutual benefit"],
["capacity","n.","ความสามารถ","Full capacity.","B1","ability|volume|potential","incapacity|inability","full capacity"],
["career","n.","อาชีพ","Successful career.","B1","profession|vocation","hobby","career path"],
["challenge","n/v.","ความท้าทาย","Overcome challenge.","B1","difficulty|obstacle|problem","ease|reward","face challenge"],
["characteristic","n.","ลักษณะเฉพาะ","Physical characteristic.","B1","feature|trait|quality","—","distinctive characteristic"],
["citizen","n.","พลเมือง","Senior citizen.","B1","resident|national|person","foreigner|alien","responsible citizen"],
["claim","v/n.","อ้าง","Make a claim.","B1","assert|state|declare","deny|refute","claim that"],
["client","n.","ลูกค้า","Satisfy client.","B1","customer|customer|buyer","seller|vendor","regular client"],
["colleague","n.","เพื่อนร่วมงาน","Work with colleagues.","B1","coworker|associate|partner","rival|opponent","close colleague"],
["commitment","n.","ความมุ่งมั่น","Show commitment.","B1","dedication|devotion|pledge","indifference|neglect","personal commitment"],
["consequence","n.","ผลที่ตามมา","Face consequences.","B1","result|outcome|effect","cause|reason","as a consequence"],
["consistent","adj.","สม่ำเสมอ","Consistent performance.","B1","steady|regular|uniform","inconsistent|variable","consistent with"],
["context","n.","บริบท","In context.","B1","setting|background|situation","—","in context"],
["contribute","v.","มีส่วนร่วม","Contribute to society.","B1","give|add|provide","take|subtract","contribute to"],
["cope","v.","รับมือ","Cope with stress.","B1","manage|handle|deal with","fail|struggle","cope with"],
["creative","adj.","สร้างสรรค์","Creative thinking.","B1","inventive|imaginative|original","unoriginal|dull","creative solution"],
["crisis","n.","วิกฤต","Economic crisis.","B1","emergency|disaster|emergency","stability|peace","financial crisis"],
["crucial","adj.","สำคัญอย่างยิ่ง","Crucial decision.","B1","vital|critical|essential","unimportant|trivial","crucial role"],
["culture","n.","วัฒนธรรม","Global culture.","B1","society|tradition|heritage","—","cultural exchange"],
["deadline","n.","กำหนดส่ง","Meet deadline.","B1","due date|time limit|cut-off","—","miss deadline"],
["decision","n.","การตัดสินใจ","Final decision.","B1","choice|determination","—","make decision"],
["demonstrate","v.","แสดง","Demonstrate skills.","B1","show|prove|illustrate","hide|conceal","demonstrate how"],
["determine","v.","กำหนด","Determine outcome.","B1","decide|establish|figure out","—","determined by"],
["device","n.","อุปกรณ์","Smart device.","B1","apparatus|gadget|tool","—","mobile device"],
["discuss","v.","อภิปราย","Discuss solutions.","B1","talk|debate|examine","ignore|avoid","discuss with"],
["distinction","n.","ความแตกต่าง","Important distinction.","B1","difference|contrast|award","similarity","make distinction"],
["diverse","adj.","หลากหลาย","Diverse group.","B1","varied|mixed|different","uniform|homogeneous","culturally diverse"],
["dominant","adj.","เด่น","Dominant role.","B1","main|ruling|prevailing","subordinate|minor","dominant force"],
["effectively","adv.","มีประสิทธิผล","Work effectively.","B1","efficiently|productively|successfully","ineffectively","communicate effectively"],
["efficiency","n.","ประสิทธิภาพ","Improve efficiency.","B1","effectiveness|productivity","inefficiency|waste","fuel efficiency"],
["elaborate","adj/v.","ซับซ้อน, ขยายความ","Elaborate plan.","B1","detailed|complex|expand","simple|basic","elaborate on"],
["enhance","v.","เพิ่มคุณค่า","Enhance performance.","B1","improve|boost|increase","worsen|decrease","enhance skills"],
["ensure","v.","ทำให้แน่ใจ","Ensure safety.","B1","guarantee|make sure|secure","endanger|risk","ensure that"],
["environment","n.","สิ่งแวดล้อม","Natural environment.","B1","surroundings|nature|setting","—","clean environment"],
["establish","v.","ก่อตั้ง","Establish trust.","B1","found|create|set up","destroy|abolish","establish that"],
["evaluate","v.","ประเมิน","Evaluate performance.","B1","assess|judge|review","—","carefully evaluate"],
["evident","adj.","ชัดเจน","Evident mistake.","B1","clear|obvious|apparent","unclear|hidden|obscure","clearly evident"],
["expand","v.","ขยาย","Expand knowledge.","B1","grow|increase|extend","shrink|reduce|contract","expand into"],
["expertise","n.","ความชำนาญ","Technical expertise.","B1","skill|knowledge|mastery","inexperience","area of expertise"],
["factor","n.","ปัจจัย","Key factor.","B1","element|cause|variable","result|effect","contributing factor"],
["feature","n/v.","คุณสมบัติ","Main feature.","B1","characteristic|quality|trait","—","key feature"],
["flexible","adj.","ยืดหยุ่น","Flexible schedule.","B1","adaptable|adjustable|open","rigid|inflexible|fixed","flexible thinking"],
["fundamental","adj.","พื้นฐาน","Fundamental right.","B1","basic|essential|core","secondary|minor","fundamental change"],
["generate","v.","สร้าง","Generate ideas.","B1","produce|create|make","destroy|eliminate","generate income"],
["global","adj.","ระดับโลก","Global market.","B1","worldwide|international|universal","local|regional","global issue"],
["guideline","n.","แนวทาง","Follow guidelines.","B1","rule|direction|principle","—","provide guidelines"],
["highlight","v/n.","เน้น","Highlight key points.","B1","emphasize|feature|stress","overlook|ignore","highlight that"],
["identify","v.","ระบุ","Identify problems.","B1","recognize|detect|find","miss|overlook","identify as"],
["impact","n/v.","ผลกระทบ","Huge impact.","B1","effect|influence|result","—","have impact on"],
["implement","v.","นำไปใช้","Implement changes.","B1","apply|carry out|execute","ignore|abandon","implement plan"],
["imply","v.","บอกเป็นนัย","What does it imply?","B1","suggest|hint|indicate","state|declare","imply that"],
["indication","n.","สัญญาณ","Clear indication.","B1","sign|signal|evidence","—","give indication"],
["initiative","n.","ความคิดริเริ่ม","Take initiative.","B1","effort|drive|action","passivity|laziness","show initiative"],
["innovation","n.","นวัตกรรม","Drive innovation.","B1","new idea|invention|change","tradition|convention","technical innovation"],
["insight","n.","ความเข้าใจ","Valuable insight.","B1","understanding|perception|wisdom","ignorance","provide insight"],
["integrate","v.","รวมเข้าด้วยกัน","Integrate systems.","B1","combine|unite|merge","separate|divide","integrate into"],
["interaction","n.","ปฏิสัมพันธ์","Social interaction.","B1","communication|exchange|engagement","isolation","positive interaction"],
["interpret","v.","แปลความ","Interpret results.","B1","explain|understand|translate","misinterpret","interpret as"],
["involve","v.","เกี่ยวข้อง","Involve everyone.","B1","include|engage|require","exclude|omit","involve in"],
["issue","n/v.","ปัญหา, ออก","Major issue.","B1","problem|topic|matter","solution|answer","address issue"],
["justify","v.","ให้เหตุผล","Justify decision.","B1","explain|defend|prove","condemn|criticize","justify that"],
["maintain","v.","รักษา","Maintain quality.","B1","keep|preserve|uphold","neglect|abandon","maintain standards"],
["motivate","v.","กระตุ้น","Motivate students.","B1","inspire|encourage|drive","discourage|demotivate","motivate to"],
["objective","n.","วัตถุประสงค์","Clear objective.","B1","goal|aim|target|fair","subjective|biased","main objective"],
["obtain","v.","ได้มา","Obtain permission.","B1","get|acquire|gain","lose|give away","obtain from"],
["opportunity","n.","โอกาส","Great opportunity.","B1","chance|opening|possibility","obstacle|barrier","take opportunity"],
["outcome","n.","ผลลัพธ์","Positive outcome.","B1","result|effect|consequence","cause|reason","expected outcome"],
["overcome","v.","เอาชนะ","Overcome obstacles.","B1","conquer|defeat|master","surrender|fail","overcome challenges"],
["participate","v.","มีส่วนร่วม","Participate actively.","B1","join|take part|engage","withdraw|absent","participate in"],
["perspective","n.","มุมมอง","New perspective.","B1","view|outlook|angle","—","change perspective"],
["policy","n.","นโยบาย","New policy.","B1","rule|regulation|guideline","—","government policy"],
["potential","n/adj.","ศักยภาพ","Huge potential.","B1","possibility|ability|capacity","limitation","unlock potential"],
["priority","n.","ลำดับความสำคัญ","Top priority.","B1","main concern|first importance","secondary|optional","set priority"],
["procedure","n.","ขั้นตอน","Standard procedure.","B1","process|method|step","—","follow procedure"],
["professional","adj/n.","มืออาชีพ","Professional advice.","B1","expert|skilled|experienced","amateur|unprofessional","professional development"],
["promote","v.","ส่งเสริม","Promote health.","B1","support|advance|raise","demote|hinder","promote to"],
["relevant","adj.","เกี่ยวข้อง","Relevant information.","B1","related|applicable|pertinent","irrelevant|unrelated","relevant to"],
["require","v.","ต้องการ","Require effort.","B1","need|demand|call for","provide|offer","require that"],
["significant","adj.","มีนัยสำคัญ","Significant change.","B1","important|notable|major","insignificant|minor","statistically significant"],
["strategy","n.","กลยุทธ์","Winning strategy.","B1","plan|approach|method","—","develop strategy"],
["sufficient","adj.","เพียงพอ","Sufficient funds.","B1","enough|adequate|ample","insufficient|inadequate","more than sufficient"],
["sustain","v.","รักษา","Sustain growth.","B1","maintain|keep|support","destroy|end","sustain effort"],
["tendency","n.","แนวโน้ม","Natural tendency.","B1","inclination|trend|habit","opposite|reverse","tendency to"],
["theory","n.","ทฤษฎี","Economic theory.","B1","idea|concept|hypothesis","practice|fact","support theory"],
["transition","n.","การเปลี่ยนผ่าน","Smooth transition.","B1","change|shift|move","stability|continuity","transition to"],
["tremendous","adj.","มหาศาล","Tremendous effort.","B1","enormous|huge|great","tiny|small|minimal","tremendous impact"],
["unique","adj.","เป็นเอกลักษณ์","Unique approach.","B1","one of a kind|special|distinct","common|ordinary","unique feature"],
["utilize","v.","ใช้ประโยชน์","Utilize resources.","B1","use|employ|make use of","waste|ignore","fully utilize"],
["valid","adj.","ถูกต้อง","Valid argument.","B1","sound|legitimate|acceptable","invalid|unacceptable","remain valid"],
["vary","v.","แตกต่าง","Results vary.","B1","differ|change|fluctuate","stay same|remain constant","vary by"],
["visible","adj.","มองเห็นได้","Visible effect.","B1","clear|obvious|apparent","invisible|hidden|unseen","clearly visible"],
// B2
["abstract","adj/n.","บทคัดย่อ","Read the abstract.","B2","theoretical|conceptual|summary","concrete|specific","abstract thinking"],
["acknowledge","v.","ยอมรับ","Acknowledge mistake.","B2","admit|recognize|accept","deny|ignore","acknowledge that"],
["analytical","adj.","เชิงวิเคราะห์","Analytical thinking.","B2","critical|logical|systematic","intuitive","analytical skills"],
["ambiguous","adj.","กำกวม","Ambiguous statement.","B2","unclear|vague|uncertain","clear|definite","ambiguous meaning"],
["coherent","adj.","สอดคล้องกัน","Coherent argument.","B2","consistent|logical|clear","inconsistent|confused","coherent plan"],
["compelling","adj.","น่าเชื่อ","Compelling evidence.","B2","convincing|persuasive|powerful","weak|unconvincing","compelling reason"],
["comprehensive","adj.","ครอบคลุม","Comprehensive review.","B2","complete|thorough|wide-ranging","partial|incomplete","comprehensive study"],
["conceptual","adj.","เชิงแนวคิด","Conceptual framework.","B2","theoretical|abstract","practical|physical","conceptual thinking"],
["conclusive","adj.","ชี้ขาด","Conclusive evidence.","B2","definitive|decisive|final","inconclusive|uncertain","conclusive proof"],
["constraint","n.","ข้อจำกัด","Budget constraint.","B2","limitation|restriction|obstacle","freedom|flexibility","under constraint"],
["conventional","adj.","ตามขนบธรรมเนียม","Conventional approach.","B2","traditional|standard|typical","unconventional|novel","conventional wisdom"],
["correlate","v.","สัมพันธ์กัน","Correlate findings.","B2","relate|connect|link","unrelated|disconnected","correlate with"],
["criteria","n.","เกณฑ์","Selection criteria.","B2","standard|requirement|measure","—","meet criteria"],
["deduce","v.","อนุมาน","Deduce conclusion.","B2","infer|conclude|reason","guess|assume","deduce from"],
["differentiate","v.","แยกแยะ","Differentiate concepts.","B2","distinguish|separate|tell apart","confuse|mix up","differentiate between"],
["empirical","adj.","จากประสบการณ์จริง","Empirical evidence.","B2","experimental|factual|observed","theoretical|assumed","empirical study"],
["explicit","adj.","ชัดเจน","Explicit instructions.","B2","clear|direct|stated","implicit|indirect|vague","make explicit"],
["fallacy","n.","ความเชื่อผิดพลาด","Common fallacy.","B2","false belief|error|misconception","truth|fact","logical fallacy"],
["feasible","adj.","เป็นไปได้","Feasible plan.","B2","possible|viable|practical","impossible|impractical","feasible option"],
["fluctuation","n.","ความผันผวน","Market fluctuation.","B2","variation|change|instability","stability|consistency","price fluctuation"],
["framework","n.","กรอบแนวคิด","Theoretical framework.","B2","structure|system|model","—","within framework"],
["hypothesis","n.","สมมุติฐาน","Test the hypothesis.","B2","theory|assumption|proposition","fact|proof","support hypothesis"],
["implication","n.","นัยสำคัญ","Policy implication.","B2","consequence|meaning|suggestion","—","major implication"],
["implicit","adj.","โดยนัย","Implicit assumption.","B2","implied|unstated|indirect","explicit|stated|direct","implicit message"],
["inference","n.","การอนุมาน","Logical inference.","B2","deduction|conclusion|reasoning","—","draw inference"],
["legitimate","adj.","ถูกต้องตามกฎหมาย","Legitimate concern.","B2","valid|lawful|genuine","illegitimate|invalid|illegal","legitimate claim"],
["methodology","n.","วิธีวิทยา","Research methodology.","B2","approach|method|technique","—","systematic methodology"],
["notion","n.","ความคิด","Common notion.","B2","idea|concept|belief","fact|reality","vague notion"],
["paradigm","n.","กระบวนทัศน์","Paradigm shift.","B2","model|framework|pattern","—","dominant paradigm"],
["parameter","n.","ตัวแปร","Set parameters.","B2","variable|limit|boundary","—","within parameters"],
["phenomenon","n.","ปรากฏการณ์","Social phenomenon.","B2","event|occurrence|development","—","natural phenomenon"],
["preliminary","adj.","เบื้องต้น","Preliminary results.","B2","initial|early|first","final|definitive","preliminary study"],
["profound","adj.","ลึกซึ้ง","Profound impact.","B2","deep|significant|major","shallow|minor|superficial","profound change"],
["rationale","n.","เหตุผล","Explain rationale.","B2","reason|logic|justification","—","underlying rationale"],
["refine","v.","ปรับให้ดีขึ้น","Refine technique.","B2","improve|enhance|perfect","worsen|damage","refine skills"],
["reinforce","v.","เสริมแรง","Reinforce learning.","B2","strengthen|support|confirm","weaken|undermine","reinforce behavior"],
["rigorous","adj.","เข้มงวด","Rigorous testing.","B2","strict|thorough|demanding","lax|easy|lenient","rigorous standard"],
["scrutiny","n.","การตรวจสอบอย่างละเอียด","Under scrutiny.","B2","examination|close look|investigation","cursory|glance","public scrutiny"],
["skeptical","adj.","ไม่เชื่อง่าย","Skeptical attitude.","B2","doubtful|questioning|critical","gullible|trusting","skeptical of"],
["specify","v.","ระบุ","Specify requirements.","B2","state|detail|define","generalize|vague","specify clearly"],
["substantial","adj.","จำนวนมาก","Substantial evidence.","B2","significant|considerable|large","minimal|minor|negligible","substantial amount"],
["sustain","v.","รักษา","Sustain development.","B2","maintain|support|continue","destroy|stop","sustain growth"],
["threshold","n.","ขีดจำกัด","Exceed threshold.","B2","limit|boundary|level","—","below threshold"],
["transparent","adj.","โปร่งใส","Transparent process.","B2","clear|open|honest","opaque|secretive|hidden","be transparent"],
["undermine","v.","บ่อนทำลาย","Undermine confidence.","B2","weaken|damage|sabotage","strengthen|support","undermine authority"],
["validate","v.","ตรวจสอบความถูกต้อง","Validate results.","B2","verify|confirm|prove","invalidate|disprove","validate data"],
["variable","n.","ตัวแปร","Control variables.","B2","factor|element|changing","constant|fixed","dependent variable"],
["widespread","adj.","แพร่หลาย","Widespread concern.","B2","common|extensive|prevalent","rare|uncommon|limited","become widespread"],
// C1
["alleviate","v.","บรรเทา","Alleviate suffering.","C1","reduce|ease|relieve","worsen|increase","alleviate pain"],
["ambivalent","adj.","ลังเล","Ambivalent feelings.","C1","uncertain|mixed|undecided","certain|decided","ambivalent about"],
["astute","adj.","เฉลียวฉลาด","Astute observation.","C1","clever|shrewd|perceptive","naive|gullible","astute observer"],
["atrophy","v/n.","ฝ่อ, เสื่อม","Muscles atrophy.","C1","decline|wither|deteriorate","grow|strengthen","mental atrophy"],
["bolster","v.","เสริม","Bolster confidence.","C1","strengthen|support|boost","weaken|undermine","bolster claim"],
["brevity","n.","ความกระชับ","Value of brevity.","C1","shortness|conciseness","length|verbosity","with brevity"],
["circumvent","v.","หลบเลี่ยง","Circumvent rules.","C1","bypass|evade|avoid","follow|obey","circumvent system"],
["cogent","adj.","น่าเชื่อถือ","Cogent argument.","C1","convincing|logical|sound","weak|illogical","cogent reason"],
["complacent","adj.","พอใจตัวเองมากเกินไป","Complacent attitude.","C1","self-satisfied|smug|overconfident","vigilant|alert|careful","become complacent"],
["concise","adj.","กระชับ","Concise answer.","C1","brief|short|succinct","lengthy|verbose","be concise"],
["contention","n.","ข้อโต้แย้ง","Point of contention.","C1","argument|dispute|claim","agreement|harmony","main contention"],
["contentious","adj.","ก่อให้เกิดการโต้เถียง","Contentious issue.","C1","controversial|disputed|debatable","uncontroversial|accepted","contentious debate"],
["convey","v.","สื่อ","Convey meaning.","C1","communicate|express|transmit","hide|conceal","convey message"],
["corroborate","v.","ยืนยัน","Corroborate claim.","C1","confirm|support|verify","contradict|disprove","corroborate evidence"],
["curtail","v.","ลดทอน","Curtail spending.","C1","limit|reduce|restrict","increase|expand","curtail rights"],
["cynical","adj.","มองโลกในแง่ร้าย","Cynical view.","C1","pessimistic|skeptical|distrustful","optimistic|trusting|idealistic","grow cynical"],
["decisive","adj.","เด็ดขาด","Decisive action.","C1","conclusive|clear-cut|resolute","indecisive|uncertain|wavering","decisive leader"],
["depict","v.","พรรณนา","Depict scene.","C1","describe|portray|represent","distort|misrepresent","depict as"],
["deplete","v.","ทำให้หมดลง","Deplete resources.","C1","exhaust|drain|use up","replenish|restore|refill","deplete supply"],
["detrimental","adj.","เป็นอันตราย","Detrimental effect.","C1","harmful|damaging|adverse","beneficial|helpful|positive","detrimental to health"],
["discern","v.","แยกแยะ","Discern truth.","C1","perceive|detect|distinguish","miss|overlook|confuse","discern pattern"],
["disparate","adj.","แตกต่างกันมาก","Disparate views.","C1","different|unequal|diverse","similar|equal|uniform","disparate groups"],
["dispel","v.","ขจัด","Dispel myth.","C1","remove|eliminate|clear","create|spread","dispel doubt"],
["dwindle","v.","ลดลงเรื่อยๆ","Funds dwindle.","C1","decrease|shrink|diminish","grow|increase|expand","dwindle away"],
["elicit","v.","ดึงออกมา","Elicit response.","C1","draw out|provoke|obtain","suppress|conceal","elicit reaction"],
["eloquent","adj.","มีวาทศิลป์","Eloquent speech.","C1","articulate|well-spoken|expressive","inarticulate|unclear","eloquent speaker"],
["emulate","v.","เลียนแบบ","Emulate success.","C1","imitate|copy|follow","differ|diverge","emulate role model"],
["ephemeral","adj.","ชั่วคราว","Ephemeral trend.","C1","temporary|fleeting|brief","permanent|lasting|enduring","ephemeral pleasure"],
["erroneous","adj.","ผิดพลาด","Erroneous conclusion.","C1","wrong|mistaken|incorrect","correct|right|accurate","erroneous assumption"],
["exacerbate","v.","ทำให้เลวร้ายลง","Exacerbate problem.","C1","worsen|aggravate|intensify","improve|alleviate|ease","exacerbate situation"],
["exemplify","v.","เป็นตัวอย่างของ","Exemplify principle.","C1","illustrate|represent|demonstrate","obscure|hide","exemplify well"],
["expedite","v.","เร่ง","Expedite process.","C1","speed up|accelerate|hasten","delay|slow down","expedite delivery"],
["fervent","adj.","กระตือรือร้นอย่างแรงกล้า","Fervent supporter.","C1","passionate|enthusiastic|intense","apathetic|indifferent","fervent believer"],
["futile","adj.","ไร้ประโยชน์","Futile attempt.","C1","useless|pointless|ineffective","useful|effective|worthwhile","prove futile"],
["hamper","v.","ขัดขวาง","Hamper progress.","C1","hinder|obstruct|impede","help|facilitate|enable","hamper growth"],
["imperative","adj/n.","จำเป็นเร่งด่วน","Imperative to act.","C1","essential|critical|vital","optional|unnecessary","moral imperative"],
["impede","v.","ขัดขวาง","Impede development.","C1","block|hinder|obstruct","help|facilitate|enable","impede progress"],
["inevitable","adj.","หลีกเลี่ยงไม่ได้","Inevitable outcome.","C1","unavoidable|certain|inescapable","avoidable|preventable","seem inevitable"],
["infer","v.","สรุปเอาเอง","Infer meaning.","C1","deduce|conclude|gather","state|declare","infer from"],
["inherent","adj.","โดยธรรมชาติ","Inherent risk.","C1","natural|built-in|intrinsic","external|acquired","inherent value"],
["insidious","adj.","ซึมลึก","Insidious disease.","C1","subtle|harmful|gradual","obvious|beneficial","insidious effect"],
["jeopardize","v.","ทำให้เสี่ยง","Jeopardize career.","C1","endanger|threaten|risk","protect|secure|safeguard","jeopardize safety"],
["lucid","adj.","ชัดเจน","Lucid explanation.","C1","clear|understandable|coherent","confusing|unclear","lucid writing"],
["meticulous","adj.","ละเอียดถี่ถ้วน","Meticulous research.","C1","careful|precise|detailed","careless|sloppy|hasty","meticulous attention"],
["mitigate","v.","บรรเทา","Mitigate risk.","C1","reduce|lessen|ease","increase|worsen","mitigate damage"],
["mundane","adj.","ธรรมดา","Mundane task.","C1","ordinary|dull|routine","exciting|extraordinary","mundane life"],
["nuanced","adj.","ละเอียดอ่อน","Nuanced view.","C1","subtle|complex|delicate","simplistic|black-and-white","nuanced argument"],
["obsolete","adj.","ล้าสมัย","Obsolete technology.","C1","outdated|old|antiquated","modern|current|up-to-date","become obsolete"],
["ominous","adj.","บอกเหตุร้าย","Ominous sign.","C1","threatening|sinister|foreboding","reassuring|encouraging|positive","ominous warning"],
["paradox","n.","ข้อขัดแย้ง","Strange paradox.","C1","contradiction|inconsistency|irony","consistency|logic","apparent paradox"],
["persevere","v.","อดทน","Persevere through difficulty.","C1","persist|endure|continue","give up|quit|surrender","persevere with"],
["pragmatic","adj.","ปฏิบัตินิยม","Pragmatic approach.","C1","practical|realistic|sensible","idealistic|impractical","pragmatic solution"],
["preclude","v.","ทำให้เป็นไปไม่ได้","Preclude possibility.","C1","prevent|exclude|rule out","allow|enable","preclude from"],
["premise","n.","สมมุติฐานเบื้องต้น","Flawed premise.","C1","assumption|basis|foundation","conclusion|result","on premise"],
["proponent","n.","ผู้สนับสนุน","Strong proponent.","C1","supporter|advocate|champion","opponent|critic","proponent of"],
["rectify","v.","แก้ไข","Rectify mistake.","C1","fix|correct|repair","worsen|damage","rectify situation"],
["refute","v.","หักล้าง","Refute claim.","C1","disprove|rebut|contradict","support|confirm","refute argument"],
["reiterate","v.","กล่าวซ้ำ","Reiterate point.","C1","repeat|restate|emphasize","state once|mention briefly","reiterate that"],
["resilient","adj.","ฟื้นตัวได้","Resilient mindset.","C1","strong|adaptable|tough","fragile|weak|vulnerable","resilient economy"],
["scrutinize","v.","ตรวจอย่างละเอียด","Scrutinize data.","C1","examine|inspect|analyze","glance|overlook","carefully scrutinize"],
["spurious","adj.","ปลอมหรือผิด","Spurious claim.","C1","false|fake|misleading","genuine|authentic|real","spurious argument"],
["stagnant","adj.","หยุดนิ่ง","Stagnant economy.","C1","static|not growing|dormant","growing|dynamic|active","stagnant growth"],
["stringent","adj.","เข้มงวด","Stringent rules.","C1","strict|rigorous|demanding","lenient|relaxed|loose","stringent requirement"],
["subvert","v.","บ่อนทำลาย","Subvert authority.","C1","undermine|weaken|sabotage","support|strengthen","subvert system"],
["superficial","adj.","ผิวเผิน","Superficial analysis.","C1","shallow|surface-level|cursory","deep|thorough|detailed","superficial understanding"],
["tacit","adj.","เข้าใจโดยไม่ต้องพูด","Tacit agreement.","C1","unspoken|implied|understood","explicit|stated|expressed","tacit consent"],
["tenacious","adj.","ยืนหยัด","Tenacious spirit.","C1","persistent|determined|stubborn","flexible|adaptable|yielding","tenacious effort"],
["transient","adj.","ชั่วคราว","Transient pleasure.","C1","temporary|fleeting|short-lived","permanent|lasting","transient nature"],
["ubiquitous","adj.","อยู่ทุกที่","Ubiquitous technology.","C1","everywhere|universal|pervasive","rare|scarce|absent","become ubiquitous"],
["unprecedented","adj.","ไม่เคยมีมาก่อน","Unprecedented growth.","C1","unparalleled|unheard of|extraordinary","ordinary|common","unprecedented event"],
["viable","adj.","เป็นไปได้","Viable solution.","C1","workable|feasible|practical","impossible|impractical","viable option"],
["volatile","adj.","ผันผวน","Volatile market.","C1","unstable|changeable|unpredictable","stable|steady|constant","volatile situation"],
["zealous","adj.","กระตือรือร้นสูง","Zealous supporter.","C1","passionate|enthusiastic|fervent","apathetic|indifferent","zealous advocate"],
];
