// Oxford 3000 — Thai meanings, CEFR A1–B2 (+ C1 bonus for exam prep)
// Format: [word, phonetic, pos, thai_meaning, example_sentence, cefr_level]
const VOCAB = [
// ══════════════════════════════════════════════════════════════════
// A1
// ══════════════════════════════════════════════════════════════════
["able","/ˈeɪ.bəl/","adj.","สามารถ","She is able to speak three languages.","A1"],
["about","/əˈbaʊt/","prep/adv.","เกี่ยวกับ, ประมาณ","Tell me about yourself.","A1"],
["above","/əˈbʌv/","prep.","เหนือ, ข้างบน","The plane flew above the clouds.","A1"],
["across","/əˈkrɒs/","prep.","ข้ามไป, ตลอด","She walked across the street.","A1"],
["act","/ækt/","v/n.","กระทำ, การกระทำ","Think before you act.","A1"],
["activity","/ækˈtɪv.ɪ.ti/","n.","กิจกรรม","What activities do you enjoy?","A1"],
["add","/æd/","v.","เพิ่ม, บวก","Add some salt to taste.","A1"],
["address","/ˈæd.res/","n.","ที่อยู่","Write your address here.","A1"],
["adult","/ˈæd.ʌlt/","n.","ผู้ใหญ่","Adults pay full price.","A1"],
["after","/ˈɑːf.tər/","prep.","หลังจาก","She rested after the exam.","A1"],
["again","/əˈɡen/","adv.","อีกครั้ง","Please say that again.","A1"],
["age","/eɪdʒ/","n.","อายุ, ยุค","What age are you?","A1"],
["agree","/əˈɡriː/","v.","เห็นด้วย","I agree with your point.","A1"],
["air","/eər/","n.","อากาศ","Fresh air is important.","A1"],
["all","/ɔːl/","det/adv.","ทั้งหมด","All students must attend.","A1"],
["allow","/əˈlaʊ/","v.","อนุญาต","Phones are not allowed here.","A1"],
["also","/ˈɔːl.səʊ/","adv.","ด้วย, เช่นกัน","She also speaks French.","A1"],
["always","/ˈɔːl.weɪz/","adv.","เสมอ","He is always on time.","A1"],
["angry","/ˈæŋ.ɡri/","adj.","โกรธ","She was angry at the news.","A1"],
["animal","/ˈæn.ɪ.məl/","n.","สัตว์","Dogs are friendly animals.","A1"],
["another","/əˈnʌð.ər/","det.","อีก, อื่น","Can I have another cup?","A1"],
["answer","/ˈɑːnt.sər/","n/v.","คำตอบ, ตอบ","What is your answer?","A1"],
["any","/ˈen.i/","det/pron.","ใดก็ได้, บ้าง","Do you have any questions?","A1"],
["area","/ˈeər.i.ə/","n.","พื้นที่, บริเวณ","This is a residential area.","A1"],
["arm","/ɑːm/","n.","แขน","She broke her arm.","A1"],
["around","/əˈraʊnd/","prep/adv.","รอบๆ, ประมาณ","Walk around the park.","A1"],
["arrive","/əˈraɪv/","v.","มาถึง","What time will you arrive?","A1"],
["ask","/ɑːsk/","v.","ถาม, ขอ","Don't be afraid to ask.","A1"],
["away","/əˈweɪ/","adv.","ออกไป, ห่างออกไป","She moved away last year.","A1"],
["back","/bæk/","adv/n.","กลับ, หลัง","He came back yesterday.","A1"],
["bad","/bæd/","adj.","แย่, ไม่ดี","That was a bad idea.","A1"],
["bag","/bæɡ/","n.","กระเป๋า","Put it in your bag.","A1"],
["be","/biː/","v.","เป็น, อยู่","I want to be a doctor.","A1"],
["beautiful","/ˈbjuː.tɪ.fəl/","adj.","สวยงาม","What a beautiful view!","A1"],
["because","/bɪˈkɒz/","conj.","เพราะว่า","I stayed home because it rained.","A1"],
["become","/bɪˈkʌm/","v.","กลายเป็น","She became a doctor.","A1"],
["before","/bɪˈfɔːr/","prep/conj.","ก่อน","Think before you speak.","A1"],
["begin","/bɪˈɡɪn/","v.","เริ่มต้น","Let's begin the class.","A1"],
["behind","/bɪˈhaɪnd/","prep.","ข้างหลัง","She stood behind me.","A1"],
["believe","/bɪˈliːv/","v.","เชื่อ","I believe you.","A1"],
["best","/best/","adj/adv.","ดีที่สุด","She gave her best.","A1"],
["between","/bɪˈtwiːn/","prep.","ระหว่าง","Choose between these two.","A1"],
["big","/bɪɡ/","adj.","ใหญ่","They live in a big house.","A1"],
["bike","/baɪk/","n.","จักรยาน","She rides her bike to school.","A1"],
["body","/ˈbɒd.i/","n.","ร่างกาย","Exercise is good for the body.","A1"],
["book","/bʊk/","n/v.","หนังสือ, จอง","I love reading books.","A1"],
["both","/bəʊθ/","det/pron.","ทั้งสอง","Both options are good.","A1"],
["break","/breɪk/","v/n.","หยุดพัก, แตก","Take a break.","A1"],
["bring","/brɪŋ/","v.","นำมา","Please bring a pen.","A1"],
["brother","/ˈbrʌð.ər/","n.","พี่ชาย/น้องชาย","My brother is tall.","A1"],
["build","/bɪld/","v.","สร้าง","They built a new school.","A1"],
["busy","/ˈbɪz.i/","adj.","ยุ่ง","I'm very busy today.","A1"],
["buy","/baɪ/","v.","ซื้อ","She wants to buy a car.","A1"],
["call","/kɔːl/","v/n.","โทร, เรียก","Call me tonight.","A1"],
["can","/kæn/","modal v.","สามารถ","Can you help me?","A1"],
["car","/kɑːr/","n.","รถยนต์","He drives a red car.","A1"],
["carry","/ˈkær.i/","v.","แบก, ถือ","Can you carry this bag?","A1"],
["catch","/kætʃ/","v.","จับ, ทัน","I can't catch the bus.","A1"],
["cause","/kɔːz/","n/v.","สาเหตุ, ก่อให้เกิด","Stress can cause illness.","A1"],
["certain","/ˈsɜː.tən/","adj.","แน่ใจ, บางอย่าง","Are you certain about this?","A1"],
["change","/tʃeɪndʒ/","v/n.","เปลี่ยนแปลง","Change is inevitable.","A1"],
["check","/tʃek/","v/n.","ตรวจสอบ","Check your answers.","A1"],
["child","/tʃaɪld/","n.","เด็ก","Every child deserves education.","A1"],
["choose","/tʃuːz/","v.","เลือก","Choose wisely.","A1"],
["city","/ˈsɪt.i/","n.","เมือง","Bangkok is a big city.","A1"],
["class","/klɑːs/","n.","ชั้นเรียน, ระดับ","Class starts at 8 a.m.","A1"],
["clean","/kliːn/","adj/v.","สะอาด, ทำความสะอาด","Keep your desk clean.","A1"],
["clear","/klɪər/","adj.","ชัดเจน","The instructions are clear.","A1"],
["close","/kləʊz/","v/adj.","ปิด, ใกล้","Close the door, please.","A1"],
["cold","/kəʊld/","adj/n.","หนาว, ความเย็น","It's very cold today.","A1"],
["colour","/ˈkʌl.ər/","n.","สี","What colour do you prefer?","A1"],
["come","/kʌm/","v.","มา","Please come here.","A1"],
["common","/ˈkɒm.ən/","adj.","ธรรมดา, ทั่วไป","Colds are common in winter.","A1"],
["computer","/kəmˈpjuː.tər/","n.","คอมพิวเตอร์","I work on a computer.","A1"],
["continue","/kənˈtɪn.juː/","v.","ดำเนินต่อไป","Continue reading quietly.","A1"],
["cook","/kʊk/","v/n.","ทำอาหาร, พ่อครัว","She loves to cook.","A1"],
["cost","/kɒst/","n/v.","ค่าใช้จ่าย","How much does it cost?","A1"],
["country","/ˈkʌn.tri/","n.","ประเทศ, ชนบท","Which country are you from?","A1"],
["create","/kriˈeɪt/","v.","สร้างสรรค์","Create something new.","A1"],
["cut","/kʌt/","v/n.","ตัด","Cut the paper in half.","A1"],
["dance","/dɑːns/","v/n.","เต้นรำ","She loves to dance.","A1"],
["dark","/dɑːk/","adj/n.","มืด, ความมืด","It's dark outside.","A1"],
["day","/deɪ/","n.","วัน","Have a nice day.","A1"],
["dead","/ded/","adj.","ตาย","The plant looks dead.","A1"],
["decide","/dɪˈsaɪd/","v.","ตัดสินใจ","It's hard to decide.","A1"],
["deep","/diːp/","adj.","ลึก","The lake is very deep.","A1"],
["different","/ˈdɪf.ər.ənt/","adj.","แตกต่าง","We have different opinions.","A1"],
["difficult","/ˈdɪf.ɪ.kəlt/","adj.","ยาก","This question is difficult.","A1"],
["door","/dɔːr/","n.","ประตู","Close the door.","A1"],
["down","/daʊn/","adv/prep.","ลง","Walk down the stairs.","A1"],
["draw","/drɔː/","v.","วาด","She can draw beautifully.","A1"],
["drink","/drɪŋk/","v/n.","ดื่ม, เครื่องดื่ม","Drink more water.","A1"],
["drive","/draɪv/","v/n.","ขับรถ","He drives to work.","A1"],
["drop","/drɒp/","v/n.","ทำตก, หยด","Don't drop that vase.","A1"],
["during","/ˈdjʊər.ɪŋ/","prep.","ระหว่าง (ช่วงเวลา)","Stay quiet during the exam.","A1"],
["each","/iːtʃ/","det/pron.","แต่ละ","Each student has a book.","A1"],
["early","/ˈɜː.li/","adj/adv.","แต่เช้า, เร็ว","Come early tomorrow.","A1"],
["easy","/ˈiː.zi/","adj.","ง่าย","The test was easy.","A1"],
["eat","/iːt/","v.","กิน","Eat your vegetables.","A1"],
["end","/end/","n/v.","จุดสิ้นสุด, สิ้นสุด","The end of the book is sad.","A1"],
["enjoy","/ɪnˈdʒɔɪ/","v.","สนุก, เพลิดเพลิน","I enjoy swimming.","A1"],
["enough","/ɪˈnʌf/","det/adv.","เพียงพอ","Is there enough food?","A1"],
["enter","/ˈen.tər/","v.","เข้าไป","Enter the room quietly.","A1"],
["every","/ˈev.ri/","det.","ทุก","Study every day.","A1"],
["exact","/ɪɡˈzækt/","adj.","แน่นอน, ตรง","What is the exact time?","A1"],
["example","/ɪɡˈzɑːm.pəl/","n.","ตัวอย่าง","Can you give an example?","A1"],
["eye","/aɪ/","n.","ตา","She has beautiful eyes.","A1"],
["face","/feɪs/","n/v.","ใบหน้า, เผชิญ","Face your fears.","A1"],
["fact","/fækt/","n.","ข้อเท็จจริง","That is a fact.","A1"],
["fall","/fɔːl/","v/n.","ตก, ล้ม","Don't fall asleep.","A1"],
["family","/ˈfæm.ɪ.li/","n.","ครอบครัว","Family is everything.","A1"],
["far","/fɑːr/","adj/adv.","ไกล","How far is it?","A1"],
["fast","/fɑːst/","adj/adv.","เร็ว","She runs fast.","A1"],
["feel","/fiːl/","v.","รู้สึก","How do you feel?","A1"],
["few","/fjuː/","det/pron.","น้อย, บางส่วน","Only a few students came.","A1"],
["find","/faɪnd/","v.","หา, พบ","I can't find my keys.","A1"],
["first","/fɜːst/","adj/adv.","แรก, ก่อน","She finished first.","A1"],
["follow","/ˈfɒl.əʊ/","v.","ติดตาม, ทำตาม","Follow the instructions.","A1"],
["food","/fuːd/","n.","อาหาร","Thai food is delicious.","A1"],
["free","/friː/","adj.","ฟรี, อิสระ","Admission is free.","A1"],
["friend","/frend/","n.","เพื่อน","She is my best friend.","A1"],
["from","/frɒm/","prep.","จาก","She is from Thailand.","A1"],
["front","/frʌnt/","n/adj.","ด้านหน้า","Sit at the front.","A1"],
["full","/fʊl/","adj.","เต็ม","The glass is full.","A1"],
["game","/ɡeɪm/","n.","เกม, การแข่งขัน","Let's play a game.","A1"],
["get","/ɡet/","v.","ได้รับ, เอา","Get some rest.","A1"],
["give","/ɡɪv/","v.","ให้","Give me your hand.","A1"],
["go","/ɡəʊ/","v.","ไป","Let's go to school.","A1"],
["good","/ɡʊd/","adj.","ดี","Good job!","A1"],
["great","/ɡreɪt/","adj.","ยอดเยี่ยม, ยิ่งใหญ่","That's a great idea.","A1"],
["grow","/ɡrəʊ/","v.","เติบโต, ปลูก","Plants need water to grow.","A1"],
["hand","/hænd/","n.","มือ","She raised her hand.","A1"],
["happy","/ˈhæp.i/","adj.","มีความสุข","I'm very happy today.","A1"],
["hard","/hɑːd/","adj/adv.","ยาก, หนัก","He works hard.","A1"],
["have","/hæv/","v.","มี","I have a question.","A1"],
["head","/hed/","n.","หัว, หัวหน้า","He's the head of the team.","A1"],
["heart","/hɑːt/","n.","หัวใจ","Exercise is good for the heart.","A1"],
["help","/help/","v/n.","ช่วย","Can you help me?","A1"],
["here","/hɪər/","adv.","ที่นี่","Come here.","A1"],
["high","/haɪ/","adj/adv.","สูง","She got a high score.","A1"],
["home","/həʊm/","n.","บ้าน","She goes home at 5.","A1"],
["hour","/aʊər/","n.","ชั่วโมง","Wait an hour.","A1"],
["house","/haʊs/","n.","บ้าน, ที่พัก","They bought a new house.","A1"],
["idea","/aɪˈdɪər/","n.","ความคิด, ไอเดีย","That's a good idea.","A1"],
["important","/ɪmˈpɔː.tənt/","adj.","สำคัญ","Sleep is important.","A1"],
["inside","/ˌɪnˈsaɪd/","prep/adv.","ข้างใน","Come inside.","A1"],
["into","/ˈɪn.tuː/","prep.","เข้าไปใน","Put it into the box.","A1"],
["job","/dʒɒb/","n.","งาน","She has a new job.","A1"],
["just","/dʒʌst/","adv.","เพิ่งจะ, แค่","I just arrived.","A1"],
["keep","/kiːp/","v.","เก็บ, รักษาไว้","Keep this a secret.","A1"],
["kind","/kaɪnd/","adj/n.","ใจดี, ชนิด","She is very kind.","A1"],
["know","/nəʊ/","v.","รู้, รู้จัก","Do you know the answer?","A1"],
["large","/lɑːdʒ/","adj.","ใหญ่","A large number of students passed.","A1"],
["last","/lɑːst/","adj/v.","สุดท้าย, คงอยู่","She came last.","A1"],
["late","/leɪt/","adj/adv.","สาย","Don't be late.","A1"],
["laugh","/lɑːf/","v.","หัวเราะ","She laughed loudly.","A1"],
["learn","/lɜːn/","v.","เรียน, เรียนรู้","Learn from your mistakes.","A1"],
["leave","/liːv/","v.","ออกไป, ทิ้งไว้","Leave your bag here.","A1"],
["left","/left/","adj/n.","ซ้าย","Turn left at the corner.","A1"],
["let","/let/","v.","ยอมให้, ปล่อย","Let me help you.","A1"],
["life","/laɪf/","n.","ชีวิต","Life is full of surprises.","A1"],
["like","/laɪk/","v/prep.","ชอบ, เหมือน","I like coffee.","A1"],
["listen","/ˈlɪs.ən/","v.","ฟัง","Listen carefully.","A1"],
["little","/ˈlɪt.əl/","adj/adv.","เล็กน้อย, นิดหน่อย","A little help goes far.","A1"],
["live","/lɪv/","v.","อาศัยอยู่","She lives in Chiang Mai.","A1"],
["long","/lɒŋ/","adj/adv.","ยาว, นาน","This road is long.","A1"],
["look","/lʊk/","v.","มอง, ดู","Look at the board.","A1"],
["lose","/luːz/","v.","แพ้, สูญเสีย","Don't lose hope.","A1"],
["love","/lʌv/","v/n.","รัก","I love my family.","A1"],
["low","/ləʊ/","adj/adv.","ต่ำ","Prices are low now.","A1"],
["make","/meɪk/","v.","ทำ, สร้าง","Make a wish.","A1"],
["many","/ˈmen.i/","det/pron.","มาก (นับได้)","Many students pass each year.","A1"],
["mean","/miːn/","v/adj.","หมายความว่า, ขี้เหนียว","What does this word mean?","A1"],
["meet","/miːt/","v.","พบ","Nice to meet you.","A1"],
["mind","/maɪnd/","n/v.","จิตใจ, สนใจ","Mind your own business.","A1"],
["miss","/mɪs/","v.","คิดถึง, พลาด","I miss home.","A1"],
["money","/ˈmʌn.i/","n.","เงิน","She saved money.","A1"],
["more","/mɔːr/","det/adv.","มากกว่า","I need more time.","A1"],
["most","/məʊst/","det/adv.","มากที่สุด","Most students agree.","A1"],
["move","/muːv/","v.","เคลื่อนที่, ย้าย","Let's move on.","A1"],
["much","/mʌtʃ/","det/adv.","มาก (นับไม่ได้)","How much does it cost?","A1"],
["music","/ˈmjuː.zɪk/","n.","ดนตรี","She loves music.","A1"],
["name","/neɪm/","n/v.","ชื่อ, ตั้งชื่อ","What is your name?","A1"],
["near","/nɪər/","prep/adj.","ใกล้","She lives near school.","A1"],
["need","/niːd/","v/n.","ต้องการ","I need help.","A1"],
["never","/ˈnev.ər/","adv.","ไม่เคย","I never lie.","A1"],
["new","/njuː/","adj.","ใหม่","She got a new phone.","A1"],
["next","/nekst/","adj/adv.","ถัดไป, ข้างๆ","Who is next?","A1"],
["night","/naɪt/","n.","กลางคืน","Good night!","A1"],
["now","/naʊ/","adv.","ตอนนี้","I'm busy now.","A1"],
["number","/ˈnʌm.bər/","n.","หมายเลข, จำนวน","Write your phone number.","A1"],
["often","/ˈɒf.ən/","adv.","บ่อย","She often reads at night.","A1"],
["old","/əʊld/","adj.","แก่, เก่า","She is ten years old.","A1"],
["only","/ˈəʊn.li/","adj/adv.","เดียว, แค่","She is the only child.","A1"],
["open","/ˈəʊ.pən/","v/adj.","เปิด","Open your book.","A1"],
["other","/ˈʌð.ər/","det/pron.","อื่น, อีก","Do you have other options?","A1"],
["outside","/ˌaʊtˈsaɪd/","prep/adv.","ข้างนอก","Wait outside.","A1"],
["own","/əʊn/","adj/v.","ของตัวเอง, เป็นเจ้าของ","She owns a shop.","A1"],
["part","/pɑːt/","n/v.","ส่วน, แยกจาก","This is part of the plan.","A1"],
["people","/ˈpiː.pəl/","n.","ผู้คน","Many people came.","A1"],
["person","/ˈpɜː.sən/","n.","บุคคล","She is a kind person.","A1"],
["phone","/fəʊn/","n.","โทรศัพท์","My phone is dead.","A1"],
["place","/pleɪs/","n/v.","สถานที่, วาง","This is a beautiful place.","A1"],
["plan","/plæn/","n/v.","แผน, วางแผน","What's the plan?","A1"],
["play","/pleɪ/","v/n.","เล่น, ละคร","Children love to play.","A1"],
["please","/pliːz/","adv/v.","กรุณา, ทำให้พอใจ","Please sit down.","A1"],
["point","/pɔɪnt/","n/v.","จุด, ชี้","What is your point?","A1"],
["problem","/ˈprɒb.ləm/","n.","ปัญหา","We have a problem.","A1"],
["put","/pʊt/","v.","วาง, ใส่","Put it on the table.","A1"],
["question","/ˈkwes.tʃən/","n/v.","คำถาม, ตั้งคำถาม","Any questions?","A1"],
["quick","/kwɪk/","adj/adv.","เร็ว","Take a quick look.","A1"],
["read","/riːd/","v.","อ่าน","Read the instructions.","A1"],
["real","/rɪəl/","adj.","จริง, แท้จริง","Is this real?","A1"],
["remember","/rɪˈmem.bər/","v.","จำได้","Remember to study.","A1"],
["right","/raɪt/","adj/adv.","ถูกต้อง, ขวา","Turn right here.","A1"],
["room","/ruːm/","n.","ห้อง, ที่ว่าง","Your room is clean.","A1"],
["run","/rʌn/","v.","วิ่ง, ดำเนินการ","She runs every morning.","A1"],
["safe","/seɪf/","adj.","ปลอดภัย","Keep your password safe.","A1"],
["same","/seɪm/","adj.","เหมือนกัน","We have the same opinion.","A1"],
["say","/seɪ/","v.","พูด, บอก","What did she say?","A1"],
["school","/skuːl/","n.","โรงเรียน","She goes to school.","A1"],
["see","/siː/","v.","เห็น","Can you see the board?","A1"],
["send","/send/","v.","ส่ง","Send me a message.","A1"],
["short","/ʃɔːt/","adj.","สั้น, เตี้ย","Her hair is short.","A1"],
["show","/ʃəʊ/","v/n.","แสดง, รายการ","Show me your work.","A1"],
["since","/sɪns/","prep/conj.","ตั้งแต่, เนื่องจาก","She has studied since morning.","A1"],
["sister","/ˈsɪs.tər/","n.","พี่สาว/น้องสาว","My sister is smart.","A1"],
["sit","/sɪt/","v.","นั่ง","Please sit down.","A1"],
["sleep","/sliːp/","v/n.","นอนหลับ","Get enough sleep.","A1"],
["slow","/sləʊ/","adj/adv.","ช้า","She is slow to decide.","A1"],
["small","/smɔːl/","adj.","เล็ก","It's a small mistake.","A1"],
["smile","/smaɪl/","v/n.","ยิ้ม","She always smiles.","A1"],
["so","/səʊ/","adv/conj.","มาก, ดังนั้น","I was so tired.","A1"],
["some","/sʌm/","det/pron.","บางส่วน, บ้าง","Some students stayed.","A1"],
["soon","/suːn/","adv.","เร็วๆ นี้","See you soon.","A1"],
["sorry","/ˈsɒr.i/","adj.","ขอโทษ","I'm so sorry.","A1"],
["speak","/spiːk/","v.","พูด","Speak slowly, please.","A1"],
["stand","/stænd/","v.","ยืน, ทน","Stand up straight.","A1"],
["start","/stɑːt/","v/n.","เริ่ม","Start from the beginning.","A1"],
["stay","/steɪ/","v.","อยู่, พัก","Stay calm.","A1"],
["still","/stɪl/","adv.","ยังคง","She still studies hard.","A1"],
["stop","/stɒp/","v.","หยุด","Stop talking.","A1"],
["story","/ˈstɔː.ri/","n.","เรื่องราว","Tell me a story.","A1"],
["strong","/strɒŋ/","adj.","แข็งแกร่ง","She is mentally strong.","A1"],
["study","/ˈstʌd.i/","v/n.","เรียน, ศึกษา","Study harder.","A1"],
["such","/sʌtʃ/","det.","ดังกล่าว, เช่นนั้น","No such problem exists.","A1"],
["sure","/ʃʊər/","adj/adv.","แน่ใจ","Are you sure?","A1"],
["swim","/swɪm/","v.","ว่ายน้ำ","She swims every day.","A1"],
["take","/teɪk/","v.","รับ, พา","Take your time.","A1"],
["talk","/tɔːk/","v/n.","คุย, พูด","Let's talk.","A1"],
["tell","/tel/","v.","บอก, เล่า","Tell me the truth.","A1"],
["than","/ðæn/","conj.","กว่า","She is taller than me.","A1"],
["think","/θɪŋk/","v.","คิด","Think before you act.","A1"],
["time","/taɪm/","n.","เวลา","Time is precious.","A1"],
["together","/təˈɡeð.ər/","adv.","ด้วยกัน","Work together.","A1"],
["too","/tuː/","adv.","เกินไป, ด้วย","Me too.","A1"],
["town","/taʊn/","n.","เมืองเล็ก","She lives in a small town.","A1"],
["try","/traɪ/","v.","พยายาม","Try your best.","A1"],
["turn","/tɜːn/","v/n.","หมุน, หัน","Turn off the light.","A1"],
["under","/ˈʌn.dər/","prep.","ใต้","The cat is under the table.","A1"],
["understand","/ˌʌn.dəˈstænd/","v.","เข้าใจ","Do you understand?","A1"],
["until","/ənˈtɪl/","prep/conj.","จนกระทั่ง","Wait until tomorrow.","A1"],
["up","/ʌp/","adv/prep.","ขึ้น","Look up at the sky.","A1"],
["use","/juːz/","v/n.","ใช้","Use a dictionary.","A1"],
["very","/ˈver.i/","adv.","มาก, มาก","She is very smart.","A1"],
["visit","/ˈvɪz.ɪt/","v/n.","เยี่ยมชม","Visit the museum.","A1"],
["wait","/weɪt/","v.","รอ","Wait a moment.","A1"],
["walk","/wɔːk/","v/n.","เดิน","Walk to school.","A1"],
["want","/wɒnt/","v.","ต้องการ","I want to learn English.","A1"],
["watch","/wɒtʃ/","v/n.","ดู, นาฬิกา","Watch the news.","A1"],
["way","/weɪ/","n.","ทาง, วิธี","Find a better way.","A1"],
["well","/wel/","adv/adj.","ดี, สุขภาพดี","She sings well.","A1"],
["which","/wɪtʃ/","pron/det.","อันไหน, ซึ่ง","Which do you prefer?","A1"],
["while","/waɪl/","conj.","ในขณะที่","Study while you can.","A1"],
["white","/waɪt/","adj.","สีขาว","She wears white.","A1"],
["why","/waɪ/","adv.","ทำไม","Why are you late?","A1"],
["win","/wɪn/","v.","ชนะ","She wants to win.","A1"],
["without","/wɪˈðaʊt/","prep.","โดยไม่มี","She left without a word.","A1"],
["word","/wɜːd/","n.","คำ","Learn new words daily.","A1"],
["work","/wɜːk/","v/n.","ทำงาน","Hard work pays off.","A1"],
["world","/wɜːld/","n.","โลก","She wants to see the world.","A1"],
["write","/raɪt/","v.","เขียน","Write your answer.","A1"],
["year","/jɪər/","n.","ปี","She studies two years.","A1"],
["young","/jʌŋ/","adj.","อายุน้อย","Stay young at heart.","A1"],
// ══════════════════════════════════════════════════════════════════
// A2
// ══════════════════════════════════════════════════════════════════
["able","/ˈeɪ.bəl/","adj.","สามารถ","She is able to run fast.","A2"],
["accept","/əkˈsept/","v.","ยอมรับ","She accepted the offer.","A2"],
["access","/ˈæk.ses/","n/v.","การเข้าถึง","Internet access is essential.","A2"],
["according to","/əˈkɔː.dɪŋ tuː/","prep.","ตาม (ที่กล่าวอ้าง)","According to the news, prices rose.","A2"],
["achieve","/əˈtʃiːv/","v.","บรรลุ","She achieved her goals.","A2"],
["affect","/əˈfekt/","v.","ส่งผลกระทบ","Stress affects health.","A2"],
["afford","/əˈfɔːd/","v.","มีเงินพอ","I can't afford a new phone.","A2"],
["against","/əˈɡenst/","prep.","ต่อต้าน, ชนกับ","She argued against the plan.","A2"],
["agree","/əˈɡriː/","v.","เห็นด้วย","Do you agree?","A2"],
["although","/ɔːlˈðəʊ/","conj.","แม้ว่า","Although tired, she studied.","A2"],
["among","/əˈmʌŋ/","prep.","ท่ามกลาง","She was among the best.","A2"],
["amount","/əˈmaʊnt/","n/v.","จำนวน, รวมเป็น","A large amount of data.","A2"],
["angry","/ˈæŋ.ɡri/","adj.","โกรธ","She was angry at him.","A2"],
["appear","/əˈpɪər/","v.","ปรากฏ, ดูเหมือน","He appears nervous.","A2"],
["apply","/əˈplaɪ/","v.","สมัคร, ใช้กับ","Apply the rules fairly.","A2"],
["attention","/əˈten.ʃən/","n.","ความสนใจ","Pay attention in class.","A2"],
["attitude","/ˈæt.ɪ.tjuːd/","n.","ทัศนคติ","A positive attitude helps.","A2"],
["avoid","/əˈvɔɪd/","v.","หลีกเลี่ยง","Avoid junk food.","A2"],
["base","/beɪs/","n/v.","ฐาน, อ้างอิง","Base your argument on facts.","A2"],
["behave","/bɪˈheɪv/","v.","ประพฤติ","Behave yourself.","A2"],
["below","/bɪˈləʊ/","prep/adv.","ต่ำกว่า, ด้านล่าง","See the note below.","A2"],
["benefit","/ˈben.ɪ.fɪt/","n/v.","ประโยชน์","Exercise benefits everyone.","A2"],
["beside","/bɪˈsaɪd/","prep.","ข้างๆ","Sit beside me.","A2"],
["borrow","/ˈbɒr.əʊ/","v.","ยืม","Can I borrow a pen?","A2"],
["business","/ˈbɪz.nɪs/","n.","ธุรกิจ","She runs a small business.","A2"],
["careful","/ˈkeər.fəl/","adj.","ระมัดระวัง","Be careful crossing the road.","A2"],
["chance","/tʃɑːns/","n.","โอกาส","Take every chance.","A2"],
["choice","/tʃɔɪs/","n.","ทางเลือก","It's your choice.","A2"],
["clearly","/ˈklɪə.li/","adv.","อย่างชัดเจน","Explain it clearly.","A2"],
["collect","/kəˈlekt/","v.","เก็บ, รวบรวม","Collect data carefully.","A2"],
["compare","/kəmˈpeər/","v.","เปรียบเทียบ","Compare the two options.","A2"],
["complete","/kəmˈpliːt/","adj/v.","สมบูรณ์, ทำเสร็จ","Complete the form.","A2"],
["confident","/ˈkɒn.fɪ.dənt/","adj.","มั่นใจ","She is confident.","A2"],
["connect","/kəˈnekt/","v.","เชื่อมต่อ","Connect the dots.","A2"],
["consider","/kənˈsɪd.ər/","v.","พิจารณา","Consider all options.","A2"],
["control","/kənˈtrəʊl/","v/n.","ควบคุม","Control your emotions.","A2"],
["correct","/kəˈrekt/","adj/v.","ถูกต้อง","Is this correct?","A2"],
["culture","/ˈkʌl.tʃər/","n.","วัฒนธรรม","Thai culture is rich.","A2"],
["decision","/dɪˈsɪʒ.ən/","n.","การตัดสินใจ","Make a good decision.","A2"],
["describe","/dɪˈskraɪb/","v.","อธิบาย","Describe what you see.","A2"],
["develop","/dɪˈvel.əp/","v.","พัฒนา","Develop new skills.","A2"],
["discuss","/dɪˈskʌs/","v.","อภิปราย","Discuss the topic.","A2"],
["drive","/draɪv/","v.","ขับรถ, กระตุ้น","What drives you?","A2"],
["earn","/ɜːn/","v.","หาเงิน, ได้รับ","You must earn respect.","A2"],
["either","/ˈaɪ.ðər/","det/conj.","ก็ได้ทั้งคู่, อีกอันหนึ่ง","Either option works.","A2"],
["energy","/ˈen.ə.dʒi/","n.","พลังงาน","She has lots of energy.","A2"],
["especially","/ɪˈspeʃ.ə.li/","adv.","โดยเฉพาะ","She loves fruit, especially mangoes.","A2"],
["event","/ɪˈvent/","n.","เหตุการณ์","A big event is coming.","A2"],
["expect","/ɪkˈspekt/","v.","คาดหวัง","I expect good results.","A2"],
["explain","/ɪkˈspleɪn/","v.","อธิบาย","Explain your answer.","A2"],
["fail","/feɪl/","v.","ล้มเหลว","Don't be afraid to fail.","A2"],
["feed","/fiːd/","v.","ให้อาหาร, ป้อน","Feed the data in.","A2"],
["finally","/ˈfaɪ.nəl.i/","adv.","ในที่สุด","She finally passed.","A2"],
["foreign","/ˈfɒr.ɪn/","adj.","ต่างชาติ, ต่างประเทศ","She studies a foreign language.","A2"],
["form","/fɔːm/","n/v.","แบบฟอร์ม, ก่อร่าง","Fill in the form.","A2"],
["forward","/ˈfɔː.wəd/","adv/adj.","ไปข้างหน้า","Move forward.","A2"],
["general","/ˈdʒen.ər.əl/","adj.","ทั่วไป","In general, it's good.","A2"],
["goal","/ɡəʊl/","n.","เป้าหมาย","Set clear goals.","A2"],
["government","/ˈɡʌv.ən.mənt/","n.","รัฐบาล","The government set rules.","A2"],
["group","/ɡruːp/","n/v.","กลุ่ม","Work in a group.","A2"],
["guess","/ɡes/","v/n.","เดา","Take a guess.","A2"],
["handle","/ˈhæn.dəl/","v.","จัดการ","Handle the situation.","A2"],
["happen","/ˈhæp.ən/","v.","เกิดขึ้น","What happened?","A2"],
["health","/helθ/","n.","สุขภาพ","Good health is important.","A2"],
["hope","/həʊp/","v/n.","หวัง","I hope you succeed.","A2"],
["however","/haʊˈev.ər/","adv/conj.","อย่างไรก็ตาม","However, it's still possible.","A2"],
["human","/ˈhjuː.mən/","adj/n.","มนุษย์","Human rights matter.","A2"],
["improve","/ɪmˈpruːv/","v.","ปรับปรุง","Improve your writing.","A2"],
["increase","/ɪnˈkriːs/","v/n.","เพิ่มขึ้น","Prices increased.","A2"],
["individual","/ˌɪn.dɪˈvɪdʒ.u.əl/","adj/n.","บุคคล, ส่วนตัว","Each individual is unique.","A2"],
["instead","/ɪnˈsted/","adv.","แทนที่","Try this instead.","A2"],
["interest","/ˈɪn.trɪst/","n/v.","ความสนใจ","She has an interest in art.","A2"],
["issue","/ˈɪʃ.uː/","n.","ประเด็น, ปัญหา","Raise the issue.","A2"],
["join","/dʒɔɪn/","v.","เข้าร่วม","Join the club.","A2"],
["lack","/læk/","v/n.","ขาด","She lacks confidence.","A2"],
["language","/ˈlæŋ.ɡwɪdʒ/","n.","ภาษา","English is a global language.","A2"],
["lead","/liːd/","v/n.","นำ, ผู้นำ","She leads the team.","A2"],
["level","/ˈlev.əl/","n.","ระดับ","Raise the level.","A2"],
["limit","/ˈlɪm.ɪt/","n/v.","ขีดจำกัด, จำกัด","Set limits.","A2"],
["local","/ˈləʊ.kəl/","adj.","ท้องถิ่น","Support local shops.","A2"],
["manage","/ˈmæn.ɪdʒ/","v.","จัดการ","She manages the team.","A2"],
["maybe","/ˈmeɪ.bi/","adv.","บางที","Maybe she's right.","A2"],
["mention","/ˈmen.ʃən/","v/n.","พูดถึง","He didn't mention it.","A2"],
["method","/ˈmeθ.əd/","n.","วิธีการ","Use the right method.","A2"],
["nature","/ˈneɪ.tʃər/","n.","ธรรมชาติ","She loves nature.","A2"],
["notice","/ˈnəʊ.tɪs/","v/n.","สังเกต, ประกาศ","Did you notice the change?","A2"],
["offer","/ˈɒf.ər/","v/n.","เสนอ","She offered to help.","A2"],
["opinion","/əˈpɪn.i.ən/","n.","ความคิดเห็น","Share your opinion.","A2"],
["otherwise","/ˈʌð.ə.waɪz/","adv.","มิฉะนั้น","Study hard, otherwise you'll fail.","A2"],
["parent","/ˈpeər.ənt/","n.","พ่อแม่","Her parents are teachers.","A2"],
["partner","/ˈpɑːt.nər/","n.","คู่หู, หุ้นส่วน","Work with a partner.","A2"],
["period","/ˈpɪər.i.əd/","n.","ช่วงเวลา","For a short period.","A2"],
["personal","/ˈpɜː.sən.əl/","adj.","ส่วนตัว","This is personal.","A2"],
["popular","/ˈpɒp.jʊ.lər/","adj.","เป็นที่นิยม","This song is popular.","A2"],
["position","/pəˈzɪʃ.ən/","n.","ตำแหน่ง, ท่าทาง","Apply for the position.","A2"],
["possible","/ˈpɒs.ɪ.bəl/","adj.","เป็นไปได้","Is it possible?","A2"],
["prepare","/prɪˈpeər/","v.","เตรียม","Prepare for the test.","A2"],
["produce","/prəˈdjuːs/","v.","ผลิต","The farm produces rice.","A2"],
["program","/ˈprəʊ.ɡræm/","n.","โปรแกรม, หลักสูตร","She joined the program.","A2"],
["protect","/prəˈtekt/","v.","ปกป้อง","Protect the environment.","A2"],
["provide","/prəˈvaɪd/","v.","ให้, จัดหา","Provide clear answers.","A2"],
["public","/ˈpʌb.lɪk/","adj/n.","สาธารณะ","Use public transport.","A2"],
["purpose","/ˈpɜː.pəs/","n.","จุดประสงค์","What is the purpose?","A2"],
["push","/pʊʃ/","v/n.","ดัน, ผลักดัน","Push yourself.","A2"],
["reach","/riːtʃ/","v.","ไปถึง, บรรลุ","Reach your goals.","A2"],
["reason","/ˈriː.zən/","n.","เหตุผล","Give a good reason.","A2"],
["receive","/rɪˈsiːv/","v.","รับ","She received a letter.","A2"],
["reduce","/rɪˈdjuːs/","v.","ลด","Reduce waste.","A2"],
["reflect","/rɪˈflekt/","v.","สะท้อน, ไตร่ตรอง","Reflect on your actions.","A2"],
["relationship","/rɪˈleɪ.ʃən.ʃɪp/","n.","ความสัมพันธ์","Build strong relationships.","A2"],
["religion","/rɪˈlɪdʒ.ən/","n.","ศาสนา","Religion is personal.","A2"],
["respect","/rɪˈspekt/","v/n.","เคารพ","Respect others.","A2"],
["respond","/rɪˈspɒnd/","v.","ตอบสนอง","Respond quickly.","A2"],
["responsibility","/rɪˌspɒn.sɪˈbɪl.ɪ.ti/","n.","ความรับผิดชอบ","Take responsibility.","A2"],
["role","/rəʊl/","n.","บทบาท","Play your role.","A2"],
["rule","/ruːl/","n/v.","กฎ, ปกครอง","Follow the rules.","A2"],
["section","/ˈsek.ʃən/","n.","ส่วน, หมวด","Read section two.","A2"],
["serious","/ˈsɪər.i.əs/","adj.","จริงจัง","This is a serious matter.","A2"],
["service","/ˈsɜː.vɪs/","n.","บริการ","Good customer service.","A2"],
["several","/ˈsev.ər.əl/","det/pron.","หลาย","Several students failed.","A2"],
["share","/ʃeər/","v/n.","แบ่งปัน, หุ้น","Share your ideas.","A2"],
["similar","/ˈsɪm.ɪ.lər/","adj.","คล้ายกัน","They have similar interests.","A2"],
["situation","/ˌsɪtʃ.uˈeɪ.ʃən/","n.","สถานการณ์","Assess the situation.","A2"],
["skill","/skɪl/","n.","ทักษะ","Build your skills.","A2"],
["society","/səˈsaɪ.ɪ.ti/","n.","สังคม","We live in a society.","A2"],
["solve","/sɒlv/","v.","แก้ปัญหา","Solve the equation.","A2"],
["special","/ˈspeʃ.əl/","adj.","พิเศษ","She is very special.","A2"],
["speech","/spiːtʃ/","n.","演讲, การพูด","He gave a speech.","A2"],
["subject","/ˈsʌb.dʒɪkt/","n.","วิชา, หัวข้อ","Choose your subject.","A2"],
["success","/səkˈses/","n.","ความสำเร็จ","Success takes effort.","A2"],
["suggest","/səˈdʒest/","v.","แนะนำ","What do you suggest?","A2"],
["support","/səˈpɔːt/","v/n.","สนับสนุน","She supports her team.","A2"],
["system","/ˈsɪs.təm/","n.","ระบบ","The system works.","A2"],
["technology","/tekˈnɒl.ə.dʒi/","n.","เทคโนโลยี","Technology is advancing.","A2"],
["though","/ðəʊ/","conj.","แม้ว่า","I'll try, though it's hard.","A2"],
["thought","/θɔːt/","n.","ความคิด","Share your thoughts.","A2"],
["through","/θruː/","prep.","ผ่าน","Work through the problem.","A2"],
["totally","/ˈtəʊ.tə.li/","adv.","โดยสิ้นเชิง","I totally agree.","A2"],
["toward","/təˈwɔːd/","prep.","ไปทาง","Walk toward the exit.","A2"],
["trust","/trʌst/","v/n.","ไว้วางใจ","Trust your instincts.","A2"],
["truth","/truːθ/","n.","ความจริง","Tell the truth.","A2"],
["type","/taɪp/","n/v.","ประเภท, พิมพ์","What type of music?","A2"],
["understand","/ˌʌn.dəˈstænd/","v.","เข้าใจ","I understand now.","A2"],
["unless","/ənˈles/","conj.","ยกเว้นว่า","Don't go unless ready.","A2"],
["useful","/ˈjuːs.fəl/","adj.","มีประโยชน์","This tool is useful.","A2"],
["value","/ˈvæl.juː/","n/v.","คุณค่า, ให้ความสำคัญ","Value your time.","A2"],
["various","/ˈveər.i.əs/","adj.","หลากหลาย","Various options exist.","A2"],
["view","/vjuː/","n/v.","มุมมอง, มอง","Share your view.","A2"],
["voice","/vɔɪs/","n.","เสียง, สิทธิ์แสดงความคิดเห็น","Raise your voice.","A2"],
["whole","/həʊl/","adj/n.","ทั้งหมด","The whole class passed.","A2"],
["wide","/waɪd/","adj/adv.","กว้าง","A wide range of topics.","A2"],
["within","/wɪˈðɪn/","prep.","ภายใน","Finish within an hour.","A2"],
["worry","/ˈwɒr.i/","v/n.","กังวล","Don't worry.","A2"],
// ══════════════════════════════════════════════════════════════════
// B1
// ══════════════════════════════════════════════════════════════════
["absence","/ˈæb.səns/","n.","การขาด, การไม่อยู่","Her absence was noticed.","B1"],
["abstract","/ˈæb.strækt/","adj/n.","เชิงนามธรรม","An abstract concept.","B1"],
["accurate","/ˈæk.jʊ.rət/","adj.","แม่นยำ","Accurate data is needed.","B1"],
["adapt","/əˈdæpt/","v.","ปรับตัว","Adapt to change.","B1"],
["adequate","/ˈæd.ɪ.kwət/","adj.","เพียงพอ","The budget is adequate.","B1"],
["advantage","/ədˈvɑːn.tɪdʒ/","n.","ข้อได้เปรียบ","Use every advantage.","B1"],
["analysis","/əˈnæl.ɪ.sɪs/","n.","การวิเคราะห์","A careful analysis.","B1"],
["ancient","/ˈeɪn.ʃənt/","adj.","โบราณ","Ancient ruins.","B1"],
["approach","/əˈprəʊtʃ/","n/v.","วิธีการ, เข้าหา","A new approach.","B1"],
["appropriate","/əˈprəʊ.pri.ɪt/","adj.","เหมาะสม","Choose appropriate words.","B1"],
["argument","/ˈɑː.ɡjʊ.mənt/","n.","การโต้แย้ง, เหตุผล","A strong argument.","B1"],
["aspect","/ˈæs.pekt/","n.","ด้าน, แง่มุม","Consider every aspect.","B1"],
["assess","/əˈses/","v.","ประเมิน","Assess your progress.","B1"],
["assume","/əˈsjuːm/","v.","สมมติ","Don't assume anything.","B1"],
["benefit","/ˈben.ɪ.fɪt/","n/v.","ประโยชน์","Exercise benefits health.","B1"],
["broad","/brɔːd/","adj.","กว้าง","A broad education.","B1"],
["capacity","/kəˈpæs.ɪ.ti/","n.","ความสามารถ, ขีดความสามารถ","Work at full capacity.","B1"],
["career","/kəˈrɪər/","n.","อาชีพ","Choose a career wisely.","B1"],
["category","/ˈkæt.ɪ.ɡər.i/","n.","หมวดหมู่","Sort into categories.","B1"],
["challenge","/ˈtʃæl.ɪndʒ/","n/v.","ความท้าทาย, ท้าทาย","Face the challenge.","B1"],
["character","/ˈkær.ɪk.tər/","n.","ตัวละคร, บุคลิก","She has strong character.","B1"],
["circumstance","/ˈsɜː.kəm.stæns/","n.","สถานการณ์, เหตุการณ์","In all circumstances.","B1"],
["claim","/kleɪm/","v/n.","อ้าง, เรียกร้อง","He claims innocence.","B1"],
["clearly","/ˈklɪə.li/","adv.","อย่างชัดเจน","State clearly.","B1"],
["complex","/ˈkɒm.pleks/","adj.","ซับซ้อน","A complex problem.","B1"],
["concentrate","/ˈkɒn.sən.treɪt/","v.","มีสมาธิ","Concentrate on the task.","B1"],
["concept","/ˈkɒn.sept/","n.","แนวคิด","Grasp the concept.","B1"],
["concern","/kənˈsɜːn/","n/v.","ความกังวล, เกี่ยวข้อง","Show concern for others.","B1"],
["consequence","/ˈkɒn.sɪ.kwəns/","n.","ผลที่ตามมา","Face the consequences.","B1"],
["context","/ˈkɒn.tekst/","n.","บริบท","Understand the context.","B1"],
["contribution","/ˌkɒn.trɪˈbjuː.ʃən/","n.","การมีส่วนร่วม","Your contribution matters.","B1"],
["convince","/kənˈvɪns/","v.","โน้มน้าว","Convince me.","B1"],
["cope","/kəʊp/","v.","รับมือ","Learn to cope with stress.","B1"],
["critical","/ˈkrɪt.ɪ.kəl/","adj.","สำคัญ, วิจารณ์","Critical thinking skills.","B1"],
["culture","/ˈkʌl.tʃər/","n.","วัฒนธรรม","Respect every culture.","B1"],
["currently","/ˈkʌr.ənt.li/","adv.","ในปัจจุบัน","She currently lives abroad.","B1"],
["debate","/dɪˈbeɪt/","n/v.","ถกเถียง","A healthy debate.","B1"],
["define","/dɪˈfaɪn/","v.","นิยาม","Define your terms.","B1"],
["degree","/dɪˈɡriː/","n.","ระดับ, ปริญญา","To a high degree.","B1"],
["demand","/dɪˈmɑːnd/","n/v.","ความต้องการ","Supply meets demand.","B1"],
["design","/dɪˈzaɪn/","n/v.","ออกแบบ","Design the solution.","B1"],
["despite","/dɪˈspaɪt/","prep.","แม้จะ","She succeeded despite difficulties.","B1"],
["determine","/dɪˈtɜː.mɪn/","v.","กำหนด, ตัดสินใจ","Determine the cause.","B1"],
["diverse","/daɪˈvɜːs/","adj.","หลากหลาย","A diverse workforce.","B1"],
["economic","/ˌiː.kəˈnɒm.ɪk/","adj.","เศรษฐกิจ","Economic growth slowed.","B1"],
["effective","/ɪˈfek.tɪv/","adj.","มีประสิทธิภาพ","An effective strategy.","B1"],
["effort","/ˈef.ət/","n.","ความพยายาม","Put in the effort.","B1"],
["element","/ˈel.ɪ.mənt/","n.","องค์ประกอบ","A key element.","B1"],
["emerge","/ɪˈmɜːdʒ/","v.","ปรากฏขึ้น","New ideas emerge.","B1"],
["emphasis","/ˈem.fə.sɪs/","n.","การเน้น","Place emphasis on skills.","B1"],
["encourage","/ɪnˈkʌr.ɪdʒ/","v.","สนับสนุน","Encourage creativity.","B1"],
["environment","/ɪnˈvaɪ.rən.mənt/","n.","สิ่งแวดล้อม","Protect the environment.","B1"],
["establish","/ɪˈstæb.lɪʃ/","v.","ก่อตั้ง, สร้าง","Establish trust.","B1"],
["estimate","/ˈes.tɪ.meɪt/","v/n.","ประมาณ","Estimate the cost.","B1"],
["evidence","/ˈev.ɪ.dəns/","n.","หลักฐาน","Provide evidence.","B1"],
["exist","/ɪɡˈzɪst/","v.","มีอยู่","Does this problem still exist?","B1"],
["expand","/ɪkˈspænd/","v.","ขยาย","Expand your knowledge.","B1"],
["experience","/ɪkˈspɪər.i.əns/","n/v.","ประสบการณ์","Gain experience.","B1"],
["expert","/ˈek.spɜːt/","n/adj.","ผู้เชี่ยวชาญ","Consult an expert.","B1"],
["explore","/ɪkˈsplɔːr/","v.","สำรวจ","Explore new ideas.","B1"],
["expose","/ɪkˈspəʊz/","v.","เปิดเผย, เปิดรับ","Expose to new ideas.","B1"],
["factor","/ˈfæk.tər/","n.","ปัจจัย","Many factors affect this.","B1"],
["feature","/ˈfiː.tʃər/","n/v.","คุณลักษณะ","Key features of the plan.","B1"],
["field","/fiːld/","n.","สาขา, ทุ่ง","Her field is medicine.","B1"],
["flexible","/ˈflek.sɪ.bəl/","adj.","ยืดหยุ่น","Be flexible.","B1"],
["focus","/ˈfəʊ.kəs/","v/n.","เน้น, โฟกัส","Focus on your goal.","B1"],
["force","/fɔːs/","n/v.","แรง, บังคับ","Don't force it.","B1"],
["foundation","/faʊnˈdeɪ.ʃən/","n.","รากฐาน","Build a strong foundation.","B1"],
["function","/ˈfʌŋk.ʃən/","n/v.","หน้าที่, ทำงาน","What is its function?","B1"],
["fund","/fʌnd/","n/v.","ทุน, จัดหาเงิน","Fund the project.","B1"],
["gain","/ɡeɪn/","v/n.","ได้รับ, กำไร","Gain more knowledge.","B1"],
["global","/ˈɡləʊ.bəl/","adj.","ระดับโลก","A global issue.","B1"],
["growth","/ɡrəʊθ/","n.","การเติบโต","Encourage growth.","B1"],
["guideline","/ˈɡaɪd.laɪn/","n.","แนวทาง","Follow the guidelines.","B1"],
["highlight","/ˈhaɪ.laɪt/","v/n.","เน้น, จุดเด่น","Highlight key points.","B1"],
["hypothesis","/haɪˈpɒθ.ɪ.sɪs/","n.","สมมุติฐาน","Test the hypothesis.","B1"],
["identify","/aɪˈden.tɪ.faɪ/","v.","ระบุ, ชี้ตัว","Identify the problem.","B1"],
["ignore","/ɪɡˈnɔːr/","v.","ไม่สนใจ","Don't ignore warnings.","B1"],
["impact","/ˈɪm.pækt/","n/v.","ผลกระทบ","It has a big impact.","B1"],
["implement","/ˈɪm.plɪ.ment/","v.","ดำเนินการ, นำไปใช้","Implement the plan.","B1"],
["imply","/ɪmˈplaɪ/","v.","บอกเป็นนัย","What does this imply?","B1"],
["indicate","/ˈɪn.dɪ.keɪt/","v.","ชี้บอก","The data indicates progress.","B1"],
["influence","/ˈɪn.flu.əns/","n/v.","อิทธิพล","Peer influence is strong.","B1"],
["interpret","/ɪnˈtɜː.prɪt/","v.","ตีความ","Interpret the graph.","B1"],
["investigate","/ɪnˈves.tɪ.ɡeɪt/","v.","สืบสวน","Investigate the cause.","B1"],
["justify","/ˈdʒʌs.tɪ.faɪ/","v.","พิสูจน์, ให้เหตุผล","Justify your answer.","B1"],
["maintain","/meɪnˈteɪn/","v.","รักษา","Maintain focus.","B1"],
["method","/ˈmeθ.əd/","n.","วิธีการ","Choose the right method.","B1"],
["minimize","/ˈmɪn.ɪ.maɪz/","v.","ลดให้น้อยที่สุด","Minimize risk.","B1"],
["moreover","/ˌmɔːrˈəʊ.vər/","adv.","ยิ่งไปกว่านั้น","Moreover, it saves time.","B1"],
["motivate","/ˈməʊ.tɪ.veɪt/","v.","จูงใจ","Motivate your team.","B1"],
["objective","/əbˈdʒek.tɪv/","n/adj.","เป้าหมาย, เป็นกลาง","Be objective.","B1"],
["obtain","/əbˈteɪn/","v.","ได้รับ, บรรลุ","Obtain a good score.","B1"],
["occur","/əˈkɜːr/","v.","เกิดขึ้น","Problems occur sometimes.","B1"],
["overcome","/ˌəʊ.vəˈkʌm/","v.","เอาชนะ","Overcome your fear.","B1"],
["participate","/pɑːˈtɪs.ɪ.peɪt/","v.","มีส่วนร่วม","Participate actively.","B1"],
["perspective","/pəˈspek.tɪv/","n.","มุมมอง","Consider other perspectives.","B1"],
["potential","/pəˈten.ʃəl/","n/adj.","ศักยภาพ","Reach your potential.","B1"],
["prevent","/prɪˈvent/","v.","ป้องกัน","Prevent errors.","B1"],
["previous","/ˈpriː.vi.əs/","adj.","ก่อนหน้า","Review previous lessons.","B1"],
["primary","/ˈpraɪ.mər.i/","adj.","หลัก, ประถม","The primary goal.","B1"],
["process","/ˈprəʊ.ses/","n/v.","กระบวนการ","Follow the process.","B1"],
["promote","/prəˈməʊt/","v.","ส่งเสริม, โปรโมต","Promote good habits.","B1"],
["prove","/pruːv/","v.","พิสูจน์","Prove your point.","B1"],
["range","/reɪndʒ/","n/v.","ช่วง, หลากหลาย","A wide range.","B1"],
["recent","/ˈriː.sənt/","adj.","ล่าสุด","Recent studies show this.","B1"],
["refer","/rɪˈfɜːr/","v.","อ้างถึง","Refer to the guide.","B1"],
["region","/ˈriː.dʒən/","n.","ภูมิภาค","A dry region.","B1"],
["relevant","/ˈrel.ɪ.vənt/","adj.","เกี่ยวข้อง","Stay relevant.","B1"],
["require","/rɪˈkwaɪər/","v.","ต้องการ","This requires practice.","B1"],
["research","/rɪˈsɜːtʃ/","n/v.","การวิจัย","Conduct research.","B1"],
["resource","/rɪˈzɔːs/","n.","ทรัพยากร","Manage resources well.","B1"],
["reveal","/rɪˈviːl/","v.","เปิดเผย","The study reveals data.","B1"],
["significant","/sɪɡˈnɪf.ɪ.kənt/","adj.","มีนัยสำคัญ","A significant result.","B1"],
["source","/sɔːs/","n.","แหล่งที่มา","Cite your source.","B1"],
["specific","/spəˈsɪf.ɪk/","adj.","เฉพาะ","Be specific.","B1"],
["strategy","/ˈstræt.ɪ.dʒi/","n.","กลยุทธ์","Plan a clear strategy.","B1"],
["structure","/ˈstrʌk.tʃər/","n/v.","โครงสร้าง","Organize the structure.","B1"],
["sufficient","/səˈfɪʃ.ənt/","adj.","เพียงพอ","Sufficient evidence.","B1"],
["summarize","/ˈsʌm.ər.aɪz/","v.","สรุป","Summarize the text.","B1"],
["therefore","/ˈðeə.fɔːr/","adv.","ดังนั้น","Therefore, we conclude.","B1"],
["throughout","/θruːˈaʊt/","prep/adv.","ตลอด","Study throughout the year.","B1"],
["topic","/ˈtɒp.ɪk/","n.","หัวข้อ","Choose a topic.","B1"],
["trend","/trend/","n.","แนวโน้ม","Follow the trend.","B1"],
["unique","/juːˈniːk/","adj.","เป็นเอกลักษณ์","She has a unique talent.","B1"],
["various","/ˈveər.i.əs/","adj.","หลากหลาย","Various solutions exist.","B1"],
// ══════════════════════════════════════════════════════════════════
// B2
// ══════════════════════════════════════════════════════════════════
["abstract","/ˈæb.strækt/","adj.","นามธรรม","Abstract thinking.","B2"],
["acknowledge","/əkˈnɒl.ɪdʒ/","v.","ยอมรับ","Acknowledge the error.","B2"],
["adjacent","/əˈdʒeɪ.sənt/","adj.","ติดกัน","Adjacent buildings.","B2"],
["advocate","/ˈæd.və.kət/","n/v.","ผู้สนับสนุน, สนับสนุน","Advocate for change.","B2"],
["ambiguous","/æmˈbɪɡ.ju.əs/","adj.","กำกวม","An ambiguous statement.","B2"],
["analyze","/ˈæn.ə.laɪz/","v.","วิเคราะห์","Analyze the data.","B2"],
["anticipate","/ænˈtɪs.ɪ.peɪt/","v.","คาดการณ์","Anticipate problems.","B2"],
["apparent","/əˈpær.ənt/","adj.","เห็นได้ชัด","The cause was apparent.","B2"],
["arbitrary","/ˈɑː.bɪ.trər.i/","adj.","ตามอำเภอใจ","An arbitrary choice.","B2"],
["attribute","/əˈtrɪb.juːt/","v/n.","นำไปสู่, คุณลักษณะ","Attribute success to hard work.","B2"],
["coherent","/kəʊˈhɪər.ənt/","adj.","สอดคล้อง, ชัดเจน","A coherent argument.","B2"],
["coincide","/ˌkəʊ.ɪnˈsaɪd/","v.","ตรงกัน","Their views coincide.","B2"],
["comply","/kəmˈplaɪ/","v.","ปฏิบัติตาม","Comply with rules.","B2"],
["conceive","/kənˈsiːv/","v.","คิดขึ้น","Conceive a new plan.","B2"],
["contradict","/ˌkɒn.trəˈdɪkt/","v.","ขัดแย้ง","Facts contradict the claim.","B2"],
["controversial","/ˌkɒn.trəˈvɜː.ʃəl/","adj.","โต้เถียง","A controversial topic.","B2"],
["correlate","/ˈkɒr.ɪ.leɪt/","v.","มีความสัมพันธ์","These two factors correlate.","B2"],
["criteria","/kraɪˈtɪər.i.ə/","n.","เกณฑ์","Meet the criteria.","B2"],
["crucial","/ˈkruː.ʃəl/","adj.","สำคัญอย่างยิ่ง","A crucial decision.","B2"],
["cumulative","/ˈkjuː.mjʊ.lə.tɪv/","adj.","สะสมมากขึ้น","Cumulative effect.","B2"],
["deduce","/dɪˈdjuːs/","v.","อนุมาน","Deduce the answer.","B2"],
["deteriorate","/dɪˈtɪər.i.ə.reɪt/","v.","เสื่อมลง","The situation deteriorated.","B2"],
["domain","/dəˈmeɪn/","n.","ขอบเขต, โดเมน","In the public domain.","B2"],
["elaborate","/ɪˈlæb.ər.ɪt/","adj/v.","ละเอียด, ขยายความ","Please elaborate.","B2"],
["eloquent","/ˈel.ə.kwənt/","adj.","มีวาทศิลป์","An eloquent speaker.","B2"],
["enhance","/ɪnˈhɑːns/","v.","เพิ่มประสิทธิภาพ","Enhance performance.","B2"],
["equivalent","/ɪˈkwɪv.ə.lənt/","adj/n.","เทียบเท่า","Find an equivalent.","B2"],
["ethical","/ˈeθ.ɪ.kəl/","adj.","มีจริยธรรม","Ethical behaviour.","B2"],
["evident","/ˈev.ɪ.dənt/","adj.","ชัดเจน","It is evident.","B2"],
["evolve","/ɪˈvɒlv/","v.","วิวัฒน์","Ideas evolve over time.","B2"],
["fluctuate","/ˈflʌk.tʃu.eɪt/","v.","ผันผวน","Prices fluctuate daily.","B2"],
["formulate","/ˈfɔː.mjʊ.leɪt/","v.","กำหนด, วางแผน","Formulate a plan.","B2"],
["imminent","/ˈɪm.ɪ.nənt/","adj.","ใกล้จะเกิด","Imminent danger.","B2"],
["implicit","/ɪmˈplɪs.ɪt/","adj.","โดยนัย","An implicit agreement.","B2"],
["inevitable","/ɪnˈev.ɪ.tə.bəl/","adj.","หลีกเลี่ยงไม่ได้","Change is inevitable.","B2"],
["inherent","/ɪnˈhɪər.ənt/","adj.","โดยเนื้อแท้","Inherent risks.","B2"],
["innovative","/ˈɪn.ə.veɪ.tɪv/","adj.","สร้างสรรค์, ใหม่","An innovative approach.","B2"],
["interact","/ˌɪn.tərˈækt/","v.","มีปฏิสัมพันธ์","Interact with others.","B2"],
["intuitive","/ɪnˈtjuː.ɪ.tɪv/","adj.","ตามสัญชาตญาณ","An intuitive design.","B2"],
["logical","/ˈlɒdʒ.ɪ.kəl/","adj.","มีตรรกะ","A logical conclusion.","B2"],
["notorious","/nəʊˈtɔː.ri.əs/","adj.","โด่งดังในทางเสีย","A notorious criminal.","B2"],
["obsolete","/ˌɒb.səˈliːt/","adj.","ล้าสมัย","Obsolete technology.","B2"],
["perceive","/pəˈsiːv/","v.","รับรู้","How do you perceive this?","B2"],
["persist","/pəˈsɪst/","v.","ยืนหยัด","Persist despite failure.","B2"],
["phenomenon","/fɪˈnɒm.ɪ.nən/","n.","ปรากฏการณ์","A rare phenomenon.","B2"],
["plausible","/ˈplɔː.zɪ.bəl/","adj.","น่าเชื่อ","A plausible explanation.","B2"],
["predominant","/prɪˈdɒm.ɪ.nənt/","adj.","โดดเด่น, มีมากที่สุด","The predominant view.","B2"],
["principle","/ˈprɪn.sɪ.pəl/","n.","หลักการ","Core principles.","B2"],
["reinforce","/ˌriː.ɪnˈfɔːs/","v.","เสริมแรง","Reinforce the concept.","B2"],
["resilient","/rɪˈzɪl.i.ənt/","adj.","ฟื้นตัวได้ดี","Stay resilient.","B2"],
["restrain","/rɪˈstreɪn/","v.","ยับยั้ง","Restrain your anger.","B2"],
["scrutiny","/ˈskruː.tɪ.ni/","n.","การตรวจสอบ","Under public scrutiny.","B2"],
["skeptical","/ˈskep.tɪ.kəl/","adj.","สงสัย","Remain skeptical.","B2"],
["substitute","/ˈsʌb.stɪ.tjuːt/","n/v.","ทดแทน","Find a substitute.","B2"],
["suppress","/səˈpres/","v.","ระงับ","Suppress emotions.","B2"],
["sustain","/səˈsteɪn/","v.","รักษาต่อเนื่อง","Sustain the effort.","B2"],
["systematic","/ˌsɪs.tɪˈmæt.ɪk/","adj.","เป็นระบบ","A systematic approach.","B2"],
["withhold","/wɪðˈhəʊld/","v.","ปิดบัง","Withhold information.","B2"],
// ══════════════════════════════════════════════════════════════════
// C1  (bonus — เน้นออกสอบ TOEFL / A-Level)
// ══════════════════════════════════════════════════════════════════
["alleviate","/əˈliː.vi.eɪt/","v.","บรรเทา","Alleviate pain.","C1"],
["ambivalent","/æmˈbɪv.ə.lənt/","adj.","รู้สึกสองอย่าง","Ambivalent feelings.","C1"],
["anachronistic","/əˌnæk.rəˈnɪs.tɪk/","adj.","ล้าสมัย","An anachronistic attitude.","C1"],
["anomaly","/əˈnɒm.ə.li/","n.","สิ่งผิดปกติ","A statistical anomaly.","C1"],
["circumvent","/ˌsɜː.kəmˈvent/","v.","หลบเลี่ยง","Circumvent the problem.","C1"],
["cogent","/ˈkəʊ.dʒənt/","adj.","น่าเชื่อถือ","A cogent argument.","C1"],
["complacent","/kəmˈpleɪ.sənt/","adj.","พอใจเกินไป","Don't be complacent.","C1"],
["contentious","/kənˈten.ʃəs/","adj.","เป็นที่ถกเถียง","A contentious issue.","C1"],
["corroborate","/kəˈrɒb.ə.reɪt/","v.","ยืนยัน","Corroborate the evidence.","C1"],
["didactic","/daɪˈdæk.tɪk/","adj.","แฝงคติสั่งสอน","A didactic novel.","C1"],
["disparate","/ˈdɪs.pər.ɪt/","adj.","แตกต่างมาก","Disparate views.","C1"],
["ephemeral","/ɪˈfem.ər.əl/","adj.","ชั่วคราว","Ephemeral trends.","C1"],
["exacerbate","/ɪɡˈzæs.ə.beɪt/","v.","ทำให้แย่ลง","Exacerbate conflict.","C1"],
["expedite","/ˈek.spɪ.daɪt/","v.","เร่งรัด","Expedite the process.","C1"],
["frivolous","/ˈfrɪv.ə.ləs/","adj.","ไร้สาระ","A frivolous claim.","C1"],
["gregarious","/ɡrɪˈɡeər.i.əs/","adj.","ชอบสังคม","A gregarious personality.","C1"],
["incongruous","/ɪnˈkɒŋ.ɡru.əs/","adj.","ไม่เข้ากัน","An incongruous comment.","C1"],
["jeopardize","/ˈdʒep.ə.daɪz/","v.","ทำให้เสี่ยง","Jeopardize safety.","C1"],
["meticulous","/məˈtɪk.jʊ.ləs/","adj.","พิถีพิถัน","Meticulous research.","C1"],
["mitigate","/ˈmɪt.ɪ.ɡeɪt/","v.","บรรเทา","Mitigate the risk.","C1"],
["ostensibly","/ɒˈsten.sɪ.bli/","adv.","ดูเหมือนว่า","Ostensibly correct.","C1"],
["perfunctory","/pəˈfʌŋk.tər.i/","adj.","ทำไปงั้น","A perfunctory reply.","C1"],
["pragmatic","/præɡˈmæt.ɪk/","adj.","ปฏิบัตินิยม","A pragmatic solution.","C1"],
["proliferate","/prəˈlɪf.ər.eɪt/","v.","แพร่กระจาย","Ideas proliferate.","C1"],
["quandary","/ˈkwɒn.dər.i/","n.","สถานการณ์ลำบาก","In a quandary.","C1"],
["recalcitrant","/rɪˈkæl.sɪ.trənt/","adj.","ดื้อดึง","A recalcitrant attitude.","C1"],
["rectify","/ˈrek.tɪ.faɪ/","v.","แก้ไข","Rectify the mistake.","C1"],
["scrutinize","/ˈskruː.tɪ.naɪz/","v.","ตรวจละเอียด","Scrutinize every detail.","C1"],
["spurious","/ˈspjʊər.i.əs/","adj.","ปลอม","A spurious argument.","C1"],
["superfluous","/suːˈpɜː.flu.əs/","adj.","เกินจำเป็น","Remove superfluous words.","C1"],
["tenacious","/təˈneɪ.ʃəs/","adj.","อดทน","A tenacious spirit.","C1"],
["ubiquitous","/juːˈbɪk.wɪ.təs/","adj.","อยู่ทุกหนทุกแห่ง","Smartphones are ubiquitous.","C1"],
["unanimously","/juːˈnæn.ɪ.məs.li/","adv.","เป็นเอกฉันท์","Voted unanimously.","C1"],
["zealous","/ˈzel.əs/","adj.","มุ่งมั่นมาก","A zealous student.","C1"],
];

// ── BATCH 2: Oxford 3000 เพิ่มเติม ──────────────────────────────
const VOCAB2 = [
// A2 เพิ่ม
["account","/əˈkaʊnt/","n/v.","บัญชี, อธิบาย","Give a full account of events.","A2"],
["achieve","/əˈtʃiːv/","v.","บรรลุ","Achieve your dreams.","A2"],
["adventure","/ədˈven.tʃər/","n.","การผจญภัย","Life is an adventure.","A2"],
["advertise","/ˈæd.və.taɪz/","v.","โฆษณา","They advertise on TV.","A2"],
["afraid","/əˈfreɪd/","adj.","กลัว","Don't be afraid of failure.","A2"],
["agriculture","/ˈæɡ.rɪ.kʌl.tʃər/","n.","เกษตรกรรม","Agriculture feeds the world.","A2"],
["ahead","/əˈhed/","adv.","ข้างหน้า","Look ahead.","A2"],
["aim","/eɪm/","n/v.","เป้าหมาย, มุ่ง","Aim high.","A2"],
["airport","/ˈeə.pɔːt/","n.","สนามบิน","The airport is busy.","A2"],
["alarm","/əˈlɑːm/","n/v.","สัญญาณเตือน","Set the alarm.","A2"],
["almost","/ˈɔːl.məʊst/","adv.","เกือบ","She almost passed.","A2"],
["alone","/əˈləʊn/","adj/adv.","คนเดียว","She works alone.","A2"],
["announce","/əˈnaʊns/","v.","ประกาศ","Announce the results.","A2"],
["apologize","/əˈpɒl.ə.dʒaɪz/","v.","ขอโทษ","He apologized sincerely.","A2"],
["arrange","/əˈreɪndʒ/","v.","จัดการ, จัดเรียง","Arrange a meeting.","A2"],
["article","/ˈɑː.tɪ.kəl/","n.","บทความ, ข้อ","Read the article.","A2"],
["artistic","/ɑːˈtɪs.tɪk/","adj.","มีความเป็นศิลปะ","She is very artistic.","A2"],
["assist","/əˈsɪst/","v.","ช่วยเหลือ","Can you assist me?","A2"],
["association","/əˌsəʊ.siˈeɪ.ʃən/","n.","สมาคม","Join the association.","A2"],
["atmosphere","/ˈæt.mə.sfɪər/","n.","บรรยากาศ","The atmosphere is tense.","A2"],
["attack","/əˈtæk/","v/n.","โจมตี","Defend against attack.","A2"],
["average","/ˈæv.ər.ɪdʒ/","adj/n.","เฉลี่ย","The average score is 70.","A2"],
["award","/əˈwɔːd/","n/v.","รางวัล","Win an award.","A2"],
["background","/ˈbæk.ɡraʊnd/","n.","ภูมิหลัง","What is your background?","A2"],
["balance","/ˈbæl.əns/","n/v.","ความสมดุล","Maintain balance.","A2"],
["band","/bænd/","n.","วงดนตรี, แถบ","She plays in a band.","A2"],
["basic","/ˈbeɪ.sɪk/","adj.","พื้นฐาน","Learn the basics.","A2"],
["behaviour","/bɪˈheɪ.vjər/","n.","พฤติกรรม","Good behaviour is key.","A2"],
["belong","/bɪˈlɒŋ/","v.","เป็นของ, สังกัด","Where do you belong?","A2"],
["birth","/bɜːθ/","n.","การเกิด","Date of birth?","A2"],
["block","/blɒk/","n/v.","ตึก, ขัดขวาง","Block the road.","A2"],
["border","/ˈbɔː.dər/","n.","ชายแดน","Cross the border.","A2"],
["breathe","/briːð/","v.","หายใจ","Breathe deeply.","A2"],
["bright","/braɪt/","adj.","สว่าง, ฉลาด","She has a bright future.","A2"],
["budget","/ˈbʌdʒ.ɪt/","n.","งบประมาณ","Stick to the budget.","A2"],
["calm","/kɑːm/","adj/v.","สงบ","Stay calm.","A2"],
["campaign","/kæmˈpeɪn/","n.","การรณรงค์","Join the campaign.","A2"],
["capital","/ˈkæp.ɪ.təl/","n.","เมืองหลวง, ทุน","Bangkok is the capital.","A2"],
["capture","/ˈkæp.tʃər/","v.","จับ, บันทึก","Capture the moment.","A2"],
["centre","/ˈsen.tər/","n.","ศูนย์กลาง","The city centre is busy.","A2"],
["characteristic","/ˌkær.ɪk.təˈrɪs.tɪk/","n/adj.","ลักษณะเฉพาะ","List the characteristics.","A2"],
["chart","/tʃɑːt/","n/v.","แผนภูมิ","Read the chart.","A2"],
["citizen","/ˈsɪt.ɪ.zən/","n.","พลเมือง","Be a good citizen.","A2"],
["claim","/kleɪm/","v/n.","อ้าง, เรียกร้อง","Claim your prize.","A2"],
["climate","/ˈklaɪ.mɪt/","n.","ภูมิอากาศ","Climate change is real.","A2"],
["code","/kəʊd/","n/v.","รหัส, เขียนโค้ด","Enter the code.","A2"],
["commit","/kəˈmɪt/","v.","ทำ, มุ่งมั่น","Commit to your goals.","A2"],
["communicate","/kəˈmjuː.nɪ.keɪt/","v.","สื่อสาร","Communicate clearly.","A2"],
["community","/kəˈmjuː.nɪ.ti/","n.","ชุมชน","Help the community.","A2"],
["competition","/ˌkɒm.pɪˈtɪʃ.ən/","n.","การแข่งขัน","Enter the competition.","A2"],
["complaint","/kəmˈpleɪnt/","n.","ข้อร้องเรียน","File a complaint.","A2"],
["concentrate","/ˈkɒn.sən.treɪt/","v.","มีสมาธิ","Concentrate fully.","A2"],
["condition","/kənˈdɪʃ.ən/","n.","เงื่อนไข, สภาพ","In good condition.","A2"],
["confident","/ˈkɒn.fɪ.dənt/","adj.","มั่นใจ","Be confident.","A2"],
["contact","/ˈkɒn.tækt/","n/v.","การติดต่อ","Contact me anytime.","A2"],
["content","/ˈkɒn.tent/","n.","เนื้อหา","Check the content.","A2"],
["conversation","/ˌkɒn.vəˈseɪ.ʃən/","n.","การสนทนา","Have a good conversation.","A2"],
["copy","/ˈkɒp.i/","n/v.","สำเนา, คัดลอก","Copy the notes.","A2"],
["corner","/ˈkɔː.nər/","n.","มุม","Wait at the corner.","A2"],
["cover","/ˈkʌv.ər/","v/n.","ปกคลุม, ปก","Cover the topic.","A2"],
["crash","/kræʃ/","v/n.","ชน, ล้ม","The car crashed.","A2"],
["creative","/kriˈeɪ.tɪv/","adj.","สร้างสรรค์","Be creative.","A2"],
["crowd","/kraʊd/","n.","ฝูงชน","A large crowd gathered.","A2"],
["current","/ˈkʌr.ənt/","adj/n.","ปัจจุบัน","Current events matter.","A2"],
["curve","/kɜːv/","n/v.","โค้ง","A steep learning curve.","A2"],
["data","/ˈdeɪ.tə/","n.","ข้อมูล","Collect data carefully.","A2"],
["deal","/diːl/","v/n.","จัดการ, ข้อตกลง","Deal with the issue.","A2"],
["debate","/dɪˈbeɪt/","n/v.","การถกเถียง","Join the debate.","A2"],
["delay","/dɪˈleɪ/","n/v.","ความล่าช้า","No more delays.","A2"],
["deliver","/dɪˈlɪv.ər/","v.","ส่ง, นำเสนอ","Deliver the message.","A2"],
["democracy","/dɪˈmɒk.rə.si/","n.","ประชาธิปไตย","Protect democracy.","A2"],
["detail","/ˈdiː.teɪl/","n.","รายละเอียด","Pay attention to detail.","A2"],
["diet","/ˈdaɪ.ɪt/","n.","อาหาร, การควบคุมอาหาร","Eat a balanced diet.","A2"],
["digital","/ˈdɪdʒ.ɪ.təl/","adj.","ดิจิทัล","Digital skills are vital.","A2"],
["direction","/dɪˈrek.ʃən/","n.","ทิศทาง","Follow the direction.","A2"],
["discover","/dɪˈskʌv.ər/","v.","ค้นพบ","Discover new things.","A2"],
["disease","/dɪˈziːz/","n.","โรค","Prevent disease.","A2"],
["document","/ˈdɒk.jʊ.mənt/","n/v.","เอกสาร","Submit the document.","A2"],
["doubt","/daʊt/","n/v.","ความสงสัย","When in doubt, ask.","A2"],
["dream","/driːm/","n/v.","ความฝัน","Dream big.","A2"],
["education","/ˌedʒ.uˈkeɪ.ʃən/","n.","การศึกษา","Education opens doors.","A2"],
["election","/ɪˈlek.ʃən/","n.","การเลือกตั้ง","Vote in the election.","A2"],
["emotion","/ɪˈməʊ.ʃən/","n.","อารมณ์","Control your emotions.","A2"],
["empty","/ˈemp.ti/","adj.","ว่าง, ไม่มีอะไร","The room is empty.","A2"],
["enemy","/ˈen.ɪ.mi/","n.","ศัตรู","Keep no enemies.","A2"],
["engineer","/ˌen.dʒɪˈnɪər/","n.","วิศวกร","She is an engineer.","A2"],
["enter","/ˈen.tər/","v.","เข้าไป","Enter the room.","A2"],
["equal","/ˈiː.kwəl/","adj.","เท่ากัน","Everyone is equal.","A2"],
["escape","/ɪˈskeɪp/","v/n.","หนี","There is no escape.","A2"],
["exchange","/ɪksˈtʃeɪndʒ/","v/n.","แลกเปลี่ยน","Exchange ideas.","A2"],
["exercise","/ˈek.sə.saɪz/","n/v.","การออกกำลังกาย","Exercise daily.","A2"],
["experiment","/ɪkˈsper.ɪ.mənt/","n/v.","การทดลอง","Run an experiment.","A2"],
["expert","/ˈek.spɜːt/","n.","ผู้เชี่ยวชาญ","Ask an expert.","A2"],
["express","/ɪkˈspres/","v.","แสดงออก","Express yourself.","A2"],
["extra","/ˈek.strə/","adj.","พิเศษ, เพิ่มเติม","An extra copy.","A2"],
["extreme","/ɪkˈstriːm/","adj.","สุดโต่ง","Extreme weather.","A2"],
["facility","/fəˈsɪl.ɪ.ti/","n.","สิ่งอำนวยความสะดวก","Modern facilities.","A2"],
["famous","/ˈfeɪ.məs/","adj.","มีชื่อเสียง","She is famous.","A2"],
["fashion","/ˈfæʃ.ən/","n.","แฟชั่น","Keep up with fashion.","A2"],
["fear","/fɪər/","n/v.","ความกลัว","Face your fears.","A2"],
["female","/ˈfiː.meɪl/","adj/n.","เพศหญิง","Female athletes excel.","A2"],
["festival","/ˈfes.tɪ.vəl/","n.","เทศกาล","Enjoy the festival.","A2"],
["fight","/faɪt/","v/n.","ต่อสู้","Fight for your rights.","A2"],
["figure","/ˈfɪɡ.ər/","n.","ตัวเลข, บุคคล","A key figure.","A2"],
["fix","/fɪks/","v.","แก้ไข, ซ่อม","Fix the problem.","A2"],
["flight","/flaɪt/","n.","เที่ยวบิน","Book your flight.","A2"],
["flow","/fləʊ/","n/v.","การไหล","The water flows.","A2"],
["forest","/ˈfɒr.ɪst/","n.","ป่า","Protect the forest.","A2"],
["formal","/ˈfɔː.məl/","adj.","เป็นทางการ","Wear formal clothes.","A2"],
["freedom","/ˈfriː.dəm/","n.","อิสรภาพ","Cherish your freedom.","A2"],
["fresh","/freʃ/","adj.","สด, ใหม่","Fresh ideas.","A2"],
["function","/ˈfʌŋk.ʃən/","n/v.","หน้าที่, ทำงาน","What is its function?","A2"],
["future","/ˈfjuː.tʃər/","n/adj.","อนาคต","Plan for the future.","A2"],
["gap","/ɡæp/","n.","ช่องว่าง","Bridge the gap.","A2"],
["gather","/ˈɡæð.ər/","v.","รวบรวม, รวมตัว","Gather information.","A2"],
["gender","/ˈdʒen.dər/","n.","เพศ","Gender equality matters.","A2"],
["generation","/ˌdʒen.əˈreɪ.ʃən/","n.","รุ่น","The next generation.","A2"],
["graduate","/ˈɡrædʒ.u.ɪt/","n/v.","บัณฑิต, สำเร็จการศึกษา","She graduated last year.","A2"],
["grant","/ɡrɑːnt/","v/n.","ให้, ทุน","Apply for a grant.","A2"],
["guide","/ɡaɪd/","n/v.","คู่มือ, นำทาง","Follow the guide.","A2"],
["guilty","/ˈɡɪl.ti/","adj.","รู้สึกผิด","She felt guilty.","A2"],
["habit","/ˈhæb.ɪt/","n.","นิสัย","Build good habits.","A2"],
["harm","/hɑːm/","n/v.","อันตราย","Do no harm.","A2"],
["headline","/ˈhed.laɪn/","n.","หัวข้อข่าว","Read the headline.","A2"],
["heavy","/ˈhev.i/","adj.","หนัก","A heavy workload.","A2"],
["hide","/haɪd/","v.","ซ่อน","Don't hide the truth.","A2"],
["hire","/haɪər/","v.","จ้าง","Hire the best people.","A2"],
["history","/ˈhɪs.tər.i/","n.","ประวัติศาสตร์","Learn from history.","A2"],
["honest","/ˈɒn.ɪst/","adj.","ซื่อสัตย์","Be honest.","A2"],
["huge","/hjuːdʒ/","adj.","ใหญ่มาก","A huge opportunity.","A2"],
["hurt","/hɜːt/","v.","เจ็บ, ทำให้เสียใจ","Words can hurt.","A2"],
["identify","/aɪˈden.tɪ.faɪ/","v.","ระบุ","Identify the key issue.","A2"],
["illness","/ˈɪl.nəs/","n.","ความเจ็บป่วย","Recover from illness.","A2"],
["imagine","/ɪˈmædʒ.ɪn/","v.","จินตนาการ","Imagine a better world.","A2"],
["impact","/ˈɪm.pækt/","n/v.","ผลกระทบ","Reduce the impact.","A2"],
["income","/ˈɪn.kʌm/","n.","รายได้","Increase your income.","A2"],
["industry","/ˈɪn.də.stri/","n.","อุตสาหกรรม","The tech industry.","A2"],
["inform","/ɪnˈfɔːm/","v.","แจ้ง","Inform the team.","A2"],
["injure","/ˈɪn.dʒər/","v.","ทำให้บาดเจ็บ","She injured her leg.","A2"],
["inspire","/ɪnˈspaɪər/","v.","สร้างแรงบันดาลใจ","Inspire others.","A2"],
["intelligent","/ɪnˈtel.ɪ.dʒənt/","adj.","ฉลาด","She is intelligent.","A2"],
["interview","/ˈɪn.tə.vjuː/","n/v.","สัมภาษณ์","Prepare for the interview.","A2"],
["introduce","/ˌɪn.trəˈdjuːs/","v.","แนะนำ, นำเสนอ","Introduce yourself.","A2"],
["invest","/ɪnˈvest/","v.","ลงทุน","Invest in education.","A2"],
["involve","/ɪnˈvɒlv/","v.","เกี่ยวข้อง","Involve everyone.","A2"],
["judge","/dʒʌdʒ/","v/n.","ตัดสิน","Don't judge quickly.","A2"],
["justice","/ˈdʒʌs.tɪs/","n.","ความยุติธรรม","Seek justice.","A2"],
["key","/kiː/","adj/n.","สำคัญ, กุญแจ","The key point is this.","A2"],
["knowledge","/ˈnɒl.ɪdʒ/","n.","ความรู้","Share your knowledge.","A2"],
["land","/lænd/","n/v.","ที่ดิน, ลงจอด","The plane will land soon.","A2"],
["launch","/lɔːntʃ/","v/n.","เปิดตัว, ส่งออก","Launch the product.","A2"],
["law","/lɔː/","n.","กฎหมาย","Follow the law.","A2"],
["leader","/ˈliː.dər/","n.","ผู้นำ","Be a good leader.","A2"],
["lesson","/ˈles.ən/","n.","บทเรียน","Learn your lesson.","A2"],
["link","/lɪŋk/","n/v.","เชื่อมโยง","Link the ideas.","A2"],
["list","/lɪst/","n/v.","รายการ","Make a list.","A2"],
["location","/ləʊˈkeɪ.ʃən/","n.","สถานที่, ตำแหน่ง","Choose a location.","A2"],
["logical","/ˈlɒdʒ.ɪ.kəl/","adj.","มีเหตุผล","Think logically.","A2"],
["male","/meɪl/","adj/n.","เพศชาย","Male students.","A2"],
["mark","/mɑːk/","n/v.","เครื่องหมาย, ให้คะแนน","Mark the answer.","A2"],
["match","/mætʃ/","n/v.","คู่, จับคู่","Find the match.","A2"],
["material","/məˈtɪər.i.əl/","n/adj.","วัสดุ","Use the right material.","A2"],
["media","/ˈmiː.di.ə/","n.","สื่อ","Social media is powerful.","A2"],
["medical","/ˈmed.ɪ.kəl/","adj.","ทางการแพทย์","Medical care is vital.","A2"],
["message","/ˈmes.ɪdʒ/","n.","ข้อความ","Send a message.","A2"],
["mistake","/mɪˈsteɪk/","n.","ความผิดพลาด","Learn from mistakes.","A2"],
["modern","/ˈmɒd.ən/","adj.","ทันสมัย","Modern technology.","A2"],
["motivate","/ˈməʊ.tɪ.veɪt/","v.","จูงใจ","Stay motivated.","A2"],
["movement","/ˈmuːv.mənt/","n.","การเคลื่อนไหว","A social movement.","A2"],
["necessary","/ˈnes.ɪ.ser.i/","adj.","จำเป็น","Is it necessary?","A2"],
["negative","/ˈneɡ.ə.tɪv/","adj.","เชิงลบ","Avoid negative thinking.","A2"],
["network","/ˈnet.wɜːk/","n/v.","เครือข่าย","Build your network.","A2"],
["normal","/ˈnɔː.məl/","adj.","ปกติ","That is normal.","A2"],
["note","/nəʊt/","n/v.","บันทึก","Take notes.","A2"],
["object","/ˈɒb.dʒɪkt/","n/v.","วัตถุ, คัดค้าน","Do you object?","A2"],
["observe","/əbˈzɜːv/","v.","สังเกต","Observe carefully.","A2"],
["opportunity","/ˌɒp.əˈtjuː.nɪ.ti/","n.","โอกาส","Seize the opportunity.","A2"],
["order","/ˈɔː.dər/","n/v.","คำสั่ง, สั่ง","In order to succeed.","A2"],
["organize","/ˈɔː.ɡə.naɪz/","v.","จัดระเบียบ","Organize your time.","A2"],
["original","/əˈrɪdʒ.ɪ.nəl/","adj.","ต้นฉบับ, แปลกใหม่","Be original.","A2"],
["outcome","/ˈaʊt.kʌm/","n.","ผลลัพธ์","A positive outcome.","A2"],
["overcome","/ˌəʊ.vəˈkʌm/","v.","เอาชนะ","Overcome obstacles.","A2"],
["pain","/peɪn/","n.","ความเจ็บปวด","Manage the pain.","A2"],
["participate","/pɑːˈtɪs.ɪ.peɪt/","v.","มีส่วนร่วม","Participate actively.","A2"],
["patient","/ˈpeɪ.ʃənt/","adj/n.","ใจเย็น, ผู้ป่วย","Be patient.","A2"],
["pattern","/ˈpæt.ən/","n.","รูปแบบ","Find the pattern.","A2"],
["physical","/ˈfɪz.ɪ.kəl/","adj.","ทางร่างกาย","Physical health.","A2"],
["plot","/plɒt/","n/v.","โครงเรื่อง, วางแผน","The plot is exciting.","A2"],
["positive","/ˈpɒz.ɪ.tɪv/","adj.","เชิงบวก","Stay positive.","A2"],
["poverty","/ˈpɒv.ə.ti/","n.","ความยากจน","Reduce poverty.","A2"],
["power","/ˈpaʊər/","n.","อำนาจ, พลังงาน","Knowledge is power.","A2"],
["practice","/ˈpræk.tɪs/","n/v.","การฝึกฝน","Practice makes perfect.","A2"],
["pressure","/ˈpreʃ.ər/","n.","แรงกดดัน","Handle pressure well.","A2"],
["principle","/ˈprɪn.sɪ.pəl/","n.","หลักการ","Stick to your principles.","A2"],
["priority","/praɪˈɒr.ɪ.ti/","n.","สิ่งที่สำคัญที่สุด","Set your priorities.","A2"],
["private","/ˈpraɪ.vɪt/","adj.","ส่วนตัว","Keep it private.","A2"],
["profit","/ˈprɒf.ɪt/","n.","กำไร","Earn a profit.","A2"],
["project","/ˈprɒdʒ.ekt/","n/v.","โครงการ","Start the project.","A2"],
["property","/ˈprɒp.ə.ti/","n.","ทรัพย์สิน","Protect your property.","A2"],
["protest","/ˈprəʊ.test/","n/v.","การประท้วง","Join the protest.","A2"],
["prove","/pruːv/","v.","พิสูจน์","Prove your point.","A2"],
["quality","/ˈkwɒl.ɪ.ti/","n.","คุณภาพ","High quality work.","A2"],
["quantity","/ˈkwɒn.tɪ.ti/","n.","ปริมาณ","Quality over quantity.","A2"],
["question","/ˈkwes.tʃən/","n/v.","คำถาม","Question everything.","A2"],
["quite","/kwaɪt/","adv.","ค่อนข้าง","Quite interesting.","A2"],
["raise","/reɪz/","v.","ยกขึ้น, เพิ่ม","Raise your hand.","A2"],
["rate","/reɪt/","n/v.","อัตรา, ประเมิน","The pass rate is high.","A2"],
["rather","/ˈrɑː.ðər/","adv.","ค่อนข้าง, แทนที่","Rather than wait, act.","A2"],
["reaction","/riˈæk.ʃən/","n.","ปฏิกิริยา","What was your reaction?","A2"],
["reality","/riˈæl.ɪ.ti/","n.","ความเป็นจริง","Face reality.","A2"],
["recognize","/ˈrek.əɡ.naɪz/","v.","รู้จัก","Recognize the pattern.","A2"],
["record","/rɪˈkɔːd/","v/n.","บันทึก","Set a record.","A2"],
["register","/ˈredʒ.ɪ.stər/","v/n.","ลงทะเบียน","Register online.","A2"],
["relate","/rɪˈleɪt/","v.","เกี่ยวข้อง","Relate to the topic.","A2"],
["release","/rɪˈliːs/","v/n.","ปล่อย","Release the results.","A2"],
["reliable","/rɪˈlaɪ.ə.bəl/","adj.","น่าเชื่อถือ","Be reliable.","A2"],
["remain","/rɪˈmeɪn/","v.","ยังคง","Remain focused.","A2"],
["remove","/rɪˈmuːv/","v.","เอาออก","Remove the error.","A2"],
["represent","/ˌrep.rɪˈzent/","v.","เป็นตัวแทน","Represent your school.","A2"],
["request","/rɪˈkwest/","n/v.","คำร้องขอ","Submit a request.","A2"],
["research","/rɪˈsɜːtʃ/","n/v.","การวิจัย","Do your research.","A2"],
["resist","/rɪˈzɪst/","v.","ต้านทาน, ต่อต้าน","Resist the temptation.","A2"],
["review","/rɪˈvjuː/","n/v.","ทบทวน","Review your notes.","A2"],
["rise","/raɪz/","v/n.","เพิ่มขึ้น","The sun rises.","A2"],
["risk","/rɪsk/","n/v.","ความเสี่ยง","Take a calculated risk.","A2"],
["route","/ruːt/","n.","เส้นทาง","Choose the best route.","A2"],
["save","/seɪv/","v.","ประหยัด, บันทึก","Save your work.","A2"],
["scale","/skeɪl/","n/v.","ขนาด, ระดับ","On a large scale.","A2"],
["schedule","/ˈʃed.juːl/","n/v.","ตารางเวลา","Follow the schedule.","A2"],
["science","/ˈsaɪəns/","n.","วิทยาศาสตร์","Study science.","A2"],
["score","/skɔːr/","n/v.","คะแนน","Improve your score.","A2"],
["search","/sɜːtʃ/","v/n.","ค้นหา","Search for answers.","A2"],
["select","/sɪˈlekt/","v.","เลือก","Select the best option.","A2"],
["senior","/ˈsiː.ni.ər/","adj/n.","อาวุโส, รุ่นพี่","A senior student.","A2"],
["sensitive","/ˈsen.sɪ.tɪv/","adj.","ไว, อ่อนไหว","Be sensitive to others.","A2"],
["separate","/ˈsep.ər.ɪt/","adj/v.","แยกกัน","Separate fact from opinion.","A2"],
["share","/ʃeər/","v/n.","แบ่งปัน","Share your ideas.","A2"],
["sign","/saɪn/","n/v.","สัญญาณ, ลงชื่อ","Sign the form.","A2"],
["solve","/sɒlv/","v.","แก้ปัญหา","Solve the equation.","A2"],
["source","/sɔːs/","n.","แหล่งที่มา","Cite the source.","A2"],
["space","/speɪs/","n.","พื้นที่, อวกาศ","Give me some space.","A2"],
["speed","/spiːd/","n/v.","ความเร็ว","Increase speed.","A2"],
["spread","/spred/","v.","กระจาย","Spread knowledge.","A2"],
["standard","/ˈstæn.dəd/","n/adj.","มาตรฐาน","Raise the standard.","A2"],
["state","/steɪt/","n/v.","สภาพ, แถลง","State your opinion.","A2"],
["status","/ˈsteɪ.təs/","n.","สถานะ","What is the status?","A2"],
["step","/step/","n/v.","ขั้นตอน","Take it step by step.","A2"],
["store","/stɔːr/","n/v.","ร้าน, เก็บ","Store data safely.","A2"],
["strategy","/ˈstræt.ɪ.dʒi/","n.","กลยุทธ์","Have a clear strategy.","A2"],
["style","/staɪl/","n.","สไตล์","Develop your own style.","A2"],
["survey","/ˈsɜː.veɪ/","n/v.","การสำรวจ","Conduct a survey.","A2"],
["survive","/səˈvaɪv/","v.","รอดชีวิต","Survive the challenge.","A2"],
["symbol","/ˈsɪm.bəl/","n.","สัญลักษณ์","A powerful symbol.","A2"],
["talent","/ˈtæl.ənt/","n.","ความสามารถพิเศษ","Develop your talent.","A2"],
["task","/tɑːsk/","n.","งาน, ภารกิจ","Complete each task.","A2"],
["team","/tiːm/","n.","ทีม","Work as a team.","A2"],
["technique","/tekˈniːk/","n.","เทคนิค","Use the right technique.","A2"],
["temperature","/ˈtem.prɪ.tʃər/","n.","อุณหภูมิ","High temperature.","A2"],
["text","/tekst/","n/v.","ข้อความ, ส่ง SMS","Read the text.","A2"],
["topic","/ˈtɒp.ɪk/","n.","หัวข้อ","Discuss the topic.","A2"],
["tradition","/trəˈdɪʃ.ən/","n.","ประเพณี","Respect traditions.","A2"],
["train","/treɪn/","v/n.","ฝึก, รถไฟ","Train hard.","A2"],
["transport","/ˈtræns.pɔːt/","n/v.","การขนส่ง","Public transport.","A2"],
["treat","/triːt/","v.","ปฏิบัติ, รักษา","Treat others well.","A2"],
["trend","/trend/","n.","แนวโน้ม","A growing trend.","A2"],
["twice","/twaɪs/","adv.","สองครั้ง","Think twice.","A2"],
["typical","/ˈtɪp.ɪ.kəl/","adj.","โดยทั่วไป","A typical day.","A2"],
["unfortunately","/ʌnˈfɔː.tʃə.nɪt.li/","adv.","น่าเสียดาย","Unfortunately, she failed.","A2"],
["unique","/juːˈniːk/","adj.","เป็นเอกลักษณ์","She is unique.","A2"],
["useful","/ˈjuːs.fəl/","adj.","มีประโยชน์","Very useful tool.","A2"],
["victory","/ˈvɪk.tər.i/","n.","ชัยชนะ","Celebrate the victory.","A2"],
["violence","/ˈvaɪə.ləns/","n.","ความรุนแรง","Avoid violence.","A2"],
["vision","/ˈvɪʒ.ən/","n.","วิสัยทัศน์","Share the vision.","A2"],
["volunteer","/ˌvɒl.ənˈtɪər/","n/v.","อาสาสมัคร","Volunteer your time.","A2"],
["vote","/vəʊt/","v/n.","ลงคะแนน","Vote for change.","A2"],
["waste","/weɪst/","n/v.","สิ่งเสีย, สูญเสีย","Don't waste time.","A2"],
["wealth","/welθ/","n.","ความมั่งคั่ง","Health over wealth.","A2"],
["weapon","/ˈwep.ən/","n.","อาวุธ","Words are weapons.","A2"],
["weight","/weɪt/","n.","น้ำหนัก","Manage your weight.","A2"],
["welfare","/ˈwel.feər/","n.","สวัสดิภาพ","Promote welfare.","A2"],
// B1 เพิ่ม
["abolish","/əˈbɒl.ɪʃ/","v.","ยกเลิก","Abolish unfair rules.","B1"],
["abstract","/ˈæb.strækt/","adj.","นามธรรม","An abstract idea.","B1"],
["accelerate","/əkˈsel.ər.eɪt/","v.","เร่งความเร็ว","Accelerate learning.","B1"],
["accommodate","/əˈkɒm.ə.deɪt/","v.","รองรับ","Accommodate the needs.","B1"],
["accumulate","/əˈkjuː.mjʊ.leɪt/","v.","สะสม","Accumulate knowledge.","B1"],
["achieve","/əˈtʃiːv/","v.","บรรลุ","Achieve excellence.","B1"],
["acknowledge","/əkˈnɒl.ɪdʒ/","v.","ยอมรับ","Acknowledge the fact.","B1"],
["acquire","/əˈkwaɪər/","v.","ได้มา","Acquire new skills.","B1"],
["allocate","/ˈæl.ə.keɪt/","v.","จัดสรร","Allocate resources.","B1"],
["alter","/ˈɔːl.tər/","v.","เปลี่ยนแปลง","Alter the plan.","B1"],
["ambition","/æmˈbɪʃ.ən/","n.","ความทะเยอทะยาน","She has great ambition.","B1"],
["analyse","/ˈæn.ə.laɪz/","v.","วิเคราะห์","Analyse the data.","B1"],
["anxiety","/æŋˈzaɪ.ɪ.ti/","n.","ความวิตกกังวล","Manage anxiety.","B1"],
["apparent","/əˈpær.ənt/","adj.","ชัดเจน","The problem is apparent.","B1"],
["application","/ˌæp.lɪˈkeɪ.ʃən/","n.","การสมัคร, แอป","Submit the application.","B1"],
["appoint","/əˈpɔɪnt/","v.","แต่งตั้ง","Appoint a leader.","B1"],
["approve","/əˈpruːv/","v.","อนุมัติ","The plan was approved.","B1"],
["arise","/əˈraɪz/","v.","เกิดขึ้น","Problems arise.","B1"],
["attach","/əˈtætʃ/","v.","แนบ","Attach the file.","B1"],
["author","/ˈɔː.θər/","n.","ผู้เขียน","The author of the book.","B1"],
["barrier","/ˈbær.i.ər/","n.","อุปสรรค","Break down barriers.","B1"],
["bias","/ˈbaɪ.əs/","n.","อคติ","Avoid bias.","B1"],
["blame","/bleɪm/","v/n.","กล่าวโทษ","Don't blame others.","B1"],
["calculate","/ˈkæl.kjʊ.leɪt/","v.","คำนวณ","Calculate the cost.","B1"],
["capable","/ˈkeɪ.pə.bəl/","adj.","มีความสามารถ","She is very capable.","B1"],
["category","/ˈkæt.ɪ.ɡər.i/","n.","หมวดหมู่","Which category?","B1"],
["cause","/kɔːz/","n/v.","สาเหตุ","Find the root cause.","B1"],
["clarify","/ˈklær.ɪ.faɪ/","v.","ชี้แจง","Please clarify.","B1"],
["classify","/ˈklæs.ɪ.faɪ/","v.","จำแนกประเภท","Classify the data.","B1"],
["colleague","/ˈkɒl.iːɡ/","n.","เพื่อนร่วมงาน","Ask a colleague.","B1"],
["conclude","/kənˈkluːd/","v.","สรุป","Conclude the report.","B1"],
["conflict","/ˈkɒn.flɪkt/","n/v.","ความขัดแย้ง","Resolve conflict.","B1"],
["contrast","/ˈkɒn.trɑːst/","n/v.","ความแตกต่าง","Contrast the ideas.","B1"],
["cooperate","/kəʊˈɒp.ər.eɪt/","v.","ร่วมมือ","Cooperate with others.","B1"],
["corrupt","/kəˈrʌpt/","adj/v.","ทุจริต","Corrupt officials.","B1"],
["creativity","/ˌkriː.eɪˈtɪv.ɪ.ti/","n.","ความคิดสร้างสรรค์","Foster creativity.","B1"],
["crisis","/ˈkraɪ.sɪs/","n.","วิกฤต","Handle a crisis.","B1"],
["curiosity","/ˌkjʊər.iˈɒs.ɪ.ti/","n.","ความอยากรู้","Curiosity drives learning.","B1"],
["deadline","/ˈded.laɪn/","n.","กำหนดเวลา","Meet the deadline.","B1"],
["debate","/dɪˈbeɪt/","n/v.","โต้เถียง","A productive debate.","B1"],
["decline","/dɪˈklaɪn/","v/n.","ปฏิเสธ, ลดลง","Decline the offer.","B1"],
["dedicate","/ˈded.ɪ.keɪt/","v.","อุทิศ","Dedicate time to study.","B1"],
["demonstrate","/ˈdem.ən.streɪt/","v.","แสดงให้เห็น","Demonstrate the method.","B1"],
["deny","/dɪˈnaɪ/","v.","ปฏิเสธ","Deny the accusation.","B1"],
["depend","/dɪˈpend/","v.","ขึ้นอยู่กับ","It depends on you.","B1"],
["derive","/dɪˈraɪv/","v.","ได้มาจาก","Derive meaning from text.","B1"],
["distinct","/dɪˈstɪŋkt/","adj.","ชัดเจน, แตกต่างชัดเจน","A distinct advantage.","B1"],
["distribute","/dɪˈstrɪb.juːt/","v.","กระจาย","Distribute the materials.","B1"],
["dominant","/ˈdɒm.ɪ.nənt/","adj.","มีอิทธิพลสูงสุด","The dominant theory.","B1"],
["dramatic","/drəˈmæt.ɪk/","adj.","น่าตื่นเต้น, โดดเด่น","A dramatic change.","B1"],
["economy","/ɪˈkɒn.ə.mi/","n.","เศรษฐกิจ","A growing economy.","B1"],
["eliminate","/ɪˈlɪm.ɪ.neɪt/","v.","กำจัด","Eliminate errors.","B1"],
["enhance","/ɪnˈhɑːns/","v.","เพิ่มคุณภาพ","Enhance your skills.","B1"],
["ensure","/ɪnˈʃɔːr/","v.","รับประกัน","Ensure accuracy.","B1"],
["ethical","/ˈeθ.ɪ.kəl/","adj.","มีจริยธรรม","An ethical decision.","B1"],
["except","/ɪkˈsept/","prep/conj.","ยกเว้น","Everyone passed except him.","B1"],
["exclude","/ɪkˈskluːd/","v.","ยกเว้น, ไม่รวม","Exclude irrelevant data.","B1"],
["exhibit","/ɪɡˈzɪb.ɪt/","v/n.","แสดง, นิทรรศการ","Exhibit your work.","B1"],
["extend","/ɪkˈstend/","v.","ขยาย","Extend the deadline.","B1"],
["extensive","/ɪkˈsten.sɪv/","adj.","กว้างขวาง","Extensive research.","B1"],
["external","/ɪkˈstɜː.nəl/","adj.","ภายนอก","External factors.","B1"],
["extreme","/ɪkˈstriːm/","adj.","สุดโต่ง","Extreme conditions.","B1"],
["facilitate","/fəˈsɪl.ɪ.teɪt/","v.","ช่วยให้ง่ายขึ้น","Facilitate learning.","B1"],
["findings","/ˈfaɪn.dɪŋz/","n.","ผลการค้นพบ","Report the findings.","B1"],
["formal","/ˈfɔː.məl/","adj.","เป็นทางการ","A formal report.","B1"],
["generation","/ˌdʒen.əˈreɪ.ʃən/","n.","รุ่น","Generation gap.","B1"],
["gradual","/ˈɡrædʒ.u.əl/","adj.","ค่อยเป็นค่อยไป","A gradual improvement.","B1"],
["grant","/ɡrɑːnt/","v/n.","ให้, ทุน","Grant permission.","B1"],
["harm","/hɑːm/","n/v.","อันตราย","Avoid harm.","B1"],
["hypothesis","/haɪˈpɒθ.ɪ.sɪs/","n.","สมมุติฐาน","Prove the hypothesis.","B1"],
["ideal","/aɪˈdɪəl/","adj/n.","อุดมคติ","An ideal solution.","B1"],
["image","/ˈɪm.ɪdʒ/","n.","ภาพ","A positive image.","B1"],
["income","/ˈɪn.kʌm/","n.","รายได้","Stable income.","B1"],
["increasingly","/ɪnˈkriː.sɪŋ.li/","adv.","มากขึ้นเรื่อยๆ","Increasingly difficult.","B1"],
["independent","/ˌɪn.dɪˈpen.dənt/","adj.","อิสระ","Be independent.","B1"],
["inequality","/ˌɪn.ɪˈkwɒl.ɪ.ti/","n.","ความไม่เท่าเทียม","Fight inequality.","B1"],
["inevitable","/ɪnˈev.ɪ.tə.bəl/","adj.","หลีกเลี่ยงไม่ได้","Change is inevitable.","B1"],
["infrastructure","/ˈɪn.frə.strʌk.tʃər/","n.","โครงสร้างพื้นฐาน","Invest in infrastructure.","B1"],
["initiative","/ɪˈnɪʃ.ə.tɪv/","n.","ความคิดริเริ่ม","Take the initiative.","B1"],
["innovate","/ˈɪn.ə.veɪt/","v.","คิดค้น","Innovate constantly.","B1"],
["insight","/ˈɪn.saɪt/","n.","ความเข้าใจลึกซึ้ง","Gain valuable insights.","B1"],
["inspire","/ɪnˈspaɪər/","v.","สร้างแรงบันดาลใจ","Inspire the team.","B1"],
["institution","/ˌɪn.stɪˈtjuː.ʃən/","n.","สถาบัน","A respected institution.","B1"],
["intend","/ɪnˈtend/","v.","ตั้งใจ","What do you intend?","B1"],
["internal","/ɪnˈtɜː.nəl/","adj.","ภายใน","Internal conflict.","B1"],
["involve","/ɪnˈvɒlv/","v.","เกี่ยวข้อง","Involve the community.","B1"],
["isolate","/ˈaɪ.sə.leɪt/","v.","แยกออก","Isolate the problem.","B1"],
["issue","/ˈɪʃ.uː/","n.","ประเด็น","Address the issue.","B1"],
["legal","/ˈliː.ɡəl/","adj.","ถูกกฎหมาย","Legal rights.","B1"],
["limitation","/ˌlɪm.ɪˈteɪ.ʃən/","n.","ข้อจำกัด","Know your limitations.","B1"],
["link","/lɪŋk/","n/v.","ความเชื่อมโยง","Link the concepts.","B1"],
["logical","/ˈlɒdʒ.ɪ.kəl/","adj.","สมเหตุสมผล","A logical explanation.","B1"],
["long-term","/ˌlɒŋˈtɜːm/","adj.","ระยะยาว","Long-term planning.","B1"],
["major","/ˈmeɪ.dʒər/","adj/n.","สำคัญ, วิชาเอก","A major problem.","B1"],
["maximize","/ˈmæk.sɪ.maɪz/","v.","เพิ่มสูงสุด","Maximize efficiency.","B1"],
["mechanism","/ˈmek.ə.nɪ.zəm/","n.","กลไก","Understand the mechanism.","B1"],
["minor","/ˈmaɪ.nər/","adj.","เล็กน้อย, วิชาโท","A minor issue.","B1"],
["mode","/məʊd/","n.","รูปแบบ","Study mode on.","B1"],
["modify","/ˈmɒd.ɪ.faɪ/","v.","ปรับแก้","Modify the plan.","B1"],
["monitor","/ˈmɒn.ɪ.tər/","v/n.","ติดตาม","Monitor progress.","B1"],
["mutual","/ˈmjuː.tʃu.əl/","adj.","ซึ่งกันและกัน","Mutual respect.","B1"],
["negative","/ˈneɡ.ə.tɪv/","adj.","เชิงลบ","Negative effects.","B1"],
["norm","/nɔːm/","n.","บรรทัดฐาน","Social norms.","B1"],
["notion","/ˈnəʊ.ʃən/","n.","แนวคิด, ความคิด","Reject the notion.","B1"],
["observe","/əbˈzɜːv/","v.","สังเกตการณ์","Observe and learn.","B1"],
["obtain","/əbˈteɪn/","v.","ได้รับ","Obtain permission.","B1"],
["obvious","/ˈɒb.vi.əs/","adj.","ชัดเจน","The answer is obvious.","B1"],
["opportunity","/ˌɒp.əˈtjuː.nɪ.ti/","n.","โอกาส","A great opportunity.","B1"],
["oppose","/əˈpəʊz/","v.","คัดค้าน","Oppose the motion.","B1"],
["outcome","/ˈaʊt.kʌm/","n.","ผลลัพธ์","Achieve the desired outcome.","B1"],
["output","/ˈaʊt.pʊt/","n.","ผลผลิต","Increase output.","B1"],
["overall","/ˌəʊ.vərˈɔːl/","adj/adv.","โดยรวม","Overall performance.","B1"],
["overcome","/ˌəʊ.vəˈkʌm/","v.","เอาชนะ","Overcome failure.","B1"],
["parallel","/ˈpær.ə.lel/","adj/n.","ขนาน, คล้ายกัน","Draw a parallel.","B1"],
["passive","/ˈpæs.ɪv/","adj.","รับ, เฉยเมย","Don't be passive.","B1"],
["perceive","/pəˈsiːv/","v.","มองว่า","How is it perceived?","B1"],
["phase","/feɪz/","n.","ระยะ","The next phase.","B1"],
["policy","/ˈpɒl.ɪ.si/","n.","นโยบาย","Follow the policy.","B1"],
["positive","/ˈpɒz.ɪ.tɪv/","adj.","เชิงบวก","Positive results.","B1"],
["predict","/prɪˈdɪkt/","v.","พยากรณ์","Predict the outcome.","B1"],
["proportion","/prəˈpɔː.ʃən/","n.","สัดส่วน","A high proportion.","B1"],
["pursue","/pəˈsjuː/","v.","ไล่ตาม, มุ่งหน้า","Pursue your passion.","B1"],
["reaction","/riˈæk.ʃən/","n.","ปฏิกิริยา","A strong reaction.","B1"],
["realistic","/ˌrɪə.lˈɪs.tɪk/","adj.","สมจริง","Set realistic goals.","B1"],
["reform","/rɪˈfɔːm/","n/v.","การปฏิรูป","Education reform.","B1"],
["regulate","/ˈreɡ.jʊ.leɪt/","v.","ควบคุม","Regulate the process.","B1"],
["reject","/rɪˈdʒekt/","v.","ปฏิเสธ","Reject the proposal.","B1"],
["relate","/rɪˈleɪt/","v.","เกี่ยวข้อง","Relate ideas to practice.","B1"],
["reliable","/rɪˈlaɪ.ə.bəl/","adj.","น่าเชื่อถือ","A reliable source.","B1"],
["reluctant","/rɪˈlʌk.tənt/","adj.","ไม่เต็มใจ","She was reluctant.","B1"],
["resolve","/rɪˈzɒlv/","v.","แก้ไข","Resolve the conflict.","B1"],
["restrict","/rɪˈstrɪkt/","v.","จำกัด","Restrict access.","B1"],
["role","/rəʊl/","n.","บทบาท","Play an active role.","B1"],
["seek","/siːk/","v.","ค้นหา","Seek advice.","B1"],
["sequence","/ˈsiː.kwəns/","n.","ลำดับ","Follow the sequence.","B1"],
["shift","/ʃɪft/","n/v.","การเปลี่ยน","A major shift.","B1"],
["solution","/səˈluː.ʃən/","n.","ทางออก","Find a solution.","B1"],
["status","/ˈsteɪ.təs/","n.","สถานะ","Current status.","B1"],
["straightforward","/ˌstreɪtˈfɔː.wəd/","adj.","ตรงไปตรงมา","A straightforward answer.","B1"],
["strength","/streŋθ/","n.","จุดแข็ง","Know your strengths.","B1"],
["subsequent","/ˈsʌb.sɪ.kwənt/","adj.","ต่อมา","Subsequent events.","B1"],
["substantial","/səbˈstæn.ʃəl/","adj.","มาก, สำคัญ","A substantial amount.","B1"],
["tackle","/ˈtæk.əl/","v.","จัดการ","Tackle the issue.","B1"],
["target","/ˈtɑː.ɡɪt/","n/v.","เป้าหมาย","Hit the target.","B1"],
["theory","/ˈθɪər.i/","n.","ทฤษฎี","Test the theory.","B1"],
["transform","/trænsˈfɔːm/","v.","เปลี่ยนแปลง","Transform the system.","B1"],
["ultimately","/ˈʌl.tɪ.mɪt.li/","adv.","ในที่สุด","Ultimately, it worked.","B1"],
["underlying","/ˌʌn.dəˈlaɪ.ɪŋ/","adj.","อยู่เบื้องหลัง","The underlying cause.","B1"],
["vary","/ˈveər.i/","v.","แตกต่าง","Results vary.","B1"],
["whereas","/weərˈæz/","conj.","ในขณะที่","She passed, whereas he failed.","B1"],
// B2 เพิ่ม
["abstract","/ˈæb.strækt/","n.","บทคัดย่อ","Write an abstract.","B2"],
["account for","/əˈkaʊnt fɔː/","v.","อธิบาย, คิดเป็น","Account for the difference.","B2"],
["accurate","/ˈæk.jʊ.rət/","adj.","ถูกต้องแม่นยำ","An accurate measurement.","B2"],
["adamant","/ˈæd.ə.mənt/","adj.","ยืนกราน","She was adamant.","B2"],
["aggregate","/ˈæɡ.rɪ.ɡɪt/","n/adj.","รวม","The aggregate score.","B2"],
["allegation","/ˌæl.ɪˈɡeɪ.ʃən/","n.","ข้อกล่าวหา","Deny the allegations.","B2"],
["allocate","/ˈæl.ə.keɪt/","v.","จัดสรร","Allocate the budget.","B2"],
["amend","/əˈmend/","v.","แก้ไข","Amend the law.","B2"],
["ample","/ˈæm.pəl/","adj.","เพียงพอมาก","Ample time given.","B2"],
["articulate","/ɑːˈtɪk.jʊ.lɪt/","adj/v.","พูดได้ชัดเจน","Articulate your views.","B2"],
["assert","/əˈsɜːt/","v.","ยืนยัน","Assert your rights.","B2"],
["assumption","/əˈsʌmp.ʃən/","n.","สมมุติฐาน","Challenge the assumption.","B2"],
["attain","/əˈteɪn/","v.","บรรลุ","Attain a high grade.","B2"],
["authenticate","/ɔːˈθen.tɪ.keɪt/","v.","ตรวจสอบความถูกต้อง","Authenticate the data.","B2"],
["benchmark","/ˈbentʃ.mɑːk/","n.","มาตรฐานอ้างอิง","Set a benchmark.","B2"],
["bias","/ˈbaɪ.əs/","v.","ทำให้มีอคติ","Avoid being biased.","B2"],
["burden","/ˈbɜː.dən/","n.","ภาระ","Share the burden.","B2"],
["clause","/klɔːz/","n.","เงื่อนไข, อนุประโยค","Read every clause.","B2"],
["coherent","/kəʊˈhɪər.ənt/","adj.","สอดคล้อง","A coherent plan.","B2"],
["collaborate","/kəˈlæb.ər.eɪt/","v.","ร่วมมือ","Collaborate effectively.","B2"],
["compelling","/kəmˈpel.ɪŋ/","adj.","น่าสนใจมาก","A compelling argument.","B2"],
["complex","/ˈkɒm.pleks/","adj.","ซับซ้อน","A complex system.","B2"],
["comprehensive","/ˌkɒm.prɪˈhen.sɪv/","adj.","ครอบคลุม","A comprehensive guide.","B2"],
["concede","/kənˈsiːd/","v.","ยอมรับ","Concede defeat.","B2"],
["consistent","/kənˈsɪs.tənt/","adj.","สม่ำเสมอ","Be consistent.","B2"],
["constitute","/ˈkɒn.stɪ.tjuːt/","v.","ประกอบด้วย","What constitutes success?","B2"],
["constraint","/kənˈstreɪnt/","n.","ข้อจำกัด","Work within constraints.","B2"],
["contemplate","/ˈkɒn.tɪm.pleɪt/","v.","ไตร่ตรอง","Contemplate the decision.","B2"],
["contradict","/ˌkɒn.trəˈdɪkt/","v.","ขัดแย้ง","Don't contradict the evidence.","B2"],
["contrast","/ˈkɒn.trɑːst/","n/v.","เปรียบเทียบความต่าง","In contrast to before.","B2"],
["conviction","/kənˈvɪk.ʃən/","n.","ความเชื่อมั่น","Speak with conviction.","B2"],
["critique","/krɪˈtiːk/","n/v.","วิจารณ์","Write a critique.","B2"],
["data-driven","/ˈdeɪ.tə ˌdrɪv.ən/","adj.","อาศัยข้อมูล","A data-driven approach.","B2"],
["decisive","/dɪˈsaɪ.sɪv/","adj.","เด็ดขาด","Be decisive.","B2"],
["deduce","/dɪˈdjuːs/","v.","อนุมาน","Deduce the meaning.","B2"],
["deficient","/dɪˈfɪʃ.ənt/","adj.","ขาด","Deficient in skills.","B2"],
["derive","/dɪˈraɪv/","v.","มาจาก","Derive a conclusion.","B2"],
["differentiate","/ˌdɪf.ərˈen.ʃi.eɪt/","v.","แยกแยะ","Differentiate clearly.","B2"],
["diminish","/dɪˈmɪn.ɪʃ/","v.","ลดลง","Diminish over time.","B2"],
["discourse","/ˈdɪs.kɔːs/","n.","วาทกรรม","Critical discourse.","B2"],
["distort","/dɪˈstɔːt/","v.","บิดเบือน","Distort the facts.","B2"],
["dominant","/ˈdɒm.ɪ.nənt/","adj.","มีอิทธิพล","The dominant group.","B2"],
["empirical","/emˈpɪr.ɪ.kəl/","adj.","อาศัยประสบการณ์จริง","Empirical evidence.","B2"],
["enforce","/ɪnˈfɔːs/","v.","บังคับใช้","Enforce the law.","B2"],
["equate","/ɪˈkweɪt/","v.","เทียบเท่า","Equate effort with result.","B2"],
["evaluate","/ɪˈvæl.ju.eɪt/","v.","ประเมิน","Evaluate the options.","B2"],
["explicit","/ɪkˈsplɪs.ɪt/","adj.","ชัดเจนตรงไปตรงมา","Be explicit.","B2"],
["exploit","/ɪkˈsplɔɪt/","v.","ใช้ประโยชน์, ล่วงละเมิด","Exploit opportunities.","B2"],
["extensive","/ɪkˈsten.sɪv/","adj.","ครอบคลุมกว้าง","Extensive knowledge.","B2"],
["facilitate","/fəˈsɪl.ɪ.teɪt/","v.","อำนวยความสะดวก","Facilitate discussion.","B2"],
["fallacy","/ˈfæl.ə.si/","n.","ความเข้าใจผิด","A logical fallacy.","B2"],
["feasible","/ˈfiː.zɪ.bəl/","adj.","เป็นไปได้","Is it feasible?","B2"],
["formulate","/ˈfɔː.mjʊ.leɪt/","v.","กำหนด","Formulate a strategy.","B2"],
["framework","/ˈfreɪm.wɜːk/","n.","กรอบแนวคิด","Build a framework.","B2"],
["fundamental","/ˌfʌn.dəˈmen.təl/","adj.","พื้นฐาน","Fundamental skills.","B2"],
["generalize","/ˈdʒen.ər.ə.laɪz/","v.","ทำให้เป็นนัยทั่วไป","Don't overgeneralize.","B2"],
["generate","/ˈdʒen.ər.eɪt/","v.","สร้าง","Generate ideas.","B2"],
["hierarchy","/ˈhaɪ.ər.ɑː.ki/","n.","ลำดับชั้น","A strict hierarchy.","B2"],
["hypothesis","/haɪˈpɒθ.ɪ.sɪs/","n.","สมมุติฐาน","Develop a hypothesis.","B2"],
["implication","/ˌɪm.plɪˈkeɪ.ʃən/","n.","ผลที่ตามมา","Consider the implications.","B2"],
["inconsistent","/ˌɪn.kənˈsɪs.tənt/","adj.","ไม่สม่ำเสมอ","Inconsistent results.","B2"],
["independence","/ˌɪn.dɪˈpen.dəns/","n.","ความเป็นอิสระ","Value independence.","B2"],
["induce","/ɪnˈdjuːs/","v.","เหนี่ยวนำ","Induce a response.","B2"],
["inference","/ˈɪn.fər.əns/","n.","การอนุมาน","Make an inference.","B2"],
["infrastructure","/ˈɪn.frə.strʌk.tʃər/","n.","โครงสร้างพื้นฐาน","Upgrade infrastructure.","B2"],
["integral","/ˈɪn.tɪ.ɡrəl/","adj.","จำเป็น, สำคัญ","An integral part.","B2"],
["investigate","/ɪnˈves.tɪ.ɡeɪt/","v.","สืบสวน","Thoroughly investigate.","B2"],
["justify","/ˈdʒʌs.tɪ.faɪ/","v.","แสดงเหตุผล","Justify the decision.","B2"],
["legitimate","/lɪˈdʒɪt.ɪ.mɪt/","adj.","ถูกกฎหมาย, สมเหตุสมผล","A legitimate concern.","B2"],
["marginal","/ˈmɑː.dʒɪ.nəl/","adj.","เล็กน้อย","A marginal gain.","B2"],
["mislead","/ˌmɪsˈliːd/","v.","ทำให้เข้าใจผิด","Don't mislead others.","B2"],
["monitor","/ˈmɒn.ɪ.tər/","v.","ติดตาม","Monitor results closely.","B2"],
["negligible","/ˈneɡ.lɪ.dʒɪ.bəl/","adj.","ไม่สำคัญ","A negligible difference.","B2"],
["nonetheless","/ˌnʌn.ðəˈles/","adv.","อย่างไรก็ตาม","Nonetheless, try again.","B2"],
["notion","/ˈnəʊ.ʃən/","n.","ความคิด, ความเชื่อ","A common notion.","B2"],
["objective","/əbˈdʒek.tɪv/","adj/n.","เป็นกลาง, เป้าหมาย","An objective view.","B2"],
["omit","/əˈmɪt/","v.","ละเว้น","Omit irrelevant details.","B2"],
["paradigm","/ˈpær.ə.daɪm/","n.","กระบวนทัศน์","A paradigm shift.","B2"],
["parameter","/pəˈræm.ɪ.tər/","n.","ตัวแปร, ขอบเขต","Set the parameters.","B2"],
["preliminary","/prɪˈlɪm.ɪ.nər.i/","adj.","เบื้องต้น","Preliminary results.","B2"],
["presume","/prɪˈzjuːm/","v.","สันนิษฐาน","Don't presume.","B2"],
["prior","/ˈpraɪər/","adj.","ก่อนหน้า","Prior experience required.","B2"],
["proposition","/ˌprɒp.əˈzɪʃ.ən/","n.","ข้อเสนอ","A logical proposition.","B2"],
["rationale","/ˌræʃ.əˈnɑːl/","n.","เหตุผล","State the rationale.","B2"],
["refine","/rɪˈfaɪn/","v.","ปรับปรุงให้ดี","Refine the argument.","B2"],
["relevant","/ˈrel.ɪ.vənt/","adj.","เกี่ยวข้อง","Keep it relevant.","B2"],
["rely","/rɪˈlaɪ/","v.","ไว้วางใจ, พึ่ง","Rely on facts.","B2"],
["remote","/rɪˈməʊt/","adj.","ห่างไกล","A remote possibility.","B2"],
["rigorous","/ˈrɪɡ.ər.əs/","adj.","เข้มงวด","Rigorous analysis.","B2"],
["sequence","/ˈsiː.kwəns/","n.","ลำดับเหตุการณ์","Logical sequence.","B2"],
["simulate","/ˈsɪm.jʊ.leɪt/","v.","จำลอง","Simulate conditions.","B2"],
["specify","/ˈspes.ɪ.faɪ/","v.","ระบุ","Specify the details.","B2"],
["sphere","/sfɪər/","n.","ขอบเขต, วงการ","The public sphere.","B2"],
["straightforward","/ˌstreɪtˈfɔː.wəd/","adj.","ตรงไปตรงมา","A straightforward task.","B2"],
["subsequent","/ˈsʌb.sɪ.kwənt/","adj.","ต่อมา","Subsequent chapters.","B2"],
["substantial","/səbˈstæn.ʃəl/","adj.","สำคัญ, มาก","Substantial progress.","B2"],
["supplement","/ˈsʌp.lɪ.mənt/","v/n.","เสริม","Supplement your diet.","B2"],
["terminology","/ˌtɜː.mɪˈnɒl.ə.dʒi/","n.","คำศัพท์เฉพาะ","Technical terminology.","B2"],
["threshold","/ˈθreʃ.həʊld/","n.","ขีดจำกัด","Exceed the threshold.","B2"],
["transition","/trænsˈɪʃ.ən/","n.","การเปลี่ยนผ่าน","A smooth transition.","B2"],
["transparent","/trænsˈpær.ənt/","adj.","โปร่งใส","Be transparent.","B2"],
["undermine","/ˌʌn.dəˈmaɪn/","v.","บั่นทอน","Undermine confidence.","B2"],
["validate","/ˈvæl.ɪ.deɪt/","v.","ตรวจสอบ","Validate the data.","B2"],
["variable","/ˈveər.i.ə.bəl/","n/adj.","ตัวแปร","Identify the variable.","B2"],
["verify","/ˈver.ɪ.faɪ/","v.","ยืนยัน","Verify the information.","B2"],
["viable","/ˈvaɪ.ə.bəl/","adj.","เป็นไปได้","A viable option.","B2"],
["widespread","/ˈwaɪd.spred/","adj.","แพร่หลาย","Widespread adoption.","B2"],
];
// merge into VOCAB
VOCAB.push(...VOCAB2);
