// VocabUp Enhanced Data with SRS, Synonyms, Collocations
// Format: [word, phonetic, pos, thai, example, level, synonyms, antonyms, collocations]

const VOCAB = [
// A1 — Basic
["about","prep/adv.","เกี่ยว, ประมาณ","Tell me about yourself.","A1","concerning|regarding","—","talk about|think about"],
["above","prep/adj.","เหนือ","The sky is above us.","A1","over|higher than","below|under","above all"],
["after","prep/conj.","หลัง","See you after class.","A1","following|later","before","after all"],
["again","adv.","อีกครั้ง","Try again tomorrow.","A1","once more|repeatedly","—","again and again"],
["all","det/pron.","ทั้งหมด","That's all folks.","A1","everything|whole","none|nothing","all day|all night"],
["also","adv.","เช่นกัน","I want to go also.","A1","too|as well","—","—"],
["an","art.","อัน","I saw an elephant.","A1","a|one","—","—"],
["and","conj.","และ","Tea and coffee.","A1","plus|with","—","—"],
["another","det/pron.","อีกอัน","Want another drink?","A1","different|other","same","one another"],
["answer","n/v.","คำตอบ, ตอบ","Answer the question.","A1","reply|respond","question","answer back|answer for"],
// A1 ต่อ (สุ่มเลือก)
["are","v.","เป็น(พูด/เขา)","You are clever.","A1","—","—","—"],
["area","n.","พื้นที่","A large area.","A1","region|zone","—","residential area|business area"],
["as","conj/prep.","ขณะที่, เช่น","As we speak...","A1","while|like","—","as if|as soon as"],
["ask","v.","ถาม","Ask for help.","A1","question|inquire","answer","ask about|ask for"],
["at","prep.","ที่","See you at noon.","A1","in|by","—","at home|at work|at first"],
["away","adv/adj.","ไกล","Go away!","A1","distant|far","near|close","right away|far away"],
["baby","n.","เด็กทารก","A newborn baby.","A1","infant|newborn","—","baby food|baby care"],
["back","n/adv.","หลัง, กลับ","Come back soon.","A1","rear|behind","front|forward","come back|go back|back pain"],
["bad","adj.","ไม่ดี","Bad weather.","A1","poor|negative|evil","good|nice","too bad|bad luck|bad habit"],
["bag","n.","กระเป๋า","Put it in the bag.","A1","sack|container","—","paper bag|shopping bag|handbag"],
["ball","n.","ลูกบอล","Kick the ball.","A1","sphere|orb","—","football|baseball|basketball"],
["bank","n.","ธนาคาร, ริมฝั่ง","Money bank.","A1","financial institution|riverbank","—","bank account|bank loan|river bank"],
["bar","n.","บาร์, ก้าน","Iron bar.","A1","tavern|rod","—","bar exam|bar tender|chocolate bar"],
["base","n.","ฐาน","The base of the tree.","A1","foundation|bottom","top|summit","military base|base camp"],
["be","v.","เป็น","I am happy.","A1","exist|live","—","—"],
["because","conj.","เพราะ","Because I said so.","A1","since|as","—","because of"],
["become","v.","เป็นไป","What will you become?","A1","turn into|grow","—","become famous|become clear"],
["been","v.","ได้","Have you been here?","A1","—","—","—"],
["before","prep/adv.","ก่อน","Before noon.","A1","prior to|earlier","after|later","before long|before now"],
["began","v.","เริ่ม(past)","I began work.","A1","started|commenced","ended|finished","—"],
["begin","v.","เริ่ม","Let's begin now.","A1","start|commence","end|finish","begin with|from the beginning"],
["being","v.","เป็น(ต่อ)","Being here is great.","A1","existing|living","—","—"],
["believe","v.","เชื่อ","I believe you.","A1","trust|accept","disbelieve|doubt","believe in|make believe"],
["below","prep/adv.","ใต้","Below the surface.","A1","under|beneath","above|over","below zero"],
["best","adj/adv.","ดีที่สุด","The best day.","A1","finest|greatest","worst|poorest","best friend|best seller"],
["better","adj/adv.","ดีกว่า","Feel better now.","A1","superior|improved","worse|inferior","better than|get better"],
["between","prep.","ระหว่าง","Between you and me.","A1","among|in the middle of","—","between them"],
["big","adj.","ใหญ่","A big house.","A1","large|great","small|little|tiny","big deal|big picture"],
["black","adj/n.","สีดำ","Black cat.","A1","dark|ebony","white|light","pitch black"],
["blue","adj/n.","สีน้ำเงิน","Blue sky.","A1","navy|azure","—","royal blue|light blue"],
["body","n.","ร่างกาย","Human body.","A1","physical form|flesh","—","body temperature|body language"],
["book","n/v.","หนังสือ, จอง","Read a book.","A1","novel|text","—","bookshelf|bookmark|book club"],
["both","det/pron.","ทั้งคู่","Both are correct.","A1","the two|each","neither|none","both of"],
["bottom","n/adj.","ก้น, ล่าง","At the bottom.","A1","base|end|foot","top|surface|upper","bottom line"],
["box","n.","กล่อง","A cardboard box.","A1","container|case","—","box office|post box"],
["boy","n.","เด็กชาย","A young boy.","A1","male child|lad","girl","boy band|boyfriend"],
["branch","n.","กิ่ง, สาขา","Tree branch.","A1","limb|twig|division","—","tree branch|bank branch"],
["break","v/n.","หัก, พัก","Take a break.","A1","snap|crack","fix|repair|mend","break down|break up|coffee break"],
["bring","v.","นำมา","Bring a friend.","A1","carry|transport","take|remove","bring back|bring up"],
["brown","adj/n.","สีน้ำตาล","Brown shoes.","A1","tan|beige","—","light brown|dark brown"],
["build","v.","สร้าง","Build a house.","A1","construct|make","demolish|destroy|tear down","build up"],
["bus","n.","รถบัส","Catch the bus.","A1","coach|vehicle","—","school bus|bus stop"],
["business","n.","ธุรกิจ","Run a business.","A1","company|trade|commerce","—","business card|business deal"],
["but","conj.","แต่","I like it but...","A1","however|yet","—","—"],
["buy","v.","ซื้อ","Buy a car.","A1","purchase|acquire","sell|vend","buy out|buy over"],
["by","prep.","โดย","By train.","A1","via|through","—","by the way|by chance|by hand"],
["call","v/n.","เรียก","Call me later.","A1","phone|summon","answer|—","call back|call for|call out"],
["can","v.","สามารถ","I can swim.","A1","able to|may","cannot|can't","—"],
["car","n.","รถยนต์","Drive a car.","A1","automobile|vehicle","—","sports car|car park"],
["care","v/n.","ใจใส่, ดูแล","Care about me.","A1","concern|look after","ignore|neglect","care for|take care"],
["case","n.","กรณี, กล่อง","In that case.","A1","situation|instance|container","—","in case|in any case"],
["catch","v.","จับ","Catch the ball.","A1","seize|grab","drop|release|let go","catch up|catch cold"],
["cause","v/n.","ทำให้เกิด, สาเหตุ","What caused it?","A1","make|create","—","root cause|cause of death"],
["center","n.","ศูนย์กลาง","City center.","A1","middle|nucleus","edge|periphery|circumference","shopping center|city center"],
["century","n.","ศตวรรษ","21st century.","A1","hundred years|era","—","—"],
["certain","adj.","แน่นอน","I'm certain now.","A1","sure|definite|fixed","uncertain|unsure|doubtful","for certain|make certain"],
["chair","n.","เก้าอี้","Sit on a chair.","A1","seat|stool","—","armchair|chair lift"],
["change","v/n.","เปลี่ยน","Change clothes.","A1","alter|modify","keep|maintain","change of mind|spare change"],
["character","n.","ลักษณะ, ตัวละคร","Good character.","A1","trait|personality|person","—","main character|character traits"],
["charge","v/n.","เรียกเก็บ, อาชิ","Charge money.","A1","cost|price|accuse","—","charge card|free of charge"],
["check","v/n.","ตรวจสอบ","Check again.","A1","verify|examine|inspect","—","check up|check in|check out"],
["cheese","n.","ชีส","Cheese pizza.","A1","dairy product","—","cheddar cheese|cheese cake"],
["choice","n.","ตัวเลือก","Your choice.","A1","option|selection|alternative","—","make a choice|of choice"],
["choose","v.","เลือก","Choose wisely.","A1","select|pick","reject|refuse|decline","choose from"],
["church","n.","โบสถ์","Visit a church.","A1","temple|place of worship","—","church bell|church service"],
["city","n.","เมือง","Big city.","A1","metropolis|urban area","village|countryside","city center|city life"],
["claim","v/n.","อ้าง","Claim victory.","A1","assert|state|declare","deny|refute","claim that|make a claim"],
["class","n.","ชั้นเรียน","In class.","A1","classroom|course|group","—","first class|business class|classroom"],
["clean","adj/v.","สะอาด","Clean room.","A1","neat|tidy|pure","dirty|messy|unclean","clean up|squeaky clean"],
["clear","adj/v.","ชัดเจน","Clear sky.","A1","obvious|transparent|bright","unclear|vague|cloudy","crystal clear|make clear"],
["climb","v.","ปีน","Climb the mountain.","A1","scale|ascend","descend|go down","climb up|social climber"],
["clock","n.","นาฬิกา","Check the clock.","A1","timepiece|watch","—","alarm clock|biological clock"],
["close","v/adj.","ปิด, ใกล้","Close the door.","A1","shut|seal","open|unlock|unlock","close by|close to"],
["clothes","n.","เสื้อผ้า","Wash clothes.","A1","garments|attire|outfit","—","clothes line|clothes hanger"],
["cloud","n.","เมฆ","White cloud.","A1","mist|vapor","—","cloud nine|cloud computing"],
["coach","n/v.","โค้ช, ฝึก","Hire a coach.","A1","trainer|instructor|bus","—","life coach|head coach"],
["coast","n.","ชายฝั่ง","Beach coast.","A1","shore|seaside|seaboard","inland|interior","—"],
["coat","n.","เสื้อโค้ท","Wear a coat.","A1","jacket|garment|layer","—","winter coat|lab coat|coat hanger"],
["code","n.","รหัส","Secret code.","A1","cipher|program|rule","—","QR code|dress code|postal code"],
["coffee","n.","กาแฟ","Hot coffee.","A1","beverage|brew","—","black coffee|coffee shop"],
["cold","adj/n.","หนาว","Cold weather.","A1","chilly|freezing|cool","hot|warm","catch a cold|cold shoulder"],
["college","n.","วิทยาลัย","Go to college.","A1","university|institution","—","college student|college campus"],
["color","n.","สี","What color?","A1","hue|shade|pigment","—","primary color|color blind"],
["come","v.","มา","Come here!","A1","arrive|approach|go","leave|go away|depart","come back|come true|come in"],
["comic","n/adj.","การ์ตูน, ตลก","Read a comic.","A1","cartoon|funny|amusing","tragic|serious","comic book|comic relief"],
["common","adj.","ธรรมชาติ","Common sense.","A1","usual|ordinary|frequent","rare|uncommon|unusual","common ground|common law"],
["company","n.","บริษัท","Work for a company.","A1","firm|business|corporation","—","in company|good company"],
["computer","n.","คอมพิวเตอร์","Use computer.","A1","PC|machine|device","—","desktop computer|laptop computer"],
["concern","v/n.","เป็นห่วง","Don't concern yourself.","A1","worry|care|relate","—","matter of concern|as far as I'm concerned"],
["condition","n.","เงื่อนไข","Poor condition.","A1","situation|requirement|state","—","weather condition|living condition"],
["conference","n.","การประชุม","Attend conference.","A1","meeting|seminar","—","video conference|press conference"],
["confirm","v.","ยืนยัน","Please confirm.","A1","verify|affirm|assure","deny|refute|contradict","confirm receipt|confirmation email"],
["connect","v.","เชื่อมต่อ","Connect the dots.","A1","link|join|attach","disconnect|separate|detach","connect to|stay connected"],
["consider","v.","พิจารณา","Consider this.","A1","think about|contemplate|regard","ignore|disregard|overlook","consider as|all things considered"],
["contain","v.","บรรจุ","Does it contain...?","A1","hold|include|comprise","exclude|omit","contain itself"],
["contact","n/v.","ติดต่อ","Contact me.","A1","reach|communicate|connection","—","contact lens|get in contact"],
["content","n.","เนื้อหา","Table of contents.","A1","subject matter|material|information","—","content page|user-generated content"],
["contest","n/v.","การแข่งขัน, แข่ง","Enter a contest.","A1","competition|competition","accept|concede","beauty contest|spelling contest"],
["continue","v.","ต่อ","Continue reading.","A1","go on|proceed|persist","stop|cease|halt","continue with|continue on"],
["control","v/n.","ควบคุม","Take control.","A1","manage|regulate|dominate","lose control|give control","remote control|birth control"],
["conversation","n.","การสนทนา","Nice conversation.","A1","discussion|dialogue|chat","—","casual conversation|start a conversation"],
["cook","v/n.","ปรุง, พ่อครัว","Cook dinner.","A1","prepare|chef|prepare food","—","head cook|cook book"],
["cool","adj.","เย็น","Cool breeze.","A1","cold|chilly|calm","hot|warm|excited","stay cool"],
["corner","n.","มุม","Corner store.","A1","angle|intersection|area","—","turn the corner|corner shop"],
["correct","adj/v.","ถูก, แก้ไข","Correct answer.","A1","right|accurate|true","incorrect|wrong|inaccurate","politically correct|correct me if I'm wrong"],
["cost","v/n.","ราคา, ราคา","How much does it cost?","A1","price|expense|charge","—","cost of living"],
["country","n.","ประเทศ","My country.","A1","nation|land|state","city|town|urban area","developing country|home country"],
["couple","n.","คู่","A couple of days.","A1","pair|two|duo","single|individual","a couple of|young couple"],
["course","n.","หลักสูตร","Take a course.","A1","class|curriculum|direction","—","of course|college course"],
["court","n.","ศาล, สนาม","In court.","A1","tribunal|playing area|royal residence","—","tennis court|court case"],
["cousin","n.","ลูกพี่ลูกน้อง","My cousin.","A1","relative|family member","—","first cousin|second cousin"],
["cover","v/n.","ปกคลุม","Cover the pot.","A1","conceal|protect|include","uncover|expose|reveal","cover up|undercover|cover letter"],
["cow","n.","วัว","A dairy cow.","A1","cattle|bovine","—","cow bell|sacred cow"],
["crazy","adj.","บ้า","Crazy idea.","A1","insane|mad|wild","sane|rational|sensible","go crazy|drive crazy"],
["cream","n.","ครีม","Cream cheese.","A1","dairy product|cosmetic","—","whipped cream|cream cheese"],
["credit","n.","เครดิต","Get credit.","A1","acknowledgment|loan|reputation","—","credit card|tax credit"],
["crew","n.","ทีม","Film crew.","A1","team|group|staff","—","flight crew|ground crew"],
["crime","n.","อาชญากรรม","Report a crime.","A1","illegal act|offense|felony","—","crime scene|crime wave"],
["crisis","n.","วิกฤต","Financial crisis.","A1","emergency|critical moment","stability|calm","midlife crisis|identity crisis"],
["critical","adj.","วิจารณ์","Critical thinking.","A1","crucial|analytical|negative","non-critical|approving|positive","critical period|critical condition"],
["crop","n/v.","พืช, ตัดสั้น","Crop failure.","A1","harvest|harvest|plants","—","cash crop|crop up"],
["cross","v/n.","ข้าม","Cross the street.","A1","traverse|go across|intersect","—","cross examination|cross roads"],
["crowd","n.","ฝูงชน","Large crowd.","A1","group|mass|throng","—","crowd control|crowd sourcing"],
["crown","n.","มงกุฎ","Royal crown.","A1","headpiece|top|sovereign","—","tooth crown|crown jewels"],
["cry","v/n.","ร้อง","Don't cry.","A1","weep|shed tears|shout","laugh|smile","cry out|far cry"],
["crystal","n.","คริสตัล","Crystal clear.","A1","mineral|glass|transparent","opaque","crystal ball"],
["culture","n.","วัฒนธรรม","Japanese culture.","A1","civilization|tradition|refinement","—","pop culture|cultural exchange"],
["cup","n.","ถ้วย","A cup of tea.","A1","vessel|mug|trophy","—","coffee cup|measuring cup"],
["curious","adj.","อยากรู้","Curious mind.","A1","inquisitive|interested|strange","uninterested|indifferent|apathetic","curious about"],
["current","adj/n.","ปัจจุบัน, กระแส","Current events.","A1","present|existing|flow","past|previous|future","electric current|current status"],
["curve","n/v.","โค้ง","Road curve.","A1","bend|arc|bow","straight|line","learning curve|curve ball"],
["custom","n/adj.","ประเพณี, แบบสั่ง","Follow custom.","A1","tradition|habit|practice","—","customs officer|custom-made"],
["cut","v/n.","ตัด","Cut the paper.","A1","slice|sever|trim","join|connect|mend","cut off|cut down|cut out"],
["cycle","n/v.","วัฏจักร, ปั่นจักรยาน","Life cycle.","A1","series|pattern|bicycle","—","water cycle|menstrual cycle"],
];

// Add 100+ more words for A2, B1, B2, C1...
// Due to token limits, I'll add the most common exam words

const VOCAB_PART2 = [
// Key A2 exam words
["damage","v/n.","ทำให้เสียหาย","Water damage.","A2","harm|injure|destruction","repair|fix|restore","cause damage|structural damage"],
["danger","n.","อันตราย","In danger.","A2","risk|hazard|peril","safety|security","in danger|danger zone"],
["dangerous","adj.","อันตรายต่อ","Dangerous animal.","A2","hazardous|risky|harmful","safe|secure|harmless","dangerous to|potentially dangerous"],
["dark","adj.","มืด","Dark room.","A2","black|dim|gloomy","light|bright|clear","dark side|dark matter|dark web"],
["data","n.","ข้อมูล","Analyze data.","A2","information|statistics|facts","—","raw data|big data"],
["date","n/v.","วันที่, นัดหมาย","What's the date?","A2","calendar day|romantic meeting","—","due date|expiration date|go on a date"],
["day","n.","วัน","Nice day.","A2","24 hours|daytime","night|evening","day after day|day care|holiday"],
["dead","adj.","ตาย","Dead battery.","A2","deceased|non-living|lifeless","alive|living|active","dead end|dead serious"],
["deal","v/n.","ข้อตกลง, จัดการ","Make a deal.","A2","agreement|transaction|handle","—","big deal|raw deal|good deal"],
["death","n.","ความตาย","Fear of death.","A2","demise|dying|end","life|birth|beginning","death penalty|sudden death"],
["debate","v/n.","โต้เถียง","Heated debate.","A2","discussion|argument|dispute","agreement|consensus","debate about|heat of the debate"],
["debt","n.","หนี้สิน","Pay the debt.","A2","obligation|loan|liability","credit|asset","national debt|foreign debt"],
["decade","n.","ทศวรรษ","Two decades ago.","A2","ten years|period","—","—"],
["decide","v.","ตัดสินใจ","Decide now.","A2","choose|determine|conclude","undecided|hesitate","decide on|decide against"],
["decision","n.","การตัดสินใจ","Final decision.","A2","choice|determination|judgment","—","make a decision|decision making"],
["deep","adj.","ลึก","Deep water.","A2","profound|intense|far down","shallow|superficial|light","deep breath|deep meaning"],
["defend","v.","ป้องกัน","Defend yourself.","A2","protect|guard|justify","attack|assault|accuse","defend against|self-defense"],
["degree","n.","องศา, ปริญญา","90 degrees.","A2","temperature unit|academic qualification","—","college degree|to some degree"],
["delay","n/v.","ล่าช้า","Unexpected delay.","A2","postpone|hold up|wait","rush|hurry|expedite","without delay|flight delay"],
["delete","v.","ลบ","Delete the file.","A2","remove|erase|wipe out","save|keep|restore","delete button|delete key"],
["deliver","v.","ส่ง, บอก","Deliver the package.","A2","bring|provide|give","collect|receive|take","deliver on|home delivery"],
["demand","v/n.","เรียกร้อง","High demand.","A2","require|request|claim","supply|offer|give","meet demand|in demand"],
["democratic","adj.","ประชาธิปไตย","Democratic system.","A2","representative|egalitarian","authoritarian|dictatorial|absolute","democratic election|democratic process"],
["demonstrate","v.","แสดง, ประท้วง","Demonstrate skill.","A2","show|prove|illustrate","hide|conceal|obscure","demonstrate against|demonstration"],
["deny","v.","ปฏิเสธ","Deny the claim.","A2","reject|refuse|contradict","accept|admit|confirm","deny access|deny that"],
["depart","v.","ออกเดินทาง","Depart tomorrow.","A2","leave|go|set off","arrive|stay|remain","depart from|point of departure"],
["department","n.","แผนก","HR department.","A2","division|section|ministry","—","police department|department store"],
["depend","v.","ขึ้นอยู่กับ","It depends on...","A2","rely on|count on|be contingent","independent|stand alone","depend on|dependent on"],
["depression","n.","ภาวะซึมเศร้า","Economic depression.","A2","sadness|recession|downturn","joy|happiness|boom","clinical depression|great depression"],
["deprive","v.","ปล่อยให้ขาด","Deprive of rights.","A2","deny|withhold|rob","give|provide|grant","deprive of|deprived child"],
["depth","n.","ความลึก","Ocean depth.","A2","deepness|extent|profundity","surface|shallowness","in depth|depth of knowledge"],
["derive","v.","ได้มา","Derive pleasure.","A2","obtain|get|stem from","—","derive from|derived word"],
["describe","v.","บรรยาย","Describe the scene.","A2","depict|portray|explain","—","describe as|hard to describe"],
["description","n.","การบรรยาย","Job description.","A2","account|depiction|explanation","—","accurate description|product description"],
["desert","n/v.","ทะเลทราย, ทิ้ง","Sahara desert.","A2","arid region|abandon|barren land","—","desert island|desert heat"],
["deserve","v.","สมควร","You deserve it.","A2","merit|earn|be worthy of","—","deserve better|well deserved"],
["design","n/v.","ออกแบบ","Web design.","A2","plan|create|intend","—","graphic design|design pattern"],
["desire","n/v.","ปรารถนา","Strong desire.","A2","wish|want|crave","aversion|disgust|dislike","desire for|burning desire"],
["desk","n.","โต๊ะ","Work at a desk.","A2","table|furniture|counter","—","office desk|reception desk"],
["despair","n/v.","สิ้นหวัง","Lose despair.","A2","hopelessness|anguish|desperation","hope|optimism|faith","in despair|despair of"],
["desperate","adj.","สิ้นหวัง","Desperate situation.","A2","hopeless|urgent|frantic","hopeful|calm|composed","desperate for|desperate times"],
["despite","prep.","แม้จะ","Despite the rain.","A2","notwithstanding|in spite of|although","because of|due to","despite that|despite all odds"],
["destroy","v.","ทำลาย","Destroy evidence.","A2","demolish|ruin|wreck","build|create|construct","destroy oneself|wholesale destruction"],
["detail","n.","รายละเอียด","Every detail.","A2","particular|element|specification","overview|general","in detail|go into detail"],
["detect","v.","สังเกต","Detect lies.","A2","discover|notice|identify","miss|overlook|ignore","difficult to detect|early detection"],
["determination","n.","ความมุ่งมั่น","Show determination.","A2","resolve|willpower|persistence","hesitation|doubt|apathy","with determination|show determination"],
["determine","v.","กำหนด","Determine the truth.","A2","decide|establish|figure out","—","determined by|determine factors"],
["develop","v.","พัฒนา","Develop skills.","A2","grow|advance|create","decline|regress|shrink","develop into|under development"],
["device","n.","อุปกรณ์","Electronic device.","A2","apparatus|gadget|tool","—","mobile device|smart device"],
["devoted","adj.","อุทิศ","Devoted fan.","A2","dedicated|loyal|faithful","disloyal|unfaithful|uncommitted","devoted to|devoted follower"],
["diamond","n.","เพชร","Diamond ring.","A2","gem|precious stone","—","diamond shaped|rough diamond"],
["diary","n.","บันทึกประจำวัน","Keep a diary.","A2","journal|log|record","—","diary entry|keep a diary"],
["dictionary","n.","พจนานุกรม","Look in dictionary.","A2","reference book|lexicon","—","English dictionary|online dictionary"],
["did","v.","ทำ(อดีต)","What did you do?","A2","—","—","—"],
["die","v.","ตาย","Plants die.","A2","pass away|perish|cease","live|be born|survive","die of|die from|die out"],
["diet","n.","อาหารควบคุม","Balanced diet.","A2","nutrition plan|what one eats","—","diet plan|put on a diet"],
["difference","n.","ความแตกต่าง","Age difference.","A2","distinction|variation|disparity","similarity|likeness|uniformity","make a difference|difference of opinion"],
["different","adj.","แตกต่าง","Different colors.","A2","distinct|unlike|various","same|similar|identical","different from|quite different"],
["difficult","adj.","ยาก","Difficult task.","A2","hard|challenging|complicated","easy|simple|uncomplicated","find difficult|difficult time"],
["dig","v.","ขุด","Dig a hole.","A2","excavate|burrow|search","—","dig up|dig deep"],
["digital","adj.","ดิจิทัล","Digital camera.","A2","electronic|computer-based","analog|physical|traditional","digital media|digital age"],
["dignity","n.","尊ศักดิ์","Maintain dignity.","A2","honor|self-respect|nobility","shame|humiliation|degradation","human dignity|with dignity"],
["dinner","n.","เย็น","Eat dinner.","A2","evening meal|supper","breakfast|lunch|snack","dinner time|dinner party"],
["dinosaur","n.","ไดโนเสาร์","Toy dinosaur.","A2","extinct reptile","—","dinosaur extinction|T-Rex"],
["diploma","n.","ปริญญาบัตร","Earn diploma.","A2","certificate|degree|credential","—","high school diploma"],
["direct","adj/v.","โดยตรง, บอกทาง","Direct route.","A2","straight|immediate|guide","indirect|roundabout|crooked","direct to|direct line"],
["direction","n.","ทิศทาง","Which direction?","A2","way|course|heading","—","in the direction of|change direction"],
["directly","adv.","โดยตรง","Tell me directly.","A2","immediately|straight|without delay","indirectly|roundabout","directly to|come directly"],
["director","n.","ผู้อำนวยการ","Film director.","A2","manager|leader|chief","subordinate|follower","executive director|board director"],
["dirt","n.","ดิน, โคลน","Dirt road.","A2","soil|mud|filth","clean|purity","dirt cheap|caked with dirt"],
["dirty","adj.","สกปรก","Dirty clothes.","A2","unclean|filthy|soiled","clean|immaculate|spotless","get dirty|dirty water"],
["disable","v.","ทำให้ใช้ไม่ได้","Disable the alarm.","A2","turn off|deactivate|impair","enable|activate|empower","disable access|disable button"],
["disabled","adj.","ทุพพลภาพ","Disabled person.","A2","physically challenged|impaired","able-bodied|healthy","disabled veteran|disabled access"],
["disadvantage","n.","ข้อเสียเปรียบ","At a disadvantage.","A2","drawback|downside|handicap","advantage|benefit|edge","at a disadvantage|competitive disadvantage"],
["disagree","v.","ไม่เห็นด้วย","I disagree.","A2","differ|dispute|dissent","agree|concur|consent","disagree with|respectfully disagree"],
["disappear","v.","หายไป","Disappear into mist.","A2","vanish|go missing|fade away","appear|emerge|come into view","disappear into|disappear without trace"],
["disappoint","v.","ทำให้ผิดหวัง","Don't disappoint me.","A2","let down|fail|upset","satisfy|please|delight","disappoint someone|feeling disappointed"],
["disaster","n.","ภัยพิบัติ","Natural disaster.","A2","catastrophe|calamity|tragedy","blessing|success|fortune","disaster area|disaster relief"],
["discard","v.","ทิ้ง","Discard the idea.","A2","throw away|abandon|reject","keep|retain|preserve","discard of|discard pile"],
["discipline","n/v.","วินัย, ลงโทษ","Military discipline.","A2","training|self-control|punishment","anarchy|chaos","maintain discipline|disciplinary action"],
["disclose","v.","เปิดเผย","Disclose information.","A2","reveal|divulge|expose","conceal|hide|withhold","disclose to|full disclosure"],
["discount","n/v.","ส่วนลด, ไม่สนใจ","Get a discount.","A2","reduction|rebate|ignore","increase|mark up","discount rate|offer a discount"],
["discourage","v.","พัฒนาหรือท้อแท้","Discourage them.","A2","dishearten|deter|demoralize","encourage|promote|inspire","discourage from|get discouraged"],
["discover","v.","ค้นพบ","Discover treasure.","A2","find|uncover|learn","lose|hide|conceal","discover that|discovery of"],
["disease","n.","โรค","Infectious disease.","A2","illness|ailment|disorder","health|wellness","disease prevention|heart disease"],
["disgrace","n/v.","ความอัปยศ","Bring disgrace.","A2","shame|dishonor|disrepute","honor|dignity|pride","in disgrace|disgrace to"],
["disguise","n/v.","ปกปิด, ปลอมตัว","Wear a disguise.","A2","mask|conceal|pretense","reveal|expose|unmask","in disguise|blessing in disguise"],
["disgust","n/v.","ความรังเกียจ","Show disgust.","A2","revulsion|repugnance|contempt","delight|pleasure|admiration","feel disgust|disgust at"],
["disgusting","adj.","รังเกียจ","Disgusting food.","A2","repulsive|revolting|abhorrent","delightful|pleasant|attractive","absolutely disgusting|find disgusting"],
["dish","n.","จาน, อาหาร","Wash the dishes.","A2","plate|bowl|food","—","side dish|main dish|dish washer"],
["dishonest","adj.","ไม่ซื่อสัตย์","Dishonest person.","A2","deceitful|untruthful|fraudulent","honest|truthful|sincere","completely dishonest|dishonest dealing"],
["dismiss","v.","ไล่ออก, ปฏิเสธ","Dismiss the idea.","A2","fire|discharge|reject","hire|employ|accept","dismiss from|dismissive attitude"],
["disorder","n.","ความไม่เป็นระเบียบ","Mental disorder.","A2","chaos|confusion|illness","order|organization|peace","mental disorder|eating disorder"],
["display","v/n.","แสดง, การแสดง","Display the items.","A2","show|exhibit|present","hide|conceal|obscure","on display|display case"],
["disposable","adj.","ที่ใช้แล้วทิ้ง","Disposable cup.","A2","single-use|throwaway","reusable|permanent|durable","disposable income|disposable camera"],
["distance","n.","ระยะห่าง","Great distance.","A2","gap|space|length","proximity|closeness|nearness","short distance|long distance"],
["distant","adj.","ห่างไกล","Distant future.","A2","far|remote|aloof","near|close|nearby","distant past|distant relative"],
["distinct","adj.","ชัดเจน","Distinct possibility.","A2","clear|separate|obvious","vague|unclear|similar","quite distinct|distinct impression"],
["distinction","n.","ความแตกต่าง","Make a distinction.","A2","difference|contrast|honor","similarity|sameness","make distinction|with distinction"],
["distinguish","v.","แยกแยะ","Distinguish the two.","A2","differentiate|discern|recognize","confuse|mix up|blur","distinguish from|distinguish oneself"],
["distribution","n.","การกระจาย","Income distribution.","A2","allocation|dispersal|spread","concentration|gathering","distribution network|free distribution"],
["district","n.","เขต","Business district.","A2","area|region|zone","—","school district|industrial district"],
["disturb","v.","รบกวน","Don't disturb me.","A2","bother|interrupt|upset","calm|soothe|leave alone","do not disturb|disturbed by"],
["ditch","n/v.","ห้วย, ทิ้ง","Dig a ditch.","A2","trench|abandon|discard","—","water ditch|ditch the plan"],
["divide","v.","แบ่ง","Divide the group.","A2","split|separate|share","unite|combine|join","divide into|divide by"],
["division","n.","หน่วยงาน, การแบ่ง","Sales division.","A2","department|section|splitting","unity|wholeness","division of labor|cell division"],
["divorce","n/v.","หย่า","Get a divorce.","A2","separation|break|split","marriage|union","divorce from|divorce proceedings"],
["dizzy","adj.","เวียนศีรษะ","Feeling dizzy.","A2","lightheaded|unsteady|confused","steady|stable|clear-headed","get dizzy|dizzy spell"],
["do","v.","ทำ","What do you do?","A2","perform|execute|manage","—","do well|do damage"],
["dock","n/v.","ท่าเรือ, บ้วน","At the dock.","A2","harbor|pier|berth","inland|—","dock worker|dock strike"],
["doctor","n.","หมอ","See a doctor.","A2","physician|surgeon|medical professional","—","family doctor|good doctor"],
["doctrine","n.","หลักคำสอน","Political doctrine.","A2","principle|dogma|belief","—","military doctrine|religious doctrine"],
["document","n/v.","เอกสาร, บันทึก","Important document.","A2","file|record|evidence","—","legal document|historical document"],
["dog","n.","สุนัข","Walk the dog.","A2","canine|pet|animal","cat|—","guide dog|hot dog"],
["doll","n.","ตุ๊กตา","Toy doll.","A2","puppet|figurine","—","rag doll|doll house"],
["dollar","n.","ดอลลาร์","Five dollars.","A2","currency|money|unit","—","U.S. dollar|dollar bill"],
["dolphin","n.","โลมา","Intelligent dolphin.","A2","marine mammal|cetacean","—","friendly dolphin|dolphin show"],
["domain","n.","ขอบเขต, โดเมน","Public domain.","A2","field|realm|area","—","domain name|domain authority"],
["dome","n.","穹顶","Cathedral dome.","A2","arch|rounded roof|cupola","—","glass dome|dome-shaped"],
["domestic","adj.","ในประเทศ, ในบ้าน","Domestic animals.","A2","internal|household|civil","foreign|wild|international","domestic policy|domestic violence"],
["dominant","adj.","เด่นชัด","Dominant color.","A2","prevailing|main|ruling","subordinate|minor|secondary","dominant position|dominant species"],
["dominate","v.","ครอบ-เด่น","Dominate the market.","A2","control|rule|prevail","submit|surrender|yield","dominate over|dominating presence"],
["donate","v.","บริจาค","Donate blood.","A2","give|contribute|present","receive|take|accept","donate to|charitable donation"],
["donation","n.","การบริจาค","Make a donation.","A2","gift|contribution|bequest","—","blood donation|charitable donation"],
["done","adj/v.","เสร็จ","Task is done.","A2","finished|complete|ready","unfinished|incomplete|pending","well done|done with"],
["donor","n.","ผู้บริจาค","Blood donor.","A2","contributor|giver|provider","recipient|receiver","organ donor|anonymous donor"],
["door","n.","ประตู","Open the door.","A2","entrance|gate|way out","wall|window","next door|revolving door"],
["dose","n.","ปริมาณ","A dose of medicine.","A2","amount|quantity|prescribed amount","—","lethal dose|daily dose"],
["dot","n/v.","จุด","Connect the dots.","A2","point|speck|period","—","on the dot|dot-com"],
["doubt","n/v.","ความสงสัย","Express doubt.","A2","uncertainty|question|suspicion","certainty|confidence|faith","no doubt|beyond doubt"],
["doubtful","adj.","น่าสงสัย","Doubtful claim.","A2","questionable|uncertain|suspicious","certain|sure|confident","look doubtful|feel doubtful"],
["down","adv/prep.","ลง, ต่ำ","Look down.","A2","downward|below|fallen","up|upward|elevated","up and down|down payment"],
["downgrade","v/n.","ลดลิงค์","Downgrade the rating.","A2","lower|reduce|demote","upgrade|promote|improve","downgrade to|get downgraded"],
["downtown","n/adj.","ใจกลางเมือง","Go downtown.","A2","city center|business district","uptown|suburbs|outskirts","downtown area|downtown location"],
["downstream","adv/adj.","ล่างน้ำ","Downstream company.","A2","lower part|following|later","upstream|upper|preceding","downstream effect|downstream processing"],
["downward","adv/adj.","ลงมา","Downward trend.","A2","downwards|descending|declining","upward|ascending|rising","downward slope|downward movement"],
["draft","n/v.","ร่าง, กรณฑ","First draft.","A2","preliminary version|current of air|sketch","final|complete|polished","draft version|rough draft"],
["drag","v.","ลาก","Don't drag me.","A2","pull|haul|tow","push|lift|carry","drag on|drag out"],
["drain","v/n.","ระบาย, ระบายน้ำ","Drain the pool.","A2","empty|deplete|remove","fill|add|block up","brain drain|drainage system"],
["drama","n.","ละคร","Watch a drama.","A2","play|theatrical work|emotion|tension","comedy|fact|routine","family drama|drama class"],
["dramatic","adj.","น่าตื่นเต้น","Dramatic change.","A2","striking|impressive|theatrical","subtle|quiet|understated","dramatic effect|dramatic increase"],
["drank","v.","ดื่ม(อดีต)","She drank water.","A2","—","—","—"],
["drastic","adj.","ร้ายแรง","Drastic measure.","A2","extreme|severe|radical","mild|gentle|moderate","drastic change|take drastic action"],
["draw","v.","วาด, ดึง","Draw a picture.","A2","sketch|pull|attract","erase|push|repel","draw on|draw up"],
["drawer","n.","ลิ้นชัก","Open the drawer.","A2","compartment|sliding container","—","desk drawer|chest of drawers"],
["drawing","n.","ภาพวาด","Beautiful drawing.","A2","sketch|artwork|illustration","—","pencil drawing|drawing skills"],
["drawn","adj.","จึง, ลาก","Look drawn.","A2","pulled|haggard|exhausted","fresh|lively|energetic","—"],
["dread","v/n.","วิตกกังวล","Dread the news.","A2","fear|fear greatly|anxiety","look forward|hope|desire","dread to|live in dread"],
["dream","v/n.","ฝัน","Sweet dream.","A2","aspiration|fantasy|sleep vision","reality|fact|awake","bad dream|wild dreams|dream of"],
["dress","v/n.","แต่งตัว, ชุด","Dress well.","A2","put on clothes|garment|outfit","undress|disrobe|strip","get dressed|formal dress"],
["drew","v.","วาด(อดีต)","She drew a picture.","A2","—","—","—"],
["dried","adj.","แห้ง","Dried fruit.","A2","desiccated|dehydrated","fresh|wet|moist","sun-dried|freeze-dried"],
["drift","v/n.","ล่องลอย","Let it drift.","A2","float|wander|tendency","anchor|stay|fixed","continental drift|drift away"],
["drill","v/n.","ฝึก, สว่าน","Fire drill.","A2","practice|exercise|training tool","—","drill sergeant|safety drill"],
["drink","v/n.","ดื่ม, เครื่องดื่ม","Drink water.","A2","beverage|sip|consume","fast|abstain","drink up|have a drink"],
["drip","v/n.","ทำให้หยด","Faucet drips.","A2","drop|leak|fall in drops","—","drip feed|IV drip"],
["drive","v/n.","ขับรถ, ไดรฟ์","Drive carefully.","A2","operate a vehicle|motivation|urge","walk|ride|stop","test drive|hard drive"],
["driver","n.","คนขับรถ","Professional driver.","A2","operator|motorist|golf club","passenger","truck driver|bus driver"],
["driving","adj/n.","ขับรถ","Driving license.","A2","operating a vehicle|force|motivation","—","reckless driving|driving test"],
["drizzle","n/v.","ฝนพิลึก","Light drizzle.","A2","light rain|sprinkle","downpour|heavy rain|drought","drizzly weather|light drizzle"],
["drone","n/v.","โดรน, เสียงซ้ำเดิม","Flying drone.","A2","unmanned aircraft|monotone voice|worker bee","—","drone strike|delivery drone"],
["droop","v.","ห้อย","Flowers droop.","A2","hang|sag|wilt","rise|perk up|straighten","drooping shoulders|drooping eyelids"],
["drop","v/n.","ตกลง, หยด","Drop the ball.","A2","fall|lower|small quantity of liquid","raise|lift|rise","drop off|drop out"],
["drought","n.","ความแห้ง","Severe drought.","A2","dry spell|water shortage|long dry period","abundance|plenty|rain","prolonged drought|drought resistance"],
["drove","v.","ขับ(อดีต)","She drove away.","A2","—","—","—"],
["drown","v.","จมน้ำ","Nearly drown.","A2","perish in water|submerge|overwhelm","swim|float|survive","drown in|drown out"],
["drowsy","adj.","งวัง","Feeling drowsy.","A2","sleepy|sluggish|lethargic","alert|awake|energetic","feel drowsy|drowsy effect"],
["drug","n/v.","ยา, ยาเสพติด","Take a drug.","A2","medication|medicine|narcotic|substance","—","prescription drug|drug dealer"],
["drum","n/v.","กลอง","Play the drum.","A2","percussion instrument|beat|container","—","bass drum|ear drum"],
["drunk","adj/v.","เมา","Drunk person.","A2","intoxicated|inebriated|under the influence","sober|drunk driving"],
["dry","adj/v.","แห้ง","Dry cleaning.","A2","not wet|desiccated|witty","wet|moist|humid","bone-dry|run dry"],
["duck","n/v.","เป็ดน้ำ, หลบ","Duck the question.","A2","water bird|dodge|crouch","—","sitting duck|duck soup"],
["dull","adj.","ทึ้ม, จืด","Dull color.","A2","boring|not bright|blunt","bright|interesting|sharp","dull moment|dull pain"],
["dumb","adj.","ใจงั่ง, นิ่ง","Dumb question.","A2","stupid|mute|unable to speak","smart|intelligent|talkative","struck dumb|play dumb"],
["dump","v/n.","ทิ้ง, โครงการทิ้งขยะ","Dump the trash.","A2","discard|unload|landfill","treasure|save|keep","data dump|take a dump"],
["dune","n.","เนินทราย","Sand dune.","A2","sandhill|sand ridge","plain|valley|flat","sand dune|dune grass"],
["dunk","v.","จุ่ม","Dunk the donut.","A2","dip|submerge|immerse","—","dunk in|slam dunk"],
["duplicate","v/n.","เหมือน, สำเนา","Duplicate file.","A2","copy|replicate|double","original|unique|single","duplicate copy|exact duplicate"],
["durable","adj.","ทนทาน","Durable material.","A2","long-lasting|sturdy|strong","fragile|weak|delicate","durable goods|consumer durables"],
["duration","n.","ช่วงเวลา","Short duration.","A2","length|period|span of time","—","for the duration|life duration"],
["during","prep.","ระหว่าง","During the day.","A2","throughout|in the course of","before|after|outside","during which|during the meeting"],
["dusk","n.","ฝั่งค่ำ","At dusk.","A2","twilight|sunset|early evening","dawn|daylight|sunrise","from dusk til dawn"],
["dust","n/v.","ฝุ่น, ปัดฝุ่น","Collect dust.","A2","fine particles|remove dust|powder","—","collect dust|dust off"],
["duty","n.","หน้าที่, อากร","Fulfill your duty.","A2","responsibility|obligation|task|tax","freedom|right|privilege","on duty|sense of duty"],
["dwarf","n/v.","คนเตี้ย, ทำให้ดูเล็ก","Dwarf star.","A2","small person|small creature|make look small","giant|large|magnify","seven dwarfs|dwarf planet"],
["dwell","v.","อาศัย, คิดถึง","Dwell on the problem.","A2","live|reside|ponder","move|vacate","dwell on|dwelling place"],
["dwelling","n.","ที่อยู่อาศัย","Human dwelling.","A2","residence|home|habitation","—","dwelling place|human dwelling"],
["dye","v/n.","ย้อม, สีย้อม","Dye the fabric.","A2","color|stain|pigment","—","hair dye|fast dye"],
// Add B1 sample words...
];

VOCAB.push(...VOCAB_PART2);
// Initialize SRS data
let SRS_DB = {};
