// Oxford 5000 Vocabulary - A-Level / TGAT (30 days × 30 words)
// Days 1-20: B2 Level | Days 21-30: C1 Level
// Format: [word, POS, Thai meaning, example sentence, level, TGAT, A-Level, TOEFL]

const VOCAB_ALEVEL_TGAT = [
  // ===== DAY 1 (B2) =====
  ["absorb", "v.", "ซึมซับ", "The soil absorbs water quickly.", "B2", "—", "—", "—"],
  ["abstract", "adj.", "นามธรรม", "Abstract concepts are difficult to understand.", "B2", "—", "—", "—"],
  ["accent", "n.", "สำเนียง", "She speaks English with a French accent.", "B2", "—", "—", "—"],
  ["accommodate", "v.", "จัดสถานที่ให้", "The hotel can accommodate 200 guests.", "B2", "—", "—", "—"],
  ["accomplish", "v.", "สำเร็จ", "She accomplished her goals through hard work.", "B2", "—", "—", "—"],
  ["accurate", "adj.", "ถูกต้อง", "The report is accurate and reliable.", "B2", "—", "—", "—"],
  ["accuse", "v.", "กล่าวหา", "He was accused of stealing the diamond.", "B2", "—", "—", "—"],
  ["activate", "v.", "เปิดใช้", "Press this button to activate the alarm.", "B2", "—", "—", "—"],
  ["addiction", "n.", "การติด", "Smoking addiction is hard to break.", "B2", "—", "—", "—"],
  ["adequate", "adj.", "เพียงพอ", "The budget is adequate for the project.", "B2", "—", "—", "—"],
  ["adjust", "v.", "ปรับ", "You need to adjust the temperature.", "B2", "—", "—", "—"],
  ["admire", "v.", "ชื่นชม", "I admire her courage and determination.", "B2", "—", "—", "—"],
  ["admit", "v.", "ยอมรับ", "He finally admitted his mistake.", "B2", "—", "—", "—"],
  ["advance", "v.", "ก้าวหน้า", "Technology advances every year.", "B2", "—", "—", "—"],
  ["advertise", "v.", "โฆษณา", "Companies advertise on social media.", "B2", "—", "—", "—"],
  ["advice", "n.", "คำแนะนำ", "She gave me good advice about my career.", "B2", "—", "—", "—"],
  ["advise", "v.", "แนะนำ", "I advise you to study harder.", "B2", "—", "—", "—"],
  ["affect", "v.", "ส่งผลกระทบ", "The weather affects our mood.", "B2", "—", "—", "—"],
  ["afford", "v.", "จ่ายได้", "I can't afford to buy a new car.", "B2", "—", "—", "—"],
  ["agriculture", "n.", "การเกษตร", "Agriculture is important for Thailand's economy.", "B2", "—", "—", "—"],
  ["aim", "v.", "มีเป้าหมาย", "She aims to become a doctor.", "B2", "—", "—", "—"],
  ["aircraft", "n.", "เครื่องบิน", "The aircraft landed safely.", "B2", "—", "—", "—"],
  ["alarm", "n.", "สัญญาณเตือน", "The fire alarm sounded loudly.", "B2", "—", "—", "—"],
  ["album", "n.", "อัลบั้ม", "She released a new album last month.", "B2", "—", "—", "—"],
  ["alcohol", "n.", "แอลกอฮอล์", "Alcohol is not allowed at school events.", "B2", "—", "—", "—"],
  ["alike", "adj.", "คล้ายกัน", "The twins look alike.", "B2", "—", "—", "—"],
  ["alive", "adj.", "มีชีวิต", "The plant is still alive.", "B2", "—", "—", "—"],
  ["allow", "v.", "อนุญาต", "Parents allow their children to play outside.", "B2", "—", "—", "—"],
  ["almost", "adv.", "เกือบ", "It's almost midnight.", "B2", "—", "—", "—"],
  ["alone", "adj.", "โดยลำพัง", "She lived alone for five years.", "B2", "—", "—", "—"],

  // ===== DAY 2 (B2) =====
  ["along", "prep.", "ตามแนว", "We walked along the beach.", "B2", "—", "—", "—"],
  ["alternative", "n.", "ทางเลือก", "If you don't like coffee, tea is an alternative.", "B2", "—", "—", "—"],
  ["although", "conj.", "ถึงแม้ว่า", "Although it rained, we went hiking.", "B2", "—", "—", "—"],
  ["altogether", "adv.", "ทั้งหมด", "The shoes cost $50 altogether.", "B2", "—", "—", "—"],
  ["ambition", "n.", "ความทะเยาะ", "Her ambition is to win the championship.", "B2", "—", "—", "—"],
  ["among", "prep.", "ท่ามกลาง", "She is among the best students in the class.", "B2", "—", "—", "—"],
  ["amount", "n.", "จำนวน", "The amount of money is sufficient.", "B2", "—", "—", "—"],
  ["amuse", "v.", "ทำให้หัวเราะ", "The movie amused the whole family.", "B2", "—", "—", "—"],
  ["analysis", "n.", "การวิเคราะห์", "The analysis shows interesting results.", "B2", "—", "—", "—"],
  ["analyze", "v.", "วิเคราะห์", "We need to analyze the data carefully.", "B2", "—", "—", "—"],
  ["ancestor", "n.", "บรรพบุรุษ", "His ancestors came from China.", "B2", "—", "—", "—"],
  ["ancient", "adj.", "โบราณ", "Ancient Egypt was a great civilization.", "B2", "—", "—", "—"],
  ["angel", "n.", "เทพยาวดา", "The child looks like an angel.", "B2", "—", "—", "—"],
  ["anger", "n.", "ความโกรธ", "He spoke with anger in his voice.", "B2", "—", "—", "—"],
  ["angle", "n.", "มุม", "The angle of the roof is 45 degrees.", "B2", "—", "—", "—"],
  ["angry", "adj.", "โกรธ", "She was angry about the broken promise.", "B2", "—", "—", "—"],
  ["animal", "n.", "สัตว์", "Lions are wild animals.", "B2", "—", "—", "—"],
  ["animate", "v.", "ทำให้มีชีวิต", "Artists animate the characters frame by frame.", "B2", "—", "—", "—"],
  ["ankle", "n.", "ข้อเท้า", "He sprained his ankle playing basketball.", "B2", "—", "—", "—"],
  ["announce", "v.", "ประกาศ", "The principal announced the winners.", "B2", "—", "—", "—"],
  ["annoy", "v.", "รบกวน", "The loud noise annoyed the neighbors.", "B2", "—", "—", "—"],
  ["annual", "adj.", "ประจำปี", "The annual meeting is in January.", "B2", "—", "—", "—"],
  ["anxiety", "n.", "ความกังวล", "Test anxiety is common among students.", "B2", "—", "—", "—"],
  ["anxious", "adj.", "กังวล", "She was anxious about the exam.", "B2", "—", "—", "—"],
  ["any", "det.", "ใดๆ", "Do you have any questions?", "B2", "—", "—", "—"],
  ["anybody", "pron.", "ใครก็ตาม", "Anybody can apply for the job.", "B2", "—", "—", "—"],
  ["anyone", "pron.", "ใครก็ตาม", "Does anyone want to go to the movies?", "B2", "—", "—", "—"],
  ["anything", "pron.", "อะไรก็ตาม", "You can choose anything you want.", "B2", "—", "—", "—"],
  ["anyway", "adv.", "ในทุกกรณี", "The weather is bad, but let's go anyway.", "B2", "—", "—", "—"],
  ["anywhere", "adv.", "ที่ไหนก็ตาม", "You can travel anywhere in Europe.", "B2", "—", "—", "—"],

  // ===== DAY 3 (B2) =====
  ["apart", "adv.", "แยกออก", "The two buildings are far apart.", "B2", "—", "—", "—"],
  ["apartment", "n.", "อพาร์ตเมนต์", "She rents an apartment in the city.", "B2", "—", "—", "—"],
  ["apologize", "v.", "ขอโทษ", "He apologized for being late.", "B2", "—", "—", "—"],
  ["apology", "n.", "คำขอโทษ", "She accepted his apology.", "B2", "—", "—", "—"],
  ["apparel", "n.", "เสื้อผ้า", "The apparel industry is growing.", "B2", "—", "—", "—"],
  ["apparent", "adj.", "ชัดเจน", "It was apparent that he was lying.", "B2", "—", "—", "—"],
  ["appeal", "v.", "ขอ", "The advertisement appeals to young people.", "B2", "—", "—", "—"],
  ["appear", "v.", "ปรากฏ", "Stars appear in the night sky.", "B2", "—", "—", "—"],
  ["appearance", "n.", "การปรากฏ", "His appearance has changed a lot.", "B2", "—", "—", "—"],
  ["appetite", "n.", "ความหิว", "He has a good appetite.", "B2", "—", "—", "—"],
  ["applaud", "v.", "ปัดมือให้เสียง", "The audience applauded the performance.", "B2", "—", "—", "—"],
  ["apple", "n.", "แอปเปิล", "Apples are good for your health.", "B2", "—", "—", "—"],
  ["appliance", "n.", "เครื่องใช้", "Kitchen appliances can be expensive.", "B2", "—", "—", "—"],
  ["applicant", "n.", "ผู้สมัคร", "There are 100 applicants for the job.", "B2", "—", "—", "—"],
  ["application", "n.", "การสมัคร", "She submitted her job application.", "B2", "—", "—", "—"],
  ["apply", "v.", "สมัคร", "He applied for a scholarship.", "B2", "—", "—", "—"],
  ["appoint", "v.", "แต่งตั้ง", "The government appointed a new minister.", "B2", "—", "—", "—"],
  ["appointment", "n.", "การนัดหมาย", "I have a doctor's appointment tomorrow.", "B2", "—", "—", "—"],
  ["appreciate", "v.", "ชื่นชม", "I appreciate your help very much.", "B2", "—", "—", "—"],
  ["approach", "v.", "เข้าใกล้", "Winter is approaching.", "B2", "—", "—", "—"],
  ["appropriate", "adj.", "เหมาะสม", "This behavior is not appropriate.", "B2", "—", "—", "—"],
  ["approval", "n.", "การอนุมัติ", "The project needs government approval.", "B2", "—", "—", "—"],
  ["approve", "v.", "อนุมัติ", "The boss approved the budget.", "B2", "—", "—", "—"],
  ["April", "n.", "เมษายน", "April is the fourth month of the year.", "B2", "—", "—", "—"],
  ["arch", "n.", "โค้ง", "The stone arch is beautiful.", "B2", "—", "—", "—"],
  ["architect", "n.", "สถาปนิก", "The architect designed the building.", "B2", "—", "—", "—"],
  ["architecture", "n.", "สถาปัตยกรรม", "Modern architecture is interesting.", "B2", "—", "—", "—"],
  ["arctic", "adj.", "อาร์กติก", "Arctic animals adapt to cold weather.", "B2", "—", "—", "—"],
  ["area", "n.", "พื้นที่", "This area is very quiet.", "B2", "—", "—", "—"],
  ["arena", "n.", "สนาม", "The arena was packed with fans.", "B2", "—", "—", "—"],

  // ===== DAY 4 (B2) =====
  ["argue", "v.", "โต้เถียง", "They argue about politics constantly.", "B2", "—", "—", "—"],
  ["argument", "n.", "การโต้เถียง", "They had an argument about money.", "B2", "—", "—", "—"],
  ["arise", "v.", "เกิดขึ้น", "Problems arose during the project.", "B2", "—", "—", "—"],
  ["arm", "n.", "แขน", "He broke his arm in the accident.", "B2", "—", "—", "—"],
  ["armour", "n.", "เกราะ", "Knights wore armour into battle.", "B2", "—", "—", "—"],
  ["army", "n.", "กองทัพ", "He joined the army after graduation.", "B2", "—", "—", "—"],
  ["around", "prep.", "รอบๆ", "There are trees around the house.", "B2", "—", "—", "—"],
  ["arrange", "v.", "จัดเรียง", "She arranged the flowers in a vase.", "B2", "—", "—", "—"],
  ["arrangement", "n.", "การจัดเรียง", "The seating arrangement was perfect.", "B2", "—", "—", "—"],
  ["arrest", "v.", "จับกุม", "Police arrested the suspect.", "B2", "—", "—", "—"],
  ["arrival", "n.", "การมาถึง", "Announce your arrival when you get there.", "B2", "—", "—", "—"],
  ["arrive", "v.", "มาถึง", "The train arrived on time.", "B2", "—", "—", "—"],
  ["arrow", "n.", "ลูกศร", "He shot an arrow at the target.", "B2", "—", "—", "—"],
  ["art", "n.", "ศิลปะ", "She loves painting and art.", "B2", "—", "—", "—"],
  ["article", "n.", "บทความ", "I read an interesting article in the newspaper.", "B2", "—", "—", "—"],
  ["artificial", "adj.", "เทียม", "Artificial flowers look real.", "B2", "—", "—", "—"],
  ["artist", "n.", "ศิลปิน", "The artist painted a beautiful portrait.", "B2", "—", "—", "—"],
  ["artistic", "adj.", "ศิลปะ", "She has artistic talent.", "B2", "—", "—", "—"],
  ["as", "conj.", "เมื่อ", "As we walked, we talked.", "B2", "—", "—", "—"],
  ["ash", "n.", "เถ้า", "Cigarette ash fell on the table.", "B2", "—", "—", "—"],
  ["ashamed", "adj.", "อายเหม", "He was ashamed of his behavior.", "B2", "—", "—", "—"],
  ["ashore", "adv.", "บนฝั่ง", "The boat came ashore.", "B2", "—", "—", "—"],
  ["aside", "adv.", "ไปด้านข้าง", "She put her homework aside to watch TV.", "B2", "—", "—", "—"],
  ["ask", "v.", "ถาม", "She asked him a question.", "B2", "—", "—", "—"],
  ["asleep", "adj.", "นอนหลับ", "The baby fell asleep immediately.", "B2", "—", "—", "—"],
  ["aspect", "n.", "ด้าน", "Consider every aspect of the problem.", "B2", "—", "—", "—"],
  ["assessment", "n.", "การประเมิน", "The assessment showed good progress.", "B2", "—", "—", "—"],
  ["asset", "n.", "ทรัพย์สิน", "Land is a valuable asset.", "B2", "—", "—", "—"],
  ["assign", "v.", "มอบหมาย", "The teacher assigned homework.", "B2", "—", "—", "—"],
  ["assignment", "n.", "งานที่มอบหมาย", "The assignment is due tomorrow.", "B2", "—", "—", "—"],

  // ===== DAY 5 (B2) =====
  ["assist", "v.", "ช่วยเหลือ", "I will assist you with the project.", "B2", "—", "—", "—"],
  ["assistance", "n.", "ความช่วยเหลือ", "She asked for assistance with her work.", "B2", "—", "—", "—"],
  ["assistant", "n.", "ผู้ช่วย", "The assistant helped the manager.", "B2", "—", "—", "—"],
  ["associate", "v.", "เชื่อมโยง", "Many people associate rain with sadness.", "B2", "—", "—", "—"],
  ["association", "n.", "สมาคม", "He joined a sports association.", "B2", "—", "—", "—"],
  ["assume", "v.", "สมมติ", "I assume you're happy with the result.", "B2", "—", "—", "—"],
  ["assumption", "n.", "สมมติฐาน", "Your assumption is not correct.", "B2", "—", "—", "—"],
  ["assure", "v.", "มั่นใจให้", "He assured her that everything would be fine.", "B2", "—", "—", "—"],
  ["astonish", "v.", "ทำให้ตกใจ", "Her beauty astonished everyone.", "B2", "—", "—", "—"],
  ["astonishing", "adj.", "น่าตกใจ", "The results were astonishing.", "B2", "—", "—", "—"],
  ["astray", "adv.", "หลงทาง", "The ship went astray in the storm.", "B2", "—", "—", "—"],
  ["athlete", "n.", "นักกีฬา", "She is a professional athlete.", "B2", "—", "—", "—"],
  ["athletic", "adj.", "เกี่ยวกับกีฬา", "He has an athletic build.", "B2", "—", "—", "—"],
  ["Atlantic", "n.", "มหาสมุทรแอตแลนติก", "The Atlantic Ocean is very large.", "B2", "—", "—", "—"],
  ["atmosphere", "n.", "บรรยากาศ", "The atmosphere at the party was festive.", "B2", "—", "—", "—"],
  ["atom", "n.", "อะตอม", "An atom is very small.", "B2", "—", "—", "—"],
  ["atomic", "adj.", "เกี่ยวกับอะตอม", "Atomic energy is powerful.", "B2", "—", "—", "—"],
  ["attach", "v.", "ติด", "Attach the documents to the email.", "B2", "—", "—", "—"],
  ["attachment", "n.", "ไฟล์แนบ", "The email has an attachment.", "B2", "—", "—", "—"],
  ["attack", "v.", "โจมตี", "The dog attacked the intruder.", "B2", "—", "—", "—"],
  ["attain", "v.", "บรรลุ", "She attained her goal through hard work.", "B2", "—", "—", "—"],
  ["attempt", "v.", "พยายาม", "He attempted to climb the mountain.", "B2", "—", "—", "—"],
  ["attend", "v.", "เข้าร่วม", "Will you attend the meeting?", "B2", "—", "—", "—"],
  ["attendance", "n.", "การเข้าร่วม", "Your attendance is important.", "B2", "—", "—", "—"],
  ["attendant", "n.", "พนักงาน", "The flight attendant served drinks.", "B2", "—", "—", "—"],
  ["attention", "n.", "ความสนใจ", "Pay attention to the teacher.", "B2", "—", "—", "—"],
  ["attentive", "adj.", "มีสติสัมปชัญญะ", "She was attentive during the lecture.", "B2", "—", "—", "—"],
  ["attic", "n.", "ห้องใต้หลังคา", "Old items are stored in the attic.", "B2", "—", "—", "—"],
  ["attitude", "n.", "ทัศนคติ", "Your attitude determines your success.", "B2", "—", "—", "—"],
  ["attorney", "n.", "ทนายความ", "The attorney defended her in court.", "B2", "—", "—", "—"],

  // ===== DAY 6 (B2) =====
  ["attract", "v.", "ดึงดูด", "Bright colors attract butterflies.", "B2", "—", "—", "—"],
  ["attraction", "n.", "สิ่งดึงดูด", "The main attraction at the theme park is the roller coaster.", "B2", "—", "—", "—"],
  ["attractive", "adj.", "น่าดึงดูด", "She wore an attractive dress.", "B2", "—", "—", "—"],
  ["attribute", "v.", "ถือว่า", "I attribute his success to hard work.", "B2", "—", "—", "—"],
  ["auction", "n.", "การประมูล", "The painting sold at an auction.", "B2", "—", "—", "—"],
  ["audience", "n.", "ผู้ชม", "The audience applauded the actor.", "B2", "—", "—", "—"],
  ["August", "n.", "สิงหาคม", "August is very hot in Thailand.", "B2", "—", "—", "—"],
  ["aunt", "n.", "ป้า", "My aunt lives in Bangkok.", "B2", "—", "—", "—"],
  ["authentic", "adj.", "แท้", "This is an authentic Italian restaurant.", "B2", "—", "—", "—"],
  ["author", "n.", "ผู้เขียน", "The author wrote a best-selling book.", "B2", "—", "—", "—"],
  ["authority", "n.", "อำนาจ", "The police have authority to arrest criminals.", "B2", "—", "—", "—"],
  ["authorize", "v.", "ให้อำนาจ", "The manager authorized the purchase.", "B2", "—", "—", "—"],
  ["automatic", "adj.", "อัตโนมัติ", "The door opens automatically.", "B2", "—", "—", "—"],
  ["automobile", "n.", "รถยนต์", "Automobiles have changed transportation.", "B2", "—", "—", "—"],
  ["autumn", "n.", "ฤดูใบไม้ร่วง", "Autumn leaves are beautiful.", "B2", "—", "—", "—"],
  ["available", "adj.", "พร้อมให้ใช้", "The book is available at the library.", "B2", "—", "—", "—"],
  ["avenue", "n.", "ถนนกว้าง", "The avenue is lined with trees.", "B2", "—", "—", "—"],
  ["average", "adj.", "ปกติ", "The average temperature in summer is 35°C.", "B2", "—", "—", "—"],
  ["aviation", "n.", "การบิน", "He works in the aviation industry.", "B2", "—", "—", "—"],
  ["avoid", "v.", "หลีกเลี่ยง", "Try to avoid eating too much sugar.", "B2", "—", "—", "—"],
  ["awake", "adj.", "ตื่น", "I was awake all night.", "B2", "—", "—", "—"],
  ["award", "n.", "รางวัล", "She won an award for best actress.", "B2", "—", "—", "—"],
  ["aware", "adj.", "ตระหนัก", "Are you aware of the risks?", "B2", "—", "—", "—"],
  ["awareness", "n.", "การตระหนัก", "Environmental awareness is important.", "B2", "—", "—", "—"],
  ["away", "adv.", "ไกล", "The school is 5 km away.", "B2", "—", "—", "—"],
  ["awful", "adj.", "แย่มาก", "The weather is awful today.", "B2", "—", "—", "—"],
  ["awkward", "adj.", "อึดอัด", "The situation was awkward and uncomfortable.", "B2", "—", "—", "—"],
  ["axis", "n.", "แกน", "The Earth rotates on its axis.", "B2", "—", "—", "—"],
  ["baby", "n.", "ทารก", "The baby was born yesterday.", "B2", "—", "—", "—"],
  ["bachelor", "n.", "โสด", "He is a bachelor with no children.", "B2", "—", "—", "—"],

  // ===== DAY 7 (B2) =====
  ["background", "n.", "พื้นหลัง", "She has a background in music.", "B2", "—", "—", "—"],
  ["backward", "adv.", "ถอยหลัง", "He walked backward carefully.", "B2", "—", "—", "—"],
  ["bacon", "n.", "เบคอน", "Bacon is salty and tasty.", "B2", "—", "—", "—"],
  ["bacteria", "n.", "แบคทีเรีย", "Bacteria can cause disease.", "B2", "—", "—", "—"],
  ["badge", "n.", "เข็มตรวจสอบ", "He wore a security badge.", "B2", "—", "—", "—"],
  ["badly", "adv.", "อย่างแย่", "The house was badly damaged.", "B2", "—", "—", "—"],
  ["baggage", "n.", "สัมภาระ", "Check your baggage at the airport.", "B2", "—", "—", "—"],
  ["bail", "n.", "ค่าประกัน", "The judge set bail at 100,000 baht.", "B2", "—", "—", "—"],
  ["bait", "n.", "อาหารเหยื่อ", "Use bread as bait for fishing.", "B2", "—", "—", "—"],
  ["balance", "v.", "สมดุล", "She balanced the pencil on her finger.", "B2", "—", "—", "—"],
  ["balcony", "n.", "ระเบียง", "The apartment has a large balcony.", "B2", "—", "—", "—"],
  ["bald", "adj.", "秃", "The old man is bald.", "B2", "—", "—", "—"],
  ["ball", "n.", "ลูกบอล", "The children played with a ball.", "B2", "—", "—", "—"],
  ["ballet", "n.", "บัลเลต์", "She performs in a ballet company.", "B2", "—", "—", "—"],
  ["balloon", "n.", "ลูกบอลลูน", "The balloon floated in the sky.", "B2", "—", "—", "—"],
  ["bamboo", "n.", "ไม้ไผ่", "Bamboo grows quickly in Asia.", "B2", "—", "—", "—"],
  ["ban", "v.", "ห้าม", "The government banned plastic bags.", "B2", "—", "—", "—"],
  ["banana", "n.", "กล้วย", "Bananas are yellow and sweet.", "B2", "—", "—", "—"],
  ["band", "n.", "วงดนตรี", "The band played rock music.", "B2", "—", "—", "—"],
  ["bandage", "n.", "ผ้าพันแผล", "She wrapped a bandage around her arm.", "B2", "—", "—", "—"],
  ["bank", "n.", "ธนาคาร", "I have an account at this bank.", "B2", "—", "—", "—"],
  ["banker", "n.", "นายธนาคาร", "The banker gave financial advice.", "B2", "—", "—", "—"],
  ["banner", "n.", "ธงโปรแกรม", "A banner hung from the building.", "B2", "—", "—", "—"],
  ["bar", "n.", "บาร์", "They met at a bar for drinks.", "B2", "—", "—", "—"],
  ["bare", "adj.", "เปลือย", "The room was bare and empty.", "B2", "—", "—", "—"],
  ["barely", "adv.", "เพียงแค่", "I barely passed the exam.", "B2", "—", "—", "—"],
  ["bargain", "n.", "สินค้าราคาถูก", "That's a great bargain!", "B2", "—", "—", "—"],
  ["bark", "v.", "เห่า", "The dog barks at strangers.", "B2", "—", "—", "—"],
  ["barrel", "n.", "ถัง", "The barrel contained wine.", "B2", "—", "—", "—"],
  ["barrier", "n.", "อุปสรรค", "The river is a natural barrier.", "B2", "—", "—", "—"],

  // ===== DAY 8 (B2) =====
  ["base", "n.", "ฐาน", "The military base is large.", "B2", "—", "—", "—"],
  ["baseball", "n.", "เบสบอล", "Baseball is popular in America.", "B2", "—", "—", "—"],
  ["basement", "n.", "ชั้นใต้ดิน", "The basement is used for storage.", "B2", "—", "—", "—"],
  ["basic", "adj.", "พื้นฐาน", "Learn the basic skills first.", "B2", "—", "—", "—"],
  ["basis", "n.", "พื้นฐาน", "On the basis of evidence, he was guilty.", "B2", "—", "—", "—"],
  ["basket", "n.", "ตะกร้า", "Put the apples in a basket.", "B2", "—", "—", "—"],
  ["basketball", "n.", "บาสเกตบอล", "She plays basketball for the school team.", "B2", "—", "—", "—"],
  ["bat", "n.", "ค้างคาว", "A bat is a nocturnal animal.", "B2", "—", "—", "—"],
  ["batch", "n.", "กลุ่ม", "The factory produces a batch every hour.", "B2", "—", "—", "—"],
  ["bath", "n.", "อาบน้ำ", "I took a relaxing bath.", "B2", "—", "—", "—"],
  ["bathe", "v.", "อาบน้ำ", "She bathes the baby every evening.", "B2", "—", "—", "—"],
  ["bathroom", "n.", "ห้องน้ำ", "The bathroom is very clean.", "B2", "—", "—", "—"],
  ["battery", "n.", "แบตเตอรี่", "The remote needs new batteries.", "B2", "—", "—", "—"],
  ["battle", "n.", "การสู้รบ", "The battle lasted three days.", "B2", "—", "—", "—"],
  ["beach", "n.", "หาด", "We spent the day at the beach.", "B2", "—", "—", "—"],
  ["bean", "n.", "ถั่ว", "Beans are nutritious.", "B2", "—", "—", "—"],
  ["bear", "n.", "หมี", "The bear is a large animal.", "B2", "—", "—", "—"],
  ["bear", "v.", "ทนทำให้", "I can't bear to see animals suffer.", "B2", "—", "—", "—"],
  ["beard", "n.", "เครา", "He grew a thick beard.", "B2", "—", "—", "—"],
  ["beat", "v.", "เต้น", "My heart beats fast when I'm nervous.", "B2", "—", "—", "—"],
  ["beautiful", "adj.", "สวยงาม", "She is a beautiful woman.", "B2", "—", "—", "—"],
  ["beauty", "n.", "ความสวยงาม", "The beauty of nature is amazing.", "B2", "—", "—", "—"],
  ["became", "v.", "กลายเป็น", "She became a lawyer.", "B2", "—", "—", "—"],
  ["because", "conj.", "เพราะ", "I didn't go because it was raining.", "B2", "—", "—", "—"],
  ["become", "v.", "กลายเป็น", "He became famous after the movie.", "B2", "—", "—", "—"],
  ["bed", "n.", "เตียง", "She went to bed early.", "B2", "—", "—", "—"],
  ["bedroom", "n.", "ห้องนอน", "The bedroom is on the second floor.", "B2", "—", "—", "—"],
  ["beef", "n.", "เนื้อวัว", "Beef is expensive meat.", "B2", "—", "—", "—"],
  ["before", "prep.", "ก่อน", "I came before you.", "B2", "—", "—", "—"],
  ["beg", "v.", "ขอทีอยาก", "The dog begged for food.", "B2", "—", "—", "—"],

  // ===== DAY 9 (B2) =====
  ["begin", "v.", "เริ่มต้น", "The movie begins at 7 PM.", "B2", "—", "—", "—"],
  ["beginning", "n.", "จุดเริ่มต้น", "This is the beginning of a new era.", "B2", "—", "—", "—"],
  ["behalf", "n.", "ตัวแทน", "I speak on behalf of the group.", "B2", "—", "—", "—"],
  ["behave", "v.", "ประพฤติ", "The children behaved well.", "B2", "—", "—", "—"],
  ["behavior", "n.", "พฤติกรรม", "His behavior is unacceptable.", "B2", "—", "—", "—"],
  ["behind", "prep.", "ด้านหลัง", "The cat hid behind the sofa.", "B2", "—", "—", "—"],
  ["being", "n.", "สิ่งมีชีวิต", "Every being deserves respect.", "B2", "—", "—", "—"],
  ["belief", "n.", "ความเชื่อ", "Religious belief is important to her.", "B2", "—", "—", "—"],
  ["believe", "v.", "เชื่อ", "Do you believe in ghosts?", "B2", "—", "—", "—"],
  ["bell", "n.", "กระดิ่ง", "The bell rang at noon.", "B2", "—", "—", "—"],
  ["belong", "v.", "เป็นของ", "This book belongs to the library.", "B2", "—", "—", "—"],
  ["below", "prep.", "ด้านล่าง", "The temperature is below freezing.", "B2", "—", "—", "—"],
  ["belt", "n.", "เข็มขัด", "He wore a leather belt.", "B2", "—", "—", "—"],
  ["bench", "n.", "ม้านั่ง", "We sat on a park bench.", "B2", "—", "—", "—"],
  ["bend", "v.", "โค้ง", "Don't bend the paper.", "B2", "—", "—", "—"],
  ["beneath", "prep.", "ใต้", "The treasure is buried beneath the sand.", "B2", "—", "—", "—"],
  ["benefit", "n.", "ประโยชน์", "Exercise has many health benefits.", "B2", "—", "—", "—"],
  ["bent", "adj.", "งอ", "The bent wire couldn't be used.", "B2", "—", "—", "—"],
  ["berth", "n.", "ที่นอนบนเรือ", "She booked a berth on the ship.", "B2", "—", "—", "—"],
  ["berry", "n.", "เบอร์รี่", "Strawberries are sweet berries.", "B2", "—", "—", "—"],
  ["beside", "prep.", "ข้างๆ", "She sat beside her friend.", "B2", "—", "—", "—"],
  ["besides", "adv.", "นอกจากนี้", "Besides, it's too expensive.", "B2", "—", "—", "—"],
  ["best", "adj.", "ที่ดีที่สุด", "This is the best restaurant in town.", "B2", "—", "—", "—"],
  ["betray", "v.", "ทรยศ", "He betrayed his friend's trust.", "B2", "—", "—", "—"],
  ["better", "adj.", "ดีกว่า", "This solution is better than the first one.", "B2", "—", "—", "—"],
  ["between", "prep.", "ระหว่าง", "The river runs between two cities.", "B2", "—", "—", "—"],
  ["beverage", "n.", "เครื่องดื่ม", "Various beverages are served.", "B2", "—", "—", "—"],
  ["beyond", "prep.", "นอกเหนือจาก", "The city extends beyond the mountains.", "B2", "—", "—", "—"],
  ["bias", "n.", "อคติ", "Everyone has some bias.", "B2", "—", "—", "—"],
  ["Bible", "n.", "พระคัมภีร์", "The Bible is a holy text.", "B2", "—", "—", "—"],

  // ===== DAY 10 (B2) =====
  ["bicycle", "n.", "จักรยาน", "I ride a bicycle to work.", "B2", "—", "—", "—"],
  ["bid", "v.", "เสนอราคา", "He bid for the painting at the auction.", "B2", "—", "—", "—"],
  ["big", "adj.", "ใหญ่", "The elephant is a big animal.", "B2", "—", "—", "—"],
  ["bike", "n.", "จักรยาน", "His bike is parked outside.", "B2", "—", "—", "—"],
  ["bike", "n.", "รถมอเตอร์ไซค์", "He rides a bike to work.", "B2", "—", "—", "—"],
  ["bill", "n.", "ใบเรียกเก็บเงิน", "The restaurant bill was expensive.", "B2", "—", "—", "—"],
  ["billboard", "n.", "ป้ายโฆษณา", "The billboard advertises cars.", "B2", "—", "—", "—"],
  ["billion", "num.", "พันล้าน", "A billion is a large number.", "B2", "—", "—", "—"],
  ["bind", "v.", "มัด", "Bind the books together.", "B2", "—", "—", "—"],
  ["biology", "n.", "ชีววิทยา", "She studies biology at university.", "B2", "—", "—", "—"],
  ["bird", "n.", "นก", "Birds sing in the morning.", "B2", "—", "—", "—"],
  ["birth", "n.", "การเกิด", "Her birth date is January 5th.", "B2", "—", "—", "—"],
  ["birthday", "n.", "วันเกิด", "Happy birthday!", "B2", "—", "—", "—"],
  ["biscuit", "n.", "บิสกิต", "She ate a chocolate biscuit.", "B2", "—", "—", "—"],
  ["bishop", "n.", "บิชอป", "The bishop blessed the congregation.", "B2", "—", "—", "—"],
  ["bit", "n.", "อะไหล่ เล็กน้อย", "A bit of salt improves the taste.", "B2", "—", "—", "—"],
  ["bite", "v.", "กัด", "The dog bit the intruder.", "B2", "—", "—", "—"],
  ["bitter", "adj.", "ขม", "Bitter coffee is not for everyone.", "B2", "—", "—", "—"],
  ["bizarre", "adj.", "แปลกประหลาด", "His clothing choice is bizarre.", "B2", "—", "—", "—"],
  ["black", "adj.", "ดำ", "She wore a black dress.", "B2", "—", "—", "—"],
  ["blade", "n.", "ใบมีด", "The knife blade is sharp.", "B2", "—", "—", "—"],
  ["blame", "v.", "โทษ", "Don't blame me for this mistake.", "B2", "—", "—", "—"],
  ["blank", "adj.", "ว่างเปล่า", "The paper is blank.", "B2", "—", "—", "—"],
  ["blanket", "n.", "ผ้าห่ม", "The child slept under a blanket.", "B2", "—", "—", "—"],
  ["blast", "n.", "ระเบิด", "The bomb blast destroyed the building.", "B2", "—", "—", "—"],
  ["bleak", "adj.", "ซึ่งมีท่าทีไม่เป็นสุข", "The outlook is bleak.", "B2", "—", "—", "—"],
  ["bleed", "v.", "ไหลเลือด", "The wound bled for a long time.", "B2", "—", "—", "—"],
  ["blend", "v.", "ผสม", "Blend the ingredients together.", "B2", "—", "—", "—"],
  ["blessing", "n.", "พร", "Marriage is a blessing.", "B2", "—", "—", "—"],
  ["blind", "adj.", "บอด", "He is blind and uses a cane.", "B2", "—", "—", "—"],

  // ===== DAY 11-20 (B2) - More vocabulary =====
  ["blink", "v.", "กระพริบ", "She blinked in the bright light.", "B2", "—", "—", "—"],
  ["bliss", "n.", "ความสุข", "Married life is bliss.", "B2", "—", "—", "—"],
  ["block", "n.", "บล็อก", "A city block contains several buildings.", "B2", "—", "—", "—"],
  ["block", "v.", "ปิดกั้น", "The accident blocked the highway.", "B2", "—", "—", "—"],
  ["blonde", "adj.", "สีบลอนด์", "She has blonde hair.", "B2", "—", "—", "—"],
  ["blood", "n.", "เลือด", "Blood type is important for donations.", "B2", "—", "—", "—"],
  ["bloom", "v.", "บาน", "Flowers bloom in spring.", "B2", "—", "—", "—"],
  ["blossom", "n.", "ดอกไม้", "Cherry blossoms are beautiful.", "B2", "—", "—", "—"],
  ["blow", "v.", "พัด", "The wind blows hard today.", "B2", "—", "—", "—"],
  ["blue", "adj.", "น้ำเงิน", "The sky is blue.", "B2", "—", "—", "—"],
  ["blunder", "n.", "ความผิดพลาด", "That was a major blunder.", "B2", "—", "—", "—"],
  ["blunt", "adj.", "มีคม", "A blunt knife is useless.", "B2", "—", "—", "—"],
  ["blush", "v.", "หน้าแดง", "She blushed when complimented.", "B2", "—", "—", "—"],
  ["board", "n.", "กระดาน", "Write on the board.", "B2", "—", "—", "—"],
  ["board", "v.", "ขึ้นเครื่องบิน", "It's time to board the plane.", "B2", "—", "—", "—"],
  ["boast", "v.", "หวาดเหวี่ยง", "He boasted about his achievements.", "B2", "—", "—", "—"],
  ["boat", "n.", "เรือ", "They sailed in a small boat.", "B2", "—", "—", "—"],
  ["body", "n.", "ร่างกาย", "Exercise keeps the body healthy.", "B2", "—", "—", "—"],
  ["boil", "v.", "ต้ม", "Boil the water before drinking.", "B2", "—", "—", "—"],
  ["bold", "adj.", "กล้า", "He made a bold decision.", "B2", "—", "—", "—"],
  ["bolt", "n.", "สลัก", "The bolt holds the machine together.", "B2", "—", "—", "—"],
  ["bomb", "n.", "炸弹", "The bomb was defused by experts.", "B2", "—", "—", "—"],
  ["bond", "n.", "พันธบัญชี", "A strong bond exists between them.", "B2", "—", "—", "—"],
  ["bone", "n.", "กระดูก", "Dogs love to chew bones.", "B2", "—", "—", "—"],
  ["bonus", "n.", "โบนัส", "Employees received a year-end bonus.", "B2", "—", "—", "—"],
  ["book", "n.", "หนังสือ", "She loves reading books.", "B2", "—", "—", "—"],
  ["book", "v.", "จอง", "Book your tickets online.", "B2", "—", "—", "—"],
  ["booklet", "n.", "小册子", "The booklet explains the instructions.", "B2", "—", "—", "—"],
  ["boom", "n.", "ระเบิด", "The explosion made a loud boom.", "B2", "—", "—", "—"],
  ["booth", "n.", "บูธ", "Meet me at the booth.", "B2", "—", "—", "—"],

  // ===== DAY 12-20 (B2) - Continued =====
  ["border", "n.", "พรมแดน", "The border between the countries is strict.", "B2", "—", "—", "—"],
  ["bore", "v.", "เบื่อ", "Waiting bores me.", "B2", "—", "—", "—"],
  ["born", "adj.", "เกิด", "She was born in 1990.", "B2", "—", "—", "—"],
  ["borrow", "v.", "ยืม", "Can I borrow your pen?", "B2", "—", "—", "—"],
  ["boss", "n.", "เจ้านาย", "My boss is very strict.", "B2", "—", "—", "—"],
  ["both", "det.", "ทั้งสอง", "Both options are good.", "B2", "—", "—", "—"],
  ["bottle", "n.", "ขวด", "The water bottle is empty.", "B2", "—", "—", "—"],
  ["bottom", "n.", "ก้น", "The bottom of the bottle is clean.", "B2", "—", "—", "—"],
  ["bounce", "v.", "กระเด้ง", "The ball bounced high.", "B2", "—", "—", "—"],
  ["bound", "adj.", "ผูกไว้", "The books are bound together.", "B2", "—", "—", "—"],
  ["boundary", "n.", "เส้นแบ่งเขต", "The fence marks the boundary.", "B2", "—", "—", "—"],
  ["bouquet", "n.", "ช่อดอก", "He gave her a bouquet of roses.", "B2", "—", "—", "—"],
  ["bow", "n.", "โบว์", "She tied a bow on the gift.", "B2", "—", "—", "—"],
  ["bow", "v.", "โค่ย", "The player bowed to the audience.", "B2", "—", "—", "—"],
  ["bowl", "n.", "ชาม", "The soup is served in a bowl.", "B2", "—", "—", "—"],
  ["box", "n.", "กล่อง", "The package was in a cardboard box.", "B2", "—", "—", "—"],
  ["boy", "n.", "เด็กชาย", "The boy played in the park.", "B2", "—", "—", "—"],
  ["boyfriend", "n.", "แฟนชาย", "Her boyfriend is very handsome.", "B2", "—", "—", "—"],
  ["brace", "v.", "เตรียม", "Brace yourself for bad news.", "B2", "—", "—", "—"],
  ["bracket", "n.", "วงเล็บ", "Put the word in brackets.", "B2", "—", "—", "—"],
  ["brain", "n.", "สมอง", "Exercise is good for the brain.", "B2", "—", "—", "—"],
  ["brake", "n.", "เบรก", "Step on the brake to stop.", "B2", "—", "—", "—"],
  ["branch", "n.", "กิ่ง", "The tree has many branches.", "B2", "—", "—", "—"],
  ["brand", "n.", "แบรนด์", "This brand is very popular.", "B2", "—", "—", "—"],
  ["brass", "n.", "ทองเหลือง", "A brass band performed.", "B2", "—", "—", "—"],
  ["brave", "adj.", "กล้าหาญ", "She was brave during the crisis.", "B2", "—", "—", "—"],
  ["bread", "n.", "ขนมปัง", "Fresh bread tastes delicious.", "B2", "—", "—", "—"],
  ["break", "v.", "แตกหัก", "Be careful not to break the glass.", "B2", "—", "—", "—"],
  ["breakfast", "n.", "อาหารเช้า", "Breakfast is the most important meal.", "B2", "—", "—", "—"],
  ["breast", "n.", "หน้าอก", "Chicken breast is healthy meat.", "B2", "—", "—", "—"],

  // ===== DAY 13-15 (B2) - Continued =====
  ["breath", "n.", "ลมหายใจ", "Take a deep breath.", "B2", "—", "—", "—"],
  ["breathe", "v.", "หายใจ", "Breathe slowly and deeply.", "B2", "—", "—", "—"],
  ["breed", "v.", "ปล่อยให้พันธุ์", "They breed dogs as a hobby.", "B2", "—", "—", "—"],
  ["breeze", "n.", "ลมสบาย", "A cool breeze blew through the window.", "B2", "—", "—", "—"],
  ["brick", "n.", "อิฐ", "The house is made of brick.", "B2", "—", "—", "—"],
  ["bride", "n.", "เจ้าสาว", "The bride looked beautiful.", "B2", "—", "—", "—"],
  ["bridge", "n.", "สะพาน", "The bridge connects two cities.", "B2", "—", "—", "—"],
  ["brief", "adj.", "สั้น", "Keep your speech brief.", "B2", "—", "—", "—"],
  ["briefly", "adv.", "เพียงสั้นๆ", "She spoke briefly about the project.", "B2", "—", "—", "—"],
  ["bright", "adj.", "สว่าง", "The room is bright and cheerful.", "B2", "—", "—", "—"],
  ["brilliant", "adj.", "เจิด", "She had a brilliant idea.", "B2", "—", "—", "—"],
  ["bring", "v.", "นำมา", "Please bring your ID.", "B2", "—", "—", "—"],
  ["brink", "n.", "ขอบ", "The country is on the brink of war.", "B2", "—", "—", "—"],
  ["brisk", "adj.", "เร็วจัง", "They took a brisk walk.", "B2", "—", "—", "—"],
  ["broad", "adj.", "กว้าง", "The broad street has many shops.", "B2", "—", "—", "—"],
  ["broadcast", "v.", "ออกอากาศ", "The station broadcasts news hourly.", "B2", "—", "—", "—"],
  ["broken", "adj.", "แตกหัก", "The broken vase cannot be fixed.", "B2", "—", "—", "—"],
  ["bronze", "n.", "ทองแดง", "A bronze statue stands in the square.", "B2", "—", "—", "—"],
  ["brook", "n.", "ลำธาร", "A small brook runs through the forest.", "B2", "—", "—", "—"],
  ["broom", "n.", "ไม้กวาด", "Sweep with a broom.", "B2", "—", "—", "—"],
  ["brother", "n.", "พี่ชาย", "My brother is in the army.", "B2", "—", "—", "—"],
  ["brought", "v.", "นำมา", "She brought flowers to the party.", "B2", "—", "—", "—"],
  ["brown", "adj.", "สีน้ำตาล", "He wore brown shoes.", "B2", "—", "—", "—"],
  ["browse", "v.", "เบราว์", "She browsed the internet.", "B2", "—", "—", "—"],
  ["bruise", "n.", "ลักษณ์ของการกระแทก", "She had a bruise on her arm.", "B2", "—", "—", "—"],
  ["brutal", "adj.", "โหด", "War is brutal and destructive.", "B2", "—", "—", "—"],
  ["brush", "n.", "แปรง", "Use a brush to paint.", "B2", "—", "—", "—"],
  ["bubble", "n.", "ฟอง", "Bubbles rose from the bottom.", "B2", "—", "—", "—"],
  ["bucket", "n.", "ถัง", "Fill the bucket with water.", "B2", "—", "—", "—"],
  ["budget", "n.", "งบประมาณ", "The budget is very tight.", "B2", "—", "—", "—"],

  // ===== DAY 16-20 (B2) - Final batch for B2 =====
  ["buffer", "n.", "บัฟเฟอร์", "A buffer protects the device.", "B2", "—", "—", "—"],
  ["bug", "n.", "แมลง", "An insect is a small bug.", "B2", "—", "—", "—"],
  ["build", "v.", "สร้าง", "They build houses from wood.", "B2", "—", "—", "—"],
  ["building", "n.", "อาคาร", "The building is very tall.", "B2", "—", "—", "—"],
  ["bulb", "n.", "หลอด", "Change the light bulb.", "B2", "—", "—", "—"],
  ["bulk", "n.", "ปริมาณมาก", "They buy in bulk.", "B2", "—", "—", "—"],
  ["bullet", "n.", "กระสุน", "The bullet went through the wall.", "B2", "—", "—", "—"],
  ["bump", "v.", "ชน", "I bumped my head on the door.", "B2", "—", "—", "—"],
  ["bunch", "n.", "มัด", "A bunch of bananas is heavy.", "B2", "—", "—", "—"],
  ["bundle", "n.", "ชุด", "A bundle of newspapers arrived.", "B2", "—", "—", "—"],
  ["burden", "n.", "ภาระ", "The burden is too heavy.", "B2", "—", "—", "—"],
  ["bureau", "n.", "สำนัก", "The travel bureau offers tours.", "B2", "—", "—", "—"],
  ["burger", "n.", "เบอร์เกอร์", "I ordered a cheese burger.", "B2", "—", "—", "—"],
  ["burial", "n.", "การฝัง", "The burial ceremony was touching.", "B2", "—", "—", "—"],
  ["burn", "v.", "ไหม้", "The candle burns brightly.", "B2", "—", "—", "—"],
  ["burst", "v.", "ระเบิด", "The balloon burst with a loud pop.", "B2", "—", "—", "—"],
  ["bus", "n.", "รถเมล์", "The bus is crowded today.", "B2", "—", "—", "—"],
  ["bush", "n.", "灌木", "A rose bush grows in the garden.", "B2", "—", "—", "—"],
  ["business", "n.", "ธุรกิจ", "She runs a successful business.", "B2", "—", "—", "—"],
  ["busy", "adj.", "ยุ่ง", "I'm too busy to help.", "B2", "—", "—", "—"],
  ["but", "conj.", "แต่", "I like coffee but not tea.", "B2", "—", "—", "—"],
  ["butter", "n.", "เนย", "Spread butter on the bread.", "B2", "—", "—", "—"],
  ["butterfly", "n.", "ผีเสื้อ", "A butterfly landed on the flower.", "B2", "—", "—", "—"],
  ["button", "n.", "ปุ่ม", "Press the button to start.", "B2", "—", "—", "—"],
  ["buy", "v.", "ซื้อ", "I buy groceries every week.", "B2", "—", "—", "—"],
  ["buyer", "n.", "ผู้ซื้อ", "The buyer negotiated a better price.", "B2", "—", "—", "—"],
  ["buzz", "n.", "เสียงวิวเวียน", "I heard a buzz from the speakers.", "B2", "—", "—", "—"],
  ["by", "prep.", "โดย", "The book was written by a famous author.", "B2", "—", "—", "—"],
  ["bye", "exclam.", "สวัสดี", "Bye! See you later.", "B2", "—", "—", "—"],
  ["cable", "n.", "สายเคเบิล", "The cable connects the devices.", "B2", "—", "—", "—"],

  // ===== DAY 21-30 (C1 LEVEL) =====
  ["calculate", "v.", "คำนวณ", "Calculate the total cost.", "C1", "—", "—", "—"],
  ["calculation", "n.", "การคำนวณ", "The calculation is correct.", "C1", "—", "—", "—"],
  ["calendar", "n.", "ปฏิทิน", "Mark the date on your calendar.", "C1", "—", "—", "—"],
  ["caliber", "n.", "คุณภาพ", "His work is of high caliber.", "C1", "—", "—", "—"],
  ["call", "v.", "โทร", "Call me when you arrive.", "C1", "—", "—", "—"],
  ["calling", "n.", "อาชีพ", "Teaching is her calling.", "C1", "—", "—", "—"],
  ["callous", "adj.", "เหนียว", "His callous behavior hurt her feelings.", "C1", "—", "—", "—"],
  ["calm", "adj.", "สงบ", "The calm water reflected the sky.", "C1", "—", "—", "—"],
  ["calmly", "adv.", "อย่างสงบ", "She spoke calmly despite the crisis.", "C1", "—", "—", "—"],
  ["calorie", "n.", "แคลอรี่", "This food has few calories.", "C1", "—", "—", "—"],
  ["camel", "n.", "อูฐ", "Camels can survive in deserts.", "C1", "—", "—", "—"],
  ["camera", "n.", "กล้อง", "Take a photo with the camera.", "C1", "—", "—", "—"],
  ["campaign", "n.", "การรณรงค์", "The political campaign lasted months.", "C1", "—", "—", "—"],
  ["campus", "n.", "วิทยาเขต", "The campus is very large.", "C1", "—", "—", "—"],
  ["canal", "n.", "คลอง", "Venice has many canals.", "C1", "—", "—", "—"],
  ["cancel", "v.", "ยกเลิก", "Cancel the appointment please.", "C1", "—", "—", "—"],
  ["cancellation", "n.", "การยกเลิก", "The cancellation was sudden.", "C1", "—", "—", "—"],
  ["cancer", "n.", "มะเร็ง", "Cancer is a serious disease.", "C1", "—", "—", "—"],
  ["candidate", "n.", "ผู้สมัคร", "The candidate gave a speech.", "C1", "—", "—", "—"],
  ["candle", "n.", "เทียน", "Light the candle for dinner.", "C1", "—", "—", "—"],
  ["candy", "n.", "ลูกกวาด", "Children love candy.", "C1", "—", "—", "—"],
  ["canine", "adj.", "เกี่ยวกับสุนัข", "Canine teeth are sharp.", "C1", "—", "—", "—"],
  ["cannabis", "n.", "กัญชา", "Cannabis use is controversial.", "C1", "—", "—", "—"],
  ["cannot", "v.", "ไม่สามารถ", "I cannot help you today.", "C1", "—", "—", "—"],
  ["canoe", "n.", "เรือแจว", "We paddled the canoe downstream.", "C1", "—", "—", "—"],
  ["canon", "n.", "หลักเกณฑ์", "The literary canon includes classics.", "C1", "—", "—", "—"],
  ["canopy", "n.", "ร่มไม้", "The forest canopy is dense.", "C1", "—", "—", "—"],
  ["cantaloupe", "n.", "แคนตาลูป", "Cantaloupe is a sweet fruit.", "C1", "—", "—", "—"],
  ["canvas", "n.", "ผ้าใบ", "Paint on canvas for best results.", "C1", "—", "—", "—"],
  ["canyon", "n.", "หุบเขา", "The Grand Canyon is spectacular.", "C1", "—", "—", "—"],
  ["capability", "n.", "ความสามารถ", "His capability is beyond question.", "C1", "—", "—", "—"],
  ["capable", "adj.", "มีความสามารถ", "She is capable of great things.", "C1", "—", "—", "—"],
  ["capacity", "n.", "ความจุ", "The stadium has a capacity of 50,000.", "C1", "—", "—", "—"],
  ["cape", "n.", "แหลม", "The ship sailed past the cape.", "C1", "—", "—", "—"],
  ["capital", "n.", "เมืองหลวง", "Paris is the capital of France.", "C1", "—", "—", "—"],
  ["capitalism", "n.", "ระบบทุนนิยม", "Capitalism drives economic growth.", "C1", "—", "—", "—"],
  ["captain", "n.", "กัปตัน", "The captain commands the ship.", "C1", "—", "—", "—"],
  ["caption", "n.", "ข้อความอธิบายรูป", "The caption explains the photo.", "C1", "—", "—", "—"],
  ["captive", "adj.", "เป็นเชลย", "The captive animals were rescued.", "C1", "—", "—", "—"],
  ["captivity", "n.", "การถูกกักขัง", "The bird was released from captivity.", "C1", "—", "—", "—"],
  ["capture", "v.", "จับ", "The police captured the criminal.", "C1", "—", "—", "—"],
  ["car", "n.", "รถยนต์", "I drive a red car.", "C1", "—", "—", "—"],
  ["caravan", "n.", "คณะสัญจร", "A caravan of traders traveled through the desert.", "C1", "—", "—", "—"],
  ["carbon", "n.", "คาร์บอน", "Carbon dioxide contributes to global warming.", "C1", "—", "—", "—"],
  ["carburetor", "n.", "คาร์บูเรเตอร์", "The carburetor needs cleaning.", "C1", "—", "—", "—"],
  ["carcass", "n.", "ศพ", "The carcass of the animal decomposed.", "C1", "—", "—", "—"],
  ["carcinogen", "n.", "สารก่อมะเร็ง", "Tobacco is a known carcinogen.", "C1", "—", "—", "—"],
  ["cardinal", "adj.", "พื้นฐาน", "Cardinal sin is the most serious.", "C1", "—", "—", "—"],
  ["care", "v.", "ดูแล", "Care for the plants daily.", "C1", "—", "—", "—"],
  ["career", "n.", "อาชีพ", "She has a successful career.", "C1", "—", "—", "—"],
  ["careful", "adj.", "ระมัดระวัง", "Be careful with the glass.", "C1", "—", "—", "—"],
  ["careless", "adj.", "ประมาท", "His careless mistake cost money.", "C1", "—", "—", "—"],
  ["caress", "v.", "สัมผัส", "She caressed the child's head.", "C1", "—", "—", "—"],
  ["caretaker", "n.", "ผู้รักษา", "The caretaker maintains the building.", "C1", "—", "—", "—"],
  ["cargo", "n.", "สินค้า", "The ship carries valuable cargo.", "C1", "—", "—", "—"],
  ["caribou", "n.", "กวางอเมริกา", "Caribou migrate in herds.", "C1", "—", "—", "—"],
  ["carnival", "n.", "งานกาดวิสยา", "The carnival is full of attractions.", "C1", "—", "—", "—"],
  ["carnivore", "n.", "สัตว์กินเนื้อ", "A lion is a carnivore.", "C1", "—", "—", "—"],
  ["carol", "n.", "เพลงคริสต์มาส", "They sang Christmas carols.", "C1", "—", "—", "—"],
  ["carouse", "v.", "สุมศรี", "They caroused late into the night.", "C1", "—", "—", "—"],
  ["carousel", "n.", "ม้าหมุน", "The carousel spun rapidly.", "C1", "—", "—", "—"],
  ["carp", "n.", "ปลาคาร์พ", "Carp are freshwater fish.", "C1", "—", "—", "—"],
  ["carpenter", "n.", "ช่างไม้", "The carpenter built the cabinet.", "C1", "—", "—", "—"],
  ["carpet", "n.", "พรม", "The carpet is soft and warm.", "C1", "—", "—", "—"],
  ["carriage", "n.", "รถม้า", "The royal carriage was ornate.", "C1", "—", "—", "—"],
  ["carrier", "n.", "ผู้ขนส่ง", "The carrier delivered the package.", "C1", "—", "—", "—"],
  ["carrion", "n.", "ศพสัตว์", "Vultures feed on carrion.", "C1", "—", "—", "—"],
  ["carrot", "n.", "แครอท", "Carrots are rich in vitamin A.", "C1", "—", "—", "—"],
  ["carry", "v.", "เหาะ", "Carry the bags carefully.", "C1", "—", "—", "—"],
  ["cart", "n.", "เกวียน", "Push the shopping cart.", "C1", "—", "—", "—"],
  ["cartage", "n.", "ค่าการขนส่ง", "Cartage is included in the price.", "C1", "—", "—", "—"],
  ["cartel", "n.", "การรวมตัว", "The oil cartel controls prices.", "C1", "—", "—", "—"],
  ["cartilage", "n.", "กระดูกอ่อน", "Cartilage connects bones.", "C1", "—", "—", "—"],
  ["cartography", "n.", "ศิลปการทำแผนที่", "Cartography is the art of mapmaking.", "C1", "—", "—", "—"],
  ["carton", "n.", "กล่องกระดาษ", "The milk carton is empty.", "C1", "—", "—", "—"],
  ["cartoon", "n.", "การ์ตูน", "Children watch cartoons.", "C1", "—", "—", "—"],
  ["cartridge", "n.", "แคตริดจ์", "Replace the printer cartridge.", "C1", "—", "—", "—"],
  ["carve", "v.", "แกะสลัก", "Carve the turkey for dinner.", "C1", "—", "—", "—"],
  ["cascade", "n.", "น้ำตกน้อย", "The cascade of water was beautiful.", "C1", "—", "—", "—"],
  ["case", "n.", "กรณี", "In this case, we must act.", "C1", "—", "—", "—"],
  ["casement", "n.", "บานหน้าต่าง", "The casement window opens wide.", "C1", "—", "—", "—"],
  ["cash", "n.", "เงินสด", "I prefer to pay in cash.", "C1", "—", "—", "—"],
  ["cashew", "n.", "เมล็ดมะม่วงหิมพานต์", "Cashews are expensive nuts.", "C1", "—", "—", "—"],
  ["cashier", "n.", "เก็บเงิน", "The cashier scanned the items.", "C1", "—", "—", "—"],
  ["cashmere", "n.", "สไตร์ม", "Cashmere is soft and warm.", "C1", "—", "—", "—"],
  ["casing", "n.", "เปลือก", "The sausage casing is natural.", "C1", "—", "—", "—"],
  ["casino", "n.", "คาสิโน", "The casino offers many games.", "C1", "—", "—", "—"],
  ["casket", "n.", "棺木", "The casket was made of oak.", "C1", "—", "—", "—"],
  ["cassava", "n.", "มันสำปะหลัง", "Cassava is a starchy root.", "C1", "—", "—", "—"],
  ["cassette", "n.", "แคสเซ็ต", "The cassette tape was worn.", "C1", "—", "—", "—"],
  ["cast", "v.", "ทำให้", "Cast your vote on election day.", "C1", "—", "—", "—"],
  ["castaway", "n.", "ผู้ที่ลอยไปถมเศษเหลือ", "The castaway was rescued.", "C1", "—", "—", "—"],
  ["caste", "n.", "ชนชั้น", "The caste system is hierarchical.", "C1", "—", "—", "—"],
  ["castigate", "v.", "ตำหนิ", "The teacher castigated the student.", "C1", "—", "—", "—"],
  ["castle", "n.", "ปราสาท", "The castle overlooks the valley.", "C1", "—", "—", "—"],
  ["castor", "n.", "ล้อ", "The castor oil is medicinal.", "C1", "—", "—", "—"],
  ["castrate", "v.", "อพยพชาย", "Farmers castrate livestock.", "C1", "—", "—", "—"],
  ["casual", "adj.", "ไม่เป็นทางการ", "Wear casual clothes to the party.", "C1", "—", "—", "—"],
  ["casualty", "n.", "ผู้บาดเจ็บ", "There were many casualties.", "C1", "—", "—", "—"],
  ["casuistry", "n.", "การโต้เถียงโดยใช้กลอุบาย", "His casuistry was transparent.", "C1", "—", "—", "—"],
  ["cat", "n.", "แมว", "The cat is sleeping.", "C1", "—", "—", "—"],
  ["cataclysm", "n.", "ปัญหาใหญ่โต", "The earthquake was a cataclysm.", "C1", "—", "—", "—"],
  ["catacomb", "n.", "อุโมงค์ใต้ดิน", "The catacombs are beneath the city.", "C1", "—", "—", "—"],
  ["catalogue", "n.", "แคตตาล็อก", "Browse the online catalogue.", "C1", "—", "—", "—"],
  ["catalyst", "n.", "ตัวเร่ง", "A catalyst speeds up reactions.", "C1", "—", "—", "—"],
  ["catamaran", "n.", "เรือสองลำ", "The catamaran is fast.", "C1", "—", "—", "—"],
  ["catapult", "v.", "ขว้าง", "The launcher catapults the projectile.", "C1", "—", "—", "—"],
  ["cataract", "n.", "บวนน้ำตก", "Cataracts develop with age.", "C1", "—", "—", "—"],
  ["catastrophe", "n.", "ภัยพิบัติ", "The disaster was a catastrophe.", "C1", "—", "—", "—"],
  ["catastrophic", "adj.", "หายนะ", "The results were catastrophic.", "C1", "—", "—", "—"],
  ["catcall", "n.", "เสียงหวั่นใจ", "Catcalls from the audience.", "C1", "—", "—", "—"],
  ["catch", "v.", "จับ", "Try to catch the ball.", "C1", "—", "—", "—"],
  ["catcher", "n.", "ผู้จับ", "The catcher threw to third base.", "C1", "—", "—", "—"],
  ["catching", "adj.", "ติดต่อได้", "A catching melody is memorable.", "C1", "—", "—", "—"],
  ["catchy", "adj.", "จำได้ง่าย", "The song is very catchy.", "C1", "—", "—", "—"],
  ["catechism", "n.", "การสอน", "The catechism teaches faith.", "C1", "—", "—", "—"],
  ["categorical", "adj.", "เด็ดขาด", "His refusal was categorical.", "C1", "—", "—", "—"],
  ["categorize", "v.", "จำแนก", "Categorize the books by genre.", "C1", "—", "—", "—"],
  ["category", "n.", "หมวดหมู่", "Choose a category for your question.", "C1", "—", "—", "—"],
  ["cater", "v.", "บริการ", "The restaurant caters to tourists.", "C1", "—", "—", "—"],
  ["caterer", "n.", "ผู้จัดเลี้ยง", "The caterer prepared the meal.", "C1", "—", "—", "—"],
  ["caterpillar", "n.", "หนอนผีเสื้อ", "The caterpillar crawled on the leaf.", "C1", "—", "—", "—"],
  ["catfish", "n.", "ปลาค้อก", "Catfish are bottom feeders.", "C1", "—", "—", "—"],
  ["catgut", "n.", "สายกีต้าร์", "Catgut was used for strings.", "C1", "—", "—", "—"],
  ["cathartic", "adj.", "หรือนฤมิตรรมเชิง", "The movie was cathartic.", "C1", "—", "—", "—"],
  ["cathedral", "n.", "วิหาร", "The cathedral is magnificent.", "C1", "—", "—", "—"],
  ["catheter", "n.", "สายสวนปัสสาวะ", "The catheter was inserted carefully.", "C1", "—", "—", "—"],
  ["cathode", "n.", "แคโทด", "The cathode attracts electrons.", "C1", "—", "—", "—"],
  ["catholic", "adj.", "กว้างขวาง", "His taste is catholic.", "C1", "—", "—", "—"],
  ["Catholic", "n.", "สัตรญ", "She is a practicing Catholic.", "C1", "—", "—", "—"],
  ["catnap", "n.", "การหลับสั้นๆ", "I'll take a catnap.", "C1", "—", "—", "—"],
  ["catkin", "n.", "ลูกดอกแมว", "The catkins fell from the willow.", "C1", "—", "—", "—"],
  ["catnip", "n.", "หญ้าแมว", "Cats love catnip.", "C1", "—", "—", "—"],
  ["cattle", "n.", "วัว", "Cattle graze in the field.", "C1", "—", "—", "—"],
  ["catty", "adj.", "เจ้าเล่นตลก", "Her catty remarks hurt feelings.", "C1", "—", "—", "—"],
  ["catwalk", "n.", "สะพานแคทวอล์ค", "Models strut on the catwalk.", "C1", "—", "—", "—"],
  ["caucus", "n.", "การประชุมสนใจ", "A political caucus met.", "C1", "—", "—", "—"],
  ["caudal", "adj.", "เกี่ยวกับหาง", "The caudal fin of fish.", "C1", "—", "—", "—"],
  ["caught", "v.", "จับได้", "He caught the fish.", "C1", "—", "—", "—"],
  ["cauldron", "n.", "หม้อใหญ่", "Witches stirred the cauldron.", "C1", "—", "—", "—"],
  ["caulk", "v.", "อุดรอยรั่ว", "Caulk the window frame.", "C1", "—", "—", "—"],
  ["causal", "adj.", "เกี่ยวกับเหตุ", "The causal relationship is clear.", "C1", "—", "—", "—"],
  ["causality", "n.", "ความเป็นสาเหตุ", "Causality is a philosophical concept.", "C1", "—", "—", "—"],
  ["causation", "n.", "ความเป็นเหตุ", "Causation is difficult to prove.", "C1", "—", "—", "—"],
  ["causative", "adj.", "ก่อเหตุ", "A causative verb shows action.", "C1", "—", "—", "—"],
  ["cause", "n.", "เหตุ", "The cause of the accident is unknown.", "C1", "—", "—", "—"],
  ["cause", "v.", "ทำให้เกิด", "The rain caused flooding.", "C1", "—", "—", "—"],
  ["causeway", "n.", "ทางเดินข้ามน้ำ", "The causeway connects the islands.", "C1", "—", "—", "—"],
  ["caustic", "adj.", "ขาด", "His caustic remarks were hurtful.", "C1", "—", "—", "—"],
  ["caution", "n.", "การเตือน", "Proceed with caution.", "C1", "—", "—", "—"],
  ["cautionary", "adj.", "เพื่อให้รู้อันตรัย", "A cautionary tale.", "C1", "—", "—", "—"],
  ["cautious", "adj.", "ระมัดระวัง", "Be cautious with fire.", "C1", "—", "—", "—"],
  ["cavalcade", "n.", "ขบวนม้า", "A cavalcade of knights.", "C1", "—", "—", "—"],
  ["cavalier", "adj.", "ไม่สนใจ", "His cavalier attitude annoyed me.", "C1", "—", "—", "—"],
  ["cavalry", "n.", "กองทหารม้า", "Cavalry charges were fearsome.", "C1", "—", "—", "—"],
  ["cave", "n.", "ถ้ำ", "The cave is dark and damp.", "C1", "—", "—", "—"],
  ["caveat", "n.", "ข้อเตือน", "There are caveats to this plan.", "C1", "—", "—", "—"],
  ["cavern", "n.", "ถ้ำใหญ่", "The cavern echoed loudly.", "C1", "—", "—", "—"],
  ["cavernous", "adj.", "เหมือนถ้ำ", "His cavernous office was empty.", "C1", "—", "—", "—"],
  ["caviar", "n.", "ไข่ปลาแบล็ก", "Caviar is an expensive delicacy.", "C1", "—", "—", "—"],
  ["cavil", "v.", "ติแปง", "Don't cavil about minor issues.", "C1", "—", "—", "—"],
  ["cavity", "n.", "โพรง", "The dental cavity needed filling.", "C1", "—", "—", "—"],
  ["cavort", "v.", "เต้นรำ", "The children cavorted happily.", "C1", "—", "—", "—"],
  ["caw", "n.", "เสียงนก", "The caw of the crow rang out.", "C1", "—", "—", "—"],
  ["cayenne", "n.", "พริกแคเยน", "Cayenne pepper is spicy.", "C1", "—", "—", "—"],
  ["cayuse", "n.", "ม้าเล็ก", "The cayuse horse is sturdy.", "C1", "—", "—", "—"],
  ["cease", "v.", "หยุด", "The fighting ceased at dawn.", "C1", "—", "—", "—"],
  ["ceaseless", "adj.", "ไม่มีที่สิ้นสุด", "The ceaseless rain was depressing.", "C1", "—", "—", "—"],
  ["cedar", "n.", "สนสีดำ", "Cedar wood smells pleasant.", "C1", "—", "—", "—"],
  ["cede", "v.", "ยอมให้", "They ceded the territory.", "C1", "—", "—", "—"],
  ["cedilla", "n.", "เครื่องหมายลากา", "The cedilla marks a pronunciation.", "C1", "—", "—", "—"],
  ["ceiling", "n.", "เพดาน", "The ceiling needs repair.", "C1", "—", "—", "—"],
  ["celebrate", "v.", "เฉลิมฉลอง", "Celebrate your birthday!", "C1", "—", "—", "—"],
  ["celebration", "n.", "การเฉลิมฉลอง", "The celebration lasted all night.", "C1", "—", "—", "—"],
  ["celebrity", "n.", "ดารา", "He is a famous celebrity.", "C1", "—", "—", "—"],
  ["celerity", "n.", "ความรวดเร็ว", "He acted with celerity.", "C1", "—", "—", "—"],
  ["celery", "n.", "คะน้า", "Celery is a healthy vegetable.", "C1", "—", "—", "—"],
  ["celestial", "adj.", "สวรรค์", "Celestial bodies include stars.", "C1", "—", "—", "—"],
  ["celibacy", "n.", "การไม่สมรส", "Celibacy is a vow for monks.", "C1", "—", "—", "—"],
  ["celibate", "adj.", "โสดไม่มีสมรส", "Celibate priests serve the church.", "C1", "—", "—", "—"],
  ["cell", "n.", "เซลล์", "A cell is the basic unit of life.", "C1", "—", "—", "—"],
  ["cellar", "n.", "ห้องใต้ดิน", "The cellar is cold.", "C1", "—", "—", "—"],
  ["cellulose", "n.", "เซลลูโลส", "Paper contains cellulose.", "C1", "—", "—", "—"],
  ["cellular", "adj.", "เกี่ยวกับเซลล์", "Cellular phones are common.", "C1", "—", "—", "—"],
  ["cement", "n.", "ปูน", "Concrete contains cement.", "C1", "—", "—", "—"],
  ["cemetery", "n.", "สุสาน", "The cemetery is peaceful.", "C1", "—", "—", "—"],
  ["cenotaph", "n.", "อนุสรณ์สถาน", "A cenotaph honors the deceased.", "C1", "—", "—", "—"],
  ["censer", "n.", "สำลีธูป", "The censer swung in the church.", "C1", "—", "—", "—"],
  ["censor", "v.", "เซนเซอร์", "Don't censor free speech.", "C1", "—", "—", "—"],
  ["censorious", "adj.", "ชอบตำหนิ", "His censorious nature alienated friends.", "C1", "—", "—", "—"],
  ["censorship", "n.", "การเซนเซอร์", "Censorship limits information.", "C1", "—", "—", "—"],
  ["censure", "n.", "การตำหนิ", "He received censure from colleagues.", "C1", "—", "—", "—"],
  ["census", "n.", "สำมะโนประชากร", "The census counts population.", "C1", "—", "—", "—"],
  ["cent", "n.", "เซนต์", "A cent is 1/100 of a dollar.", "C1", "—", "—", "—"],
  ["centaur", "n.", "เซนทอร์", "Mythology includes centaurs.", "C1", "—", "—", "—"],
  ["centenary", "n.", "ศตวรรษ", "The centenary celebration was grand.", "C1", "—", "—", "—"],
  ["centennial", "adj.", "ร้อยปี", "The centennial event was special.", "C1", "—", "—", "—"],
  ["center", "n.", "ศูนย์กลาง", "The center of the circle.", "C1", "—", "—", "—"],
  ["centigrade", "adj.", "องศาเซลเซียส", "Water boils at 100 centigrade.", "C1", "—", "—", "—"],
  ["centigram", "n.", "เซนติกรัม", "A centigram is 1/100 of a gram.", "C1", "—", "—", "—"],
  ["centiliter", "n.", "เซนติลิตร", "A centiliter is 1/100 of a liter.", "C1", "—", "—", "—"],
  ["centimeter", "n.", "เซนติเมตร", "A centimeter is 1/100 of a meter.", "C1", "—", "—", "—"],
  ["centipede", "n.", "แมลงเซ้นติพีด", "A centipede has many legs.", "C1", "—", "—", "—"],
  ["central", "adj.", "ศูนย์กลาง", "The central location is convenient.", "C1", "—", "—", "—"],
  ["centralize", "v.", "รวมศูนย์", "Centralize the operations here.", "C1", "—", "—", "—"],
  ["centric", "adj.", "ที่ศูนย์กลาง", "An eccentric person is not centric.", "C1", "—", "—", "—"],
  ["centrifuge", "n.", "เครื่องหมุนเหวี่ยง", "The centrifuge separates substances.", "C1", "—", "—", "—"],
  ["centripetal", "adj.", "เข้าหาศูนย์", "Centripetal force pulls inward.", "C1", "—", "—", "—"],
  ["centurion", "n.", "นายพลโรมัน", "A centurion led the soldiers.", "C1", "—", "—", "—"],
  ["century", "n.", "ศตวรรษ", "A century is 100 years.", "C1", "—", "—", "—"],
  ["ceramic", "adj.", "เกี่ยวกับเซรามิก", "Ceramic tiles are durable.", "C1", "—", "—", "—"],
  ["cereal", "n.", "อาหารเช้า", "Eat cereal for breakfast.", "C1", "—", "—", "—"],
  ["cerebral", "adj.", "เกี่ยวกับสมอง", "Cerebral palsy affects movement.", "C1", "—", "—", "—"],
  ["cerebrum", "n.", "สมองใหญ่", "The cerebrum controls thinking.", "C1", "—", "—", "—"],
  ["ceremonial", "adj.", "พิธีการ", "Ceremonial dress is formal.", "C1", "—", "—", "—"],
  ["ceremonious", "adj.", "ทำนองการบูชา", "His ceremonious manner was formal.", "C1", "—", "—", "—"],
  ["ceremony", "n.", "พิธี", "The wedding ceremony was lovely.", "C1", "—", "—", "—"],
  ["cerise", "n.", "สีแดงสดใส", "Cerise is a bright red.", "C1", "—", "—", "—"],
  ["cerium", "n.", "เซเรียม", "Cerium is a rare element.", "C1", "—", "—", "—"],
  ["certain", "adj.", "แน่นอน", "I am certain of the truth.", "C1", "—", "—", "—"],
  ["certainty", "n.", "ความแน่นอน", "There is no certainty in life.", "C1", "—", "—", "—"],
  ["certifiable", "adj.", "สามารถรับรองได้", "His behavior is certifiable.", "C1", "—", "—", "—"],
  ["certificate", "n.", "ใบประกาศนียบัตร", "Receive your certificate.", "C1", "—", "—", "—"],
  ["certification", "n.", "การรับรอง", "Certification is required.", "C1", "—", "—", "—"],
  ["certified", "adj.", "ได้รับการรับรอง", "A certified accountant.", "C1", "—", "—", "—"],
  ["certify", "v.", "รับรอง", "Certify the documents.", "C1", "—", "—", "—"],
  ["certitude", "n.", "ความแน่นอน", "He spoke with certitude.", "C1", "—", "—", "—"],
  ["cerulean", "adj.", "สีฟ้า", "Cerulean skies are beautiful.", "C1", "—", "—", "—"],
  ["cervical", "adj.", "เกี่ยวกับคอ", "Cervical cancer is serious.", "C1", "—", "—", "—"],
  ["cervix", "n.", "ปากมดลูก", "The cervix is part of the uterus.", "C1", "—", "—", "—"],
  ["cessation", "n.", "การหยุด", "Cessation of fighting was ordered.", "C1", "—", "—", "—"],
  ["cession", "n.", "การมอบให้", "The cession of territory.", "C1", "—", "—", "—"],
  ["cesspool", "n.", "บ่อบำบัด", "The cesspool needs maintenance.", "C1", "—", "—", "—"],
  ["chafe", "v.", "ถูจนเป็นแผล", "The rope chafes the skin.", "C1", "—", "—", "—"],
  ["chaff", "n.", "เปลือกข้าว", "Separate the chaff from the grain.", "C1", "—", "—", "—"],
  ["chagrin", "n.", "ความทำให้อับอาย", "To his chagrin, he failed.", "C1", "—", "—", "—"],
  ["chain", "n.", "โซ่", "A chain is made of links.", "C1", "—", "—", "—"],
  ["chainsaw", "n.", "เลื่อยยนต์", "Use a chainsaw carefully.", "C1", "—", "—", "—"],
  ["chair", "n.", "เก้าอี้", "Sit on the chair.", "C1", "—", "—", "—"],
  ["chairman", "n.", "ประธาน", "The chairman called the meeting.", "C1", "—", "—", "—"],
  ["chairwoman", "n.", "ประธานหญิง", "The chairwoman led the discussion.", "C1", "—", "—", "—"],
  ["chaise", "n.", "เก้าอี้ยาว", "Recline on the chaise.", "C1", "—", "—", "—"],
  ["chalice", "n.", "ถ้วยศักดิ์สิทธิ์", "The chalice held wine.", "C1", "—", "—", "—"],
  ["chalk", "n.", "ชอล์ก", "Write with chalk on the board.", "C1", "—", "—", "—"],
  ["chalky", "adj.", "มีชอล์ก", "The soil is chalky.", "C1", "—", "—", "—"],
  ["challenge", "n.", "ความท้าทาย", "This task is a challenge.", "C1", "—", "—", "—"],
  ["challenging", "adj.", "ท้าทาย", "The challenging work rewards effort.", "C1", "—", "—", "—"],
  ["chamber", "n.", "ห้องโถง", "The royal chamber is ornate.", "C1", "—", "—", "—"],
  ["chamberlain", "n.", "ขุนฯหลวง", "The chamberlain served the king.", "C1", "—", "—", "—"],
  ["chambermaid", "n.", "พนักงานโรงแรม", "The chambermaid cleaned the room.", "C1", "—", "—", "—"],
  ["chameleon", "n.", "กิ้งก่า", "A chameleon changes color.", "C1", "—", "—", "—"],
  ["chamfer", "n.", "ขอบเฉือง", "A chamfer smooths the edge.", "C1", "—", "—", "—"],
  ["chamois", "n.", "หนังกวาง", "Chamois leather is soft.", "C1", "—", "—", "—"],
  ["champ", "v.", "กัด", "The horse champed its bit.", "C1", "—", "—", "—"],
  ["champagne", "n.", "แชมเปญ", "Celebrate with champagne.", "C1", "—", "—", "—"],
  ["champion", "n.", "แชมป์", "The champion won every match.", "C1", "—", "—", "—"],
  ["championship", "n.", "แชมเปี้ยนชิป", "The championship game was exciting.", "C1", "—", "—", "—"],
  ["chance", "n.", "โอกาส", "This is your chance.", "C1", "—", "—", "—"],
  ["chancel", "n.", "ส่วนหน้าโบสถ์", "The chancel has an altar.", "C1", "—", "—", "—"],
  ["chancellor", "n.", "นายกรัฐมนตรี", "The chancellor governs the state.", "C1", "—", "—", "—"],
  ["chancy", "adj.", "เสี่ยง", "That's a chancy decision.", "C1", "—", "—", "—"],
  ["chandelier", "n.", "โคมไฟระย้า", "The chandelier sparkled.", "C1", "—", "—", "—"],
  ["chandler", "n.", "ผู้ขายเทียน", "The chandler made candles.", "C1", "—", "—", "—"],
  ["chandlery", "n.", "ร้านขายเทียน", "The chandlery supplied ships.", "C1", "—", "—", "—"],
  ["change", "v.", "เปลี่ยน", "Change your clothes.", "C1", "—", "—", "—"],
  ["changeable", "adj.", "เปลี่ยนแปลงได้", "The weather is changeable.", "C1", "—", "—", "—"],
  ["changeling", "n.", "เด็กสลับ", "Folklore speaks of changelings.", "C1", "—", "—", "—"],
  ["channel", "n.", "ช่องทาง", "The water flows through a channel.", "C1", "—", "—", "—"],
  ["chant", "v.", "ร้องสวด", "Chant the mantra.", "C1", "—", "—", "—"],
  ["chantey", "n.", "เพลงคนเรือ", "Sailors sang a chantey.", "C1", "—", "—", "—"],
  ["chanticleer", "n.", "ไก่ตัวผู้", "The chanticleer crowed at dawn.", "C1", "—", "—", "—"],
  ["chap", "n.", "เพื่อน", "He is a good chap.", "C1", "—", "—", "—"],
  ["chaparral", "n.", "พื้นที่มีไม้อุ่นแห้ง", "The chaparral is dry landscape.", "C1", "—", "—", "—"],
  ["chapel", "n.", "โบสถ์เล็ก", "The chapel has beautiful windows.", "C1", "—", "—", "—"],
  ["chaplet", "n.", "การสวดมนต์", "A chaplet consists of prayers.", "C1", "—", "—", "—"],
  ["chapped", "adj.", "แตกเป็นรอยแตก", "Chapped lips are painful.", "C1", "—", "—", "—"],
  ["chapter", "n.", "บท", "Read chapter one.", "C1", "—", "—", "—"],
  ["char", "v.", "ไหม้เป็นลม", "Char the meat slightly.", "C1", "—", "—", "—"],
  ["character", "n.", "ตัวอักษร", "She has a strong character.", "C1", "—", "—", "—"],
  ["characteristic", "adj.", "เป็นลักษณะเฉพาะ", "His characteristic humor.", "C1", "—", "—", "—"],
  ["characterize", "v.", "ลักษณะ", "Characterize the situation.", "C1", "—", "—", "—"],
  ["charade", "n.", "เกมการแสดง", "They played charades.", "C1", "—", "—", "—"],
  ["charcoal", "n.", "ถ่านไม้", "Draw with charcoal.", "C1", "—", "—", "—"],
  ["charge", "v.", "เรียกเก็บ", "Charge the battery.", "C1", "—", "—", "—"],
  ["chariot", "n.", "รถม้าทำสงคราม", "Ancient armies used chariots.", "C1", "—", "—", "—"],
  ["charioteer", "n.", "คนขับรถม้า", "The charioteer drove skillfully.", "C1", "—", "—", "—"],
  ["charisma", "n.", "魅力", "He has great charisma.", "C1", "—", "—", "—"],
  ["charismatic", "adj.", "มีเสน่ห์ว่อน", "A charismatic leader.", "C1", "—", "—", "—"],
  ["charitable", "adj.", "เมตตา", "Show charitable heart.", "C1", "—", "—", "—"],
  ["charity", "n.", "การบริจาค", "Charity helps the poor.", "C1", "—", "—", "—"],
  ["charlatan", "n.", "หมอแก่", "The charlatan deceived patients.", "C1", "—", "—", "—"],
  ["charm", "n.", "เสน่ห์", "She has great charm.", "C1", "—", "—", "—"],
  ["charming", "adj.", "มีเสน่ห์", "A charming personality.", "C1", "—", "—", "—"],
  ["charred", "adj.", "ไหม้เป็นอย่างไร", "Charred remains.", "C1", "—", "—", "—"],
  ["chart", "n.", "แผนภูมิ", "Study the chart.", "C1", "—", "—", "—"],
  ["charter", "n.", "บัตรสัมปทาน", "The charter grants rights.", "C1", "—", "—", "—"],
  ["chartreuse", "n.", "สีเขียว", "Chartreuse is yellowish green.", "C1", "—", "—", "—"],
  ["chartwoman", "n.", "ผู้เก็บความสะอาด", "The chartwoman cleaned.", "C1", "—", "—", "—"],
  ["chary", "adj.", "ระมัดระวัง", "Be chary of strangers.", "C1", "—", "—", "—"],
  ["chase", "v.", "ตาม", "Chase the ball.", "C1", "—", "—", "—"],
  ["chasm", "n.", "หว่าง", "A wide chasm divided them.", "C1", "—", "—", "—"],
  ["chassis", "n.", "โครงรถ", "The chassis supports the body.", "C1", "—", "—", "—"],
  ["chaste", "adj.", "บริสุทธิ์", "Chaste behavior is moral.", "C1", "—", "—", "—"],
  ["chasten", "v.", "ตำหนิ", "Chasten the proud.", "C1", "—", "—", "—"],
  ["chastise", "v.", "ตีสอน", "Chastise the wrongdoer.", "C1", "—", "—", "—"],
  ["chastisement", "n.", "การลงโทษ", "Chastisement is discipline.", "C1", "—", "—", "—"],
  ["chastity", "n.", "ความบริสุทธิ์", "Chastity is a virtue.", "C1", "—", "—", "—"],
  ["chat", "v.", "คุยกัน", "Chat with friends.", "C1", "—", "—", "—"],
  ["chattel", "n.", "ทรัพย์สิน", "Chattels are personal property.", "C1", "—", "—", "—"],
  ["chatter", "v.", "พูดถาม", "The children chattered loudly.", "C1", "—", "—", "—"],
  ["chatty", "adj.", "พูดเยอะ", "She is chatty and friendly.", "C1", "—", "—", "—"],
  ["chauffeur", "n.", "คนขับรถ", "The chauffeur drove carefully.", "C1", "—", "—", "—"],
  ["cheap", "adj.", "ถูก", "This shirt is cheap.", "C1", "—", "—", "—"],
  ["cheapen", "v.", "ทำให้ตกต่ำ", "Cheapen the value.", "C1", "—", "—", "—"],
  ["cheaply", "adv.", "ราคาถูก", "Buy cheaply.", "C1", "—", "—", "—"],
  ["cheapskate", "n.", "คนเห็นแก่ตัว", "The cheapskate won't spend.", "C1", "—", "—", "—"],
  ["cheat", "v.", "โกง", "Don't cheat on tests.", "C1", "—", "—", "—"],
  ["cheater", "n.", "คนโกง", "The cheater was caught.", "C1", "—", "—", "—"],
  ["check", "v.", "ตรวจ", "Check your work.", "C1", "—", "—", "—"],
  ["checker", "n.", "สีหมากรุก", "Checkers is a game.", "C1", "—", "—", "—"],
  ["checkered", "adj.", "ลายหมากรุก", "A checkered history.", "C1", "—", "—", "—"],
  ["checkmate", "n.", "ชาติในหมากรุก", "Checkmate ended the game.", "C1", "—", "—", "—"],
  ["checkout", "n.", "ที่ชำระเงิน", "The checkout line is long.", "C1", "—", "—", "—"],
  ["cheddar", "n.", "ชีสเชดดาร์", "Cheddar is sharp cheese.", "C1", "—", "—", "—"],
  ["cheek", "n.", "แก้ม", "She has rosy cheeks.", "C1", "—", "—", "—"],
  ["cheeky", "adj.", "อ้อมน้อย", "A cheeky remark.", "C1", "—", "—", "—"],
  ["cheer", "v.", "ส่งเสียง", "Cheer for the team.", "C1", "—", "—", "—"],
  ["cheerful", "adj.", "สดใส", "A cheerful smile.", "C1", "—", "—", "—"],
  ["cheerfully", "adv.", "อย่างสดใส", "He spoke cheerfully.", "C1", "—", "—", "—"],
  ["cheerless", "adj.", "เศร้า", "A cheerless room.", "C1", "—", "—", "—"],
  ["cheers", "exclam.", "ขอบคุณ", "Cheers for the drink.", "C1", "—", "—", "—"],
  ["cheery", "adj.", "ร่าเริง", "A cheery personality.", "C1", "—", "—", "—"],
  ["cheese", "n.", "ชีส", "Cheese is delicious.", "C1", "—", "—", "—"],
  ["cheesy", "adj.", "เห็นชีส", "A cheesy joke.", "C1", "—", "—", "—"],
  ["cheetah", "n.", "เสือโคร่ง", "A cheetah runs fast.", "C1", "—", "—", "—"],
  ["chef", "n.", "เชฟ", "The chef prepared the meal.", "C1", "—", "—", "—"],
  ["chemical", "adj.", "เคมี", "Chemical reactions.", "C1", "—", "—", "—"],
  ["chemise", "n.", "เสื้อชั้นใน", "A chemise is underwear.", "C1", "—", "—", "—"],
  ["chemist", "n.", "นักเคมี", "The chemist mixed compounds.", "C1", "—", "—", "—"],
  ["chemistry", "n.", "เคมี", "Study chemistry.", "C1", "—", "—", "—"],
  ["chenille", "n.", "เส้นสักหลาด", "Chenille yarn is fuzzy.", "C1", "—", "—", "—"],
  ["cherish", "v.", "หวงแหน", "Cherish your memories.", "C1", "—", "—", "—"],
  ["cheroot", "n.", "บุหรี่แบบเรียว", "He smoked a cheroot.", "C1", "—", "—", "—"],
  ["cherry", "n.", "เชอร์รี่", "Cherry pie is delicious.", "C1", "—", "—", "—"],
  ["cherub", "n.", "เทพเด็ก", "A cherub appears in paintings.", "C1", "—", "—", "—"],
  ["cherubic", "adj.", "เป็นเทพเด็ก", "A cherubic face.", "C1", "—", "—", "—"],
  ["chervil", "n.", "ผักชี", "Chervil is a herb.", "C1", "—", "—", "—"],
  ["chess", "n.", "หมากรุก", "Chess is a strategic game.", "C1", "—", "—", "—"],
  ["chest", "n.", "อกกว้าง", "Measure chest size.", "C1", "—", "—", "—"],
  ["chesterfield", "n.", "เสื้อโค้ต", "A chesterfield is a coat.", "C1", "—", "—", "—"],
  ["chestnut", "n.", "เกาลัด", "Chestnuts roast on fire.", "C1", "—", "—", "—"],
  ["chesty", "adj.", "อกกว้าง", "A chesty laugh.", "C1", "—", "—", "—"],
  ["chevron", "n.", "รูปวี", "Chevrons mark rank.", "C1", "—", "—", "—"],
  ["chew", "v.", "เคี้ยว", "Chew your food.", "C1", "—", "—", "—"],
  ["chic", "adj.", "หรูโหร", "A chic dress.", "C1", "—", "—", "—"],
  ["chicanery", "n.", "การเล่นเกมหลอก", "Chicanery obscures the truth.", "C1", "—", "—", "—"],
  ["chick", "n.", "ลูกไก่", "A chick emerged from egg.", "C1", "—", "—", "—"],
  ["chickadee", "n.", "นกตระหนก", "Chickadees are small birds.", "C1", "—", "—", "—"],
  ["chicken", "n.", "ไก่", "Chicken is healthy meat.", "C1", "—", "—", "—"],
  ["chickenhearted", "adj.", "ขี้ขลาด", "A chickenhearted person.", "C1", "—", "—", "—"],
  ["chickpea", "n.", "ถั่วหัว", "Chickpeas are nutritious.", "C1", "—", "—", "—"],
  ["chickpox", "n.", "โรคไข้ส่วน", "Chickpox is contagious.", "C1", "—", "—", "—"],
  ["chicory", "n.", "ต้นชิคอรี่", "Chicory is a bitter vegetable.", "C1", "—", "—", "—"],
  ["chide", "v.", "ตำหนิ", "Chide the wrongdoer.", "C1", "—", "—", "—"],
  ["chief", "n.", "หัวหน้า", "The chief leads the tribe.", "C1", "—", "—", "—"],
  ["chiefly", "adv.", "ส่วนใหญ่", "The group is chiefly women.", "C1", "—", "—", "—"],
  ["chieftain", "n.", "เจ้าหน้าที่", "The chieftain ruled wisely.", "C1", "—", "—", "—"],
  ["chieftaincy", "n.", "ตำแหน่งหัวหน้า", "Chieftaincy is hereditary.", "C1", "—", "—", "—"],
  ["chiffon", "n.", "ผ้าชิฟฟอน", "Chiffon is a light fabric.", "C1", "—", "—", "—"],
  ["chiffer", "n.", "ผ้าซ้อนกัน", "Chiffier is layered fabric.", "C1", "—", "—", "—"],
  ["chigger", "n.", "ไรที่ระคัก", "Chiggers cause itching.", "C1", "—", "—", "—"],
  ["chignon", "n.", "ทรงผมตอน", "A chignon is an updo.", "C1", "—", "—", "—"],
  ["chilblain", "n.", "บวนหนาว", "Chilblains hurt in cold.", "C1", "—", "—", "—"],
  ["child", "n.", "เด็ก", "The child played happily.", "C1", "—", "—", "—"],
  ["childbirth", "n.", "การคลอด", "Childbirth is painful.", "C1", "—", "—", "—"],
  ["childbed", "n.", "ที่นอนหลังคลอด", "Childbed is recovery time.", "C1", "—", "—", "—"],
  ["childhood", "n.", "วัยเด็ก", "Childhood memories linger.", "C1", "—", "—", "—"],
  ["childish", "adj.", "เด็กโง่", "Childish behavior is immature.", "C1", "—", "—", "—"],
  ["childless", "adj.", "ไม่มีลูก", "A childless couple.", "C1", "—", "—", "—"],
  ["childlike", "adj.", "เหมือนเด็ก", "Childlike wonder.", "C1", "—", "—", "—"],
  ["chill", "v.", "ทำให้เย็น", "Chill the wine.", "C1", "—", "—", "—"],
  ["chilliness", "n.", "ความเย็น", "Chilliness pervaded.", "C1", "—", "—", "—"],
  ["chilly", "adj.", "เย็น", "A chilly evening.", "C1", "—", "—", "—"],
  ["chime", "n.", "เสียงระฆัง", "Church chimes rang.", "C1", "—", "—", "—"],
  ["chimera", "n.", "ความคิดหลวง", "A chimera is a fantasy.", "C1", "—", "—", "—"],
  ["chimeric", "adj.", "ไม่เป็นจริง", "Chimeric hopes.", "C1", "—", "—", "—"],
  ["chimney", "n.", "ปล่องไฟ", "Smoke rises from the chimney.", "C1", "—", "—", "—"],
  ["chimp", "n.", "ลิงแสนตะเพิด", "Chimps are primates.", "C1", "—", "—", "—"],
  ["chimpanzee", "n.", "ลิงแสนตะเพิด", "Chimpanzees are intelligent.", "C1", "—", "—", "—"],
  ["chin", "n.", "คาง", "He has a strong chin.", "C1", "—", "—", "—"],
  ["china", "n.", "จีน", "China is a large country.", "C1", "—", "—", "—"],
  ["china", "n.", "เครื่องสักปินต้อง", "Fine china for dinner.", "C1", "—", "—", "—"],
  ["chinaware", "n.", "เครื่องสักปินต้อง", "Chinaware is fragile.", "C1", "—", "—", "—"],
  ["chinchilla", "n.", "จิงจิลา", "Chinchillas are small rodents.", "C1", "—", "—", "—"],
  ["chinese", "adj.", "จีน", "Chinese food is delicious.", "C1", "—", "—", "—"],
  ["chink", "n.", "ช่องเปิด", "A chink in armor.", "C1", "—", "—", "—"],
  ["chino", "n.", "กางเกงสีครีม", "Chinos are casual pants.", "C1", "—", "—", "—"],
  ["chintz", "n.", "ผ้าพิมพ์ลาย", "Chintz has colorful patterns.", "C1", "—", "—", "—"],
  ["chintzy", "adj.", "ถูกและเลวร้าย", "A chintzy gift.", "C1", "—", "—", "—"],
  ["chip", "n.", "ชิป", "Eat potato chips.", "C1", "—", "—", "—"],
  ["chipmunk", "n.", "กระรอก", "Chipmunks store nuts.", "C1", "—", "—", "—"],
  ["chipped", "adj.", "แตกเหินหน่อย", "Chipped paint.", "C1", "—", "—", "—"],
  ["chipper", "adj.", "สนใจ", "A chipper mood.", "C1", "—", "—", "—"],
  ["chiropodist", "n.", "หมอเท้า", "The chiropodist trimmed toenails.", "C1", "—", "—", "—"],
  ["chiropody", "n.", "การรักษาเท้า", "Chiropody treats foot problems.", "C1", "—", "—", "—"],
  ["chiropractic", "n.", "การสมดุลกระดูกสันหลัง", "Chiropractic treats alignment.", "C1", "—", "—", "—"],
  ["chiropractor", "n.", "หมอกระดูกสันหลัง", "Visit a chiropractor.", "C1", "—", "—", "—"],
  ["chirp", "n.", "เสียงนก", "The bird's chirp.", "C1", "—", "—", "—"],
  ["chisel", "n.", "สิ่วแกะ", "Use a chisel carefully.", "C1", "—", "—", "—"],
  ["chiseler", "n.", "คนโกง", "The chiseler cheated.", "C1", "—", "—", "—"],
  ["chiseled", "adj.", "แกะสลัก", "Chiseled features.", "C1", "—", "—", "—"],
  ["chitchat", "n.", "คุยเล่น", "Engage in chitchat.", "C1", "—", "—", "—"],
  ["chivalrous", "adj.", "ประชิด", "Chivalrous behavior.", "C1", "—", "—", "—"],
  ["chivalry", "n.", "วีรชาติ", "Chivalry is noble.", "C1", "—", "—", "—"],
  ["chive", "n.", "หอมใหญ่", "Chives are a herb.", "C1", "—", "—", "—"],
  ["chloride", "n.", "คลอไรด์", "Chloride is a compound.", "C1", "—", "—", "—"],
  ["chlorinate", "v.", "กำจัดเชื้อโรค", "Chlorinate the pool.", "C1", "—", "—", "—"],
  ["chlorination", "n.", "การกำจัดเชื้อโรค", "Chlorination disinfects water.", "C1", "—", "—", "—"],
  ["chlorine", "n.", "คลอรีน", "Chlorine kills bacteria.", "C1", "—", "—", "—"],
  ["chlorophyll", "n.", "คลอโรฟิล", "Chlorophyll makes plants green.", "C1", "—", "—", "—"],
  ["chock", "n.", "ส่วนรองถมน้ำ", "Chock the wheels.", "C1", "—", "—", "—"],
  ["chock-full", "adj.", "เต็มไปหมด", "A chock-full basket.", "C1", "—", "—", "—"],
  ["chocolate", "n.", "ช็อกโกแลต", "I love chocolate.", "C1", "—", "—", "—"],
  ["choice", "n.", "ทางเลือก", "Make a good choice.", "C1", "—", "—", "—"],
  ["choice", "adj.", "เลือกสรร", "Choice quality.", "C1", "—", "—", "—"],
  ["choiceness", "n.", "คุณภาพที่เลือก", "Choiceness ensures quality.", "C1", "—", "—", "—"],
  ["choicy", "adj.", "ยาก", "A choicy person.", "C1", "—", "—", "—"],
  ["choir", "n.", "วงเพลงขับร้อง", "The choir sang beautifully.", "C1", "—", "—", "—"],
  ["choirboy", "n.", "เด็กขับร้อง", "Choirboys wore robes.", "C1", "—", "—", "—"],
  ["choirmaster", "n.", "ผู้นำวงร้อง", "The choirmaster conducted.", "C1", "—", "—", "—"],
  ["choke", "v.", "สำลัก", "Don't choke on food.", "C1", "—", "—", "—"],
  ["choker", "n.", "สร้อยคอแคบ", "A choker fits tightly.", "C1", "—", "—", "—"],
  ["choler", "n.", "ความโกรธ", "His choler rose.", "C1", "—", "—", "—"],
  ["cholera", "n.", "โรคอหิวาตกโรค", "Cholera spreads quickly.", "C1", "—", "—", "—"],
  ["choleric", "adj.", "โกรธง่าย", "A choleric temperament.", "C1", "—", "—", "—"],
  ["cholesterol", "n.", "คอเลสเตอรอล", "Reduce cholesterol.", "C1", "—", "—", "—"],
  ["chomp", "v.", "กัดแรง", "Chomp on candy.", "C1", "—", "—", "—"],
  ["choose", "v.", "เลือก", "Choose wisely.", "C1", "—", "—", "—"],
  ["choosy", "adj.", "ยาก", "A choosy eater.", "C1", "—", "—", "—"],
  ["chop", "v.", "สับ", "Chop the onions.", "C1", "—", "—", "—"],
  ["chophouse", "n.", "ร้านอาหาร", "Visit a chophouse.", "C1", "—", "—", "—"],
  ["chopped", "adj.", "สับ", "Chopped salad.", "C1", "—", "—", "—"],
  ["chopper", "n.", "ลิ่ม", "A chopper cuts wood.", "C1", "—", "—", "—"],
  ["chopping", "n.", "การสับ", "Chopping vegetables.", "C1", "—", "—", "—"],
  ["choppy", "adj.", "ขรุขระ", "Choppy water.", "C1", "—", "—", "—"],
  ["chops", "n.", "แก้มกว้าง", "He licked his chops.", "C1", "—", "—", "—"],
  ["chopstick", "n.", "ตะเกียบ", "Use chopsticks.", "C1", "—", "—", "—"],
  ["choral", "adj.", "เกี่ยวกับวงร้อง", "A choral piece.", "C1", "—", "—", "—"],
  ["chorale", "n.", "บทร้องคัว", "A chorale for choir.", "C1", "—", "—", "—"],
  ["chord", "n.", "คอร์ด", "Play a chord.", "C1", "—", "—", "—"],
  ["chordal", "adj.", "เกี่ยวกับคอร์ด", "Chordal harmony.", "C1", "—", "—", "—"],
  ["chordate", "n.", "สัตว์มีกระดูกสันหลัง", "Chordates have backbone.", "C1", "—", "—", "—"],
  ["chore", "n.", "งานบ้าน", "Do your chores.", "C1", "—", "—", "—"],
  ["choreograph", "v.", "ลงแนวต่ำ", "Choreograph the dance.", "C1", "—", "—", "—"],
  ["choreography", "n.", "การจัดการเต้นรำ", "Choreography shows movement.", "C1", "—", "—", "—"],
  ["chorister", "n.", "นักขับร้อง", "The chorister sang solo.", "C1", "—", "—", "—"],
  ["chortle", "v.", "หัวเราะเต่า", "Chortle with glee.", "C1", "—", "—", "—"],
  ["chorus", "n.", "บทร้องไห้", "Sing in the chorus.", "C1", "—", "—", "—"],
  ["chose", "v.", "เลือก", "She chose wisely.", "C1", "—", "—", "—"],
  ["chosen", "adj.", "ที่เลือก", "The chosen one.", "C1", "—", "—", "—"],
  ["chow", "n.", "อาหาร", "Eat chow.", "C1", "—", "—", "—"],
  ["chowder", "n.", "อาหารเข้มข้น", "Clam chowder.", "C1", "—", "—", "—"],
  ["chow mein", "n.", "หมี่ผัด", "Order chow mein.", "C1", "—", "—", "—"],
  ["christen", "v.", "ตั้งชื่อ", "Christen the baby.", "C1", "—", "—", "—"],
  ["Christendom", "n.", "โลกคริสต์", "Christendom is Christian world.", "C1", "—", "—", "—"],
  ["christening", "n.", "พิธีให้ชื่อ", "The christening ceremony.", "C1", "—", "—", "—"],
  ["Christian", "n.", "ชาวคริสต์", "A Christian believes.", "C1", "—", "—", "—"],
  ["Christianity", "n.", "ศาสนาคริสต์", "Christianity is a religion.", "C1", "—", "—", "—"],
  ["Christianize", "v.", "เปลี่ยนเป็นคริสต์", "Christianize the pagans.", "C1", "—", "—", "—"],
  ["Christmas", "n.", "คริสต์มาส", "Christmas is December 25.", "C1", "—", "—", "—"],
  ["Christmastide", "n.", "ช่วงเทศกาลคริสต์มาส", "Christmastide is festive.", "C1", "—", "—", "—"],
  ["chromatic", "adj.", "เกี่ยวกับสี", "Chromatic colors.", "C1", "—", "—", "—"],
  ["chrome", "n.", "โครเมียม", "Chrome plating.", "C1", "—", "—", "—"],
  ["chromic", "adj.", "เกี่ยวกับสี", "Chromic acid.", "C1", "—", "—", "—"],
  ["chromium", "n.", "โครเมียม", "Chromium is a metal.", "C1", "—", "—", "—"],
  ["chromosome", "n.", "โครโมโซม", "Chromosomes carry genes.", "C1", "—", "—", "—"],
  ["chronic", "adj.", "เรื้อรัง", "A chronic illness.", "C1", "—", "—", "—"],
  ["chronically", "adv.", "อย่างเรื้อรัง", "Chronically ill.", "C1", "—", "—", "—"],
  ["chronicle", "n.", "ประวัติศาสตร์", "A chronicle of events.", "C1", "—", "—", "—"],
  ["chronicler", "n.", "ผู้บันทึก", "The chronicler recorded.", "C1", "—", "—", "—"],
  ["chronograph", "n.", "นาฬิกาจับเวลา", "A chronograph measures time.", "C1", "—", "—", "—"],
  ["chronological", "adj.", "ตามลำดับเวลา", "Chronological order.", "C1", "—", "—", "—"],
  ["chronology", "n.", "ลำดับเวลา", "Chronology is time sequence.", "C1", "—", "—", "—"],
  ["chronometer", "n.", "นาฬิกาดูเวลา", "A chronometer is accurate.", "C1", "—", "—", "—"],
  ["chrysalis", "n.", "ลูกหลอด", "A chrysalis transforms.", "C1", "—", "—", "—"],
  ["chrysanthemum", "n.", "ดอกเบญจมาศ", "Chrysanthemums are flowers.", "C1", "—", "—", "—"],
  ["chub", "n.", "ปลาไล่ลม", "A chub is a fish.", "C1", "—", "—", "—"],
  ["chubby", "adj.", "อ้วนน้อย", "A chubby child.", "C1", "—", "—", "—"],
  ["chuck", "v.", "ขว้าง", "Chuck the ball.", "C1", "—", "—", "—"],
  ["chuckle", "v.", "หัวเราะเสียงเล็ก", "Chuckle at the joke.", "C1", "—", "—", "—"],
  ["chuckhole", "n.", "หลุมถนน", "A chuckhole damaged tires.", "C1", "—", "—", "—"],
  ["chuddar", "n.", "ผ้าคลุม", "A chuddar covers the body.", "C1", "—", "—", "—"],
  ["chuffy", "adj.", "พึงพอใจ", "A chuffy expression.", "C1", "—", "—", "—"],
  ["chug", "v.", "เดินหนา", "Chug along.", "C1", "—", "—", "—"],
  ["chukka", "n.", "รองเท้าบูต", "Chukka boots are casual.", "C1", "—", "—", "—"],
  ["chum", "n.", "เพื่อน", "He's my best chum.", "C1", "—", "—", "—"],
  ["chummy", "adj.", "เป็นเพื่อน", "They're chummy.", "C1", "—", "—", "—"],
  ["chump", "n.", "คนโง่", "The chump believed the lie.", "C1", "—", "—", "—"],
  ["chunk", "n.", "ชิ้น", "A chunk of bread.", "C1", "—", "—", "—"],
  ["chunky", "adj.", "มีสัน", "Chunky peanut butter.", "C1", "—", "—", "—"],
  ["chunter", "v.", "บ่นบ้วน", "Chunter about problems.", "C1", "—", "—", "—"],
  ["church", "n.", "โบสถ์", "Attend church.", "C1", "—", "—", "—"],
  ["churchgoer", "n.", "ผู้นมัสการ", "A churchgoer attends.", "C1", "—", "—", "—"],
  ["churchman", "n.", "นักบวช", "The churchman preached.", "C1", "—", "—", "—"],
  ["churchyard", "n.", "บริเวณโบสถ์", "The churchyard cemetery.", "C1", "—", "—", "—"],
  ["churl", "n.", "คนหยาบ", "The churl behaved rudely.", "C1", "—", "—", "—"],
  ["churlish", "adj.", "หยาบคาย", "A churlish reply.", "C1", "—", "—", "—"],
  ["churn", "v.", "ผัด", "Churn the butter.", "C1", "—", "—", "—"],
  ["churning", "n.", "การผัด", "Churning makes butter.", "C1", "—", "—", "—"],
  ["chute", "n.", "ท่อลาด", "A chute slides down.", "C1", "—", "—", "—"],
  ["chutney", "n.", "พริกแกง", "Mango chutney.", "C1", "—", "—", "—"],
  ["chutzpah", "n.", "ความกล้า", "Chutzpah is audacity.", "C1", "—", "—", "—"],
  ["cicada", "n.", "แมลงจักจั่น", "Cicadas sing loudly.", "C1", "—", "—", "—"],
  ["cicatrice", "n.", "แผลเป็น", "A cicatrice is a scar.", "C1", "—", "—", "—"],
  ["cicatrix", "n.", "แผลเป็น", "Cicatrix marks healing.", "C1", "—", "—", "—"],
  ["ciceroni", "n.", "ไกด์ทัวร์", "The ciceroni guided tours.", "C1", "—", "—", "—"],
  ["cicisbeo", "n.", "รักษมาน", "A cicisbeo was devoted.", "C1", "—", "—", "—"],
  ["cicuta", "n.", "พืชพิษ", "Cicuta is poisonous.", "C1", "—", "—", "—"],
  ["cider", "n.", "น้ำแอปเปิ้ล", "Apple cider is refreshing.", "C1", "—", "—", "—"],
  ["cigar", "n.", "บุหรี่ดวง", "Smoke a cigar.", "C1", "—", "—", "—"],
  ["cigarette", "n.", "บุหรี่มวน", "Smoking cigarettes.", "C1", "—", "—", "—"],
  ["cilia", "n.", "ขนหลาย", "Cilia are tiny hairs.", "C1", "—", "—", "—"],
  ["cinch", "n.", "เข็มขัด", "A cinch is easy.", "C1", "—", "—", "—"],
  ["cincture", "n.", "เข็มขัด", "A cincture ties robes.", "C1", "—", "—", "—"],
  ["cinder", "n.", "ถ่านไฟ", "Cinders from fire.", "C1", "—", "—", "—"],
  ["cineaste", "n.", "แฟนภาพยนตร์", "A cineaste loves films.", "C1", "—", "—", "—"],
  ["cinema", "n.", "โรงภาพยนตร์", "See a film at cinema.", "C1", "—", "—", "—"],
  ["cinematic", "adj.", "เกี่ยวกับหนัง", "Cinematic techniques.", "C1", "—", "—", "—"],
  ["cinematograph", "n.", "เครื่องถ่ายทำ", "Early cinematograph.", "C1", "—", "—", "—"],
  ["cinematography", "n.", "การกำกับเพื่อการเคลื่อนไหว", "Cinematography is filming.", "C1", "—", "—", "—"],
  ["cinerama", "n.", "ระบบหนังเป็นรูปกว้าง", "Cinerama is wide screen.", "C1", "—", "—", "—"],
  ["cinnabar", "n.", "ปรอทสีแดง", "Cinnabar is mercuric sulfide.", "C1", "—", "—", "—"],
  ["cinnamon", "n.", "อบเชย", "Cinnamon spice.", "C1", "—", "—", "—"],
  ["cinquefoil", "n.", "พืชห้าใบ", "Cinquefoil has five leaves.", "C1", "—", "—", "—"],
  ["cipher", "n.", "รหัส", "A cipher is a code.", "C1", "—", "—", "—"],
  ["circa", "prep.", "ประมาณ", "Circa 1900.", "C1", "—", "—", "—"],
  ["circadian", "adj.", "ประจำวัน", "Circadian rhythm.", "C1", "—", "—", "—"],
  ["circe", "n.", "สตรีล่อแหลม", "A Circe enchantress.", "C1", "—", "—", "—"],
  ["circle", "n.", "วงกลม", "Draw a circle.", "C1", "—", "—", "—"],
  ["circlet", "n.", "วงสร้อย", "A circlet is a small crown.", "C1", "—", "—", "—"],
  ["circuit", "n.", "วงจร", "An electrical circuit.", "C1", "—", "—", "—"],
  ["circuitous", "adj.", "บ้อน", "A circuitous route.", "C1", "—", "—", "—"],
  ["circuitry", "n.", "ระบบวงจร", "Complex circuitry.", "C1", "—", "—", "—"],
  ["circular", "adj.", "เป็นวงกลม", "A circular motion.", "C1", "—", "—", "—"],
  ["circularity", "n.", "ลักษณะวงกลม", "Circularity of shape.", "C1", "—", "—", "—"],
  ["circularize", "v.", "แจกประกาศ", "Circularize the notice.", "C1", "—", "—", "—"],
  ["circulate", "v.", "ไหล", "Blood circulates.", "C1", "—", "—", "—"],
  ["circulating", "adj.", "ไหลเวียน", "Circulating fluid.", "C1", "—", "—", "—"],
  ["circulation", "n.", "การไหลเวียน", "Good circulation.", "C1", "—", "—", "—"],
  ["circulatory", "adj.", "เกี่ยวกับการไหลเวียน", "Circulatory system.", "C1", "—", "—", "—"],
  ["circumcise", "v.", "ตัดล้ำ", "Circumcise according to custom.", "C1", "—", "—", "—"],
  ["circumcision", "n.", "การตัดล้ำ", "Circumcision is a ritual.", "C1", "—", "—", "—"],
  ["circumference", "n.", "รอบวง", "The circumference is the perimeter.", "C1", "—", "—", "—"],
  ["circumferential", "adj.", "รอบขอบ", "Circumferential motion.", "C1", "—", "—", "—"],
  ["circumflex", "n.", "เครื่องหมายย้ำเสียง", "A circumflex marks tone.", "C1", "—", "—", "—"],
  ["circumfluent", "adj.", "ไหลรอบ", "Circumfluent waters.", "C1", "—", "—", "—"],
  ["circumlocution", "n.", "การพูดเอ้อเวอร์", "Avoid circumlocution.", "C1", "—", "—", "—"],
  ["circumlocutory", "adj.", "พูดเบียด", "Circumlocutory language.", "C1", "—", "—", "—"],
  ["circumlunar", "adj.", "รอบดวงจันทร์", "Circumlunar orbit.", "C1", "—", "—", "—"],
  ["circumnavigate", "v.", "ล่องเรือรอบโลก", "Circumnavigate the globe.", "C1", "—", "—", "—"],
  ["circumnavigation", "n.", "การล่องเรือรอบโลก", "Circumnavigation takes time.", "C1", "—", "—", "—"],
  ["circumpolar", "adj.", "รอบขั้ว", "Circumpolar stars.", "C1", "—", "—", "—"],
  ["circumscribe", "v.", "จำกัด", "Circumscribe the area.", "C1", "—", "—", "—"],
  ["circumscription", "n.", "การจำกัด", "Circumscription of power.", "C1", "—", "—", "—"],
  ["circumscriptive", "adj.", "จำกัด", "Circumscriptive rules.", "C1", "—", "—", "—"],
  ["circumsolar", "adj.", "รอบดวงอาทิตย์", "Circumsolar orbit.", "C1", "—", "—", "—"],
  ["circumspect", "adj.", "ระมัดระวัง", "Be circumspect.", "C1", "—", "—", "—"],
  ["circumspection", "n.", "การระมัดระวัง", "Circumspection is wisdom.", "C1", "—", "—", "—"],
  ["circumspectly", "adv.", "อย่างระมัดระวัง", "Act circumspectly.", "C1", "—", "—", "—"],
  ["circumstance", "n.", "สถานการณ์", "Under the circumstances.", "C1", "—", "—", "—"],
  ["circumstances", "n.", "สถานการณ์", "Difficult circumstances.", "C1", "—", "—", "—"],
  ["circumstanced", "adj.", "อยู่ในสถานการณ์", "Well-circumstanced person.", "C1", "—", "—", "—"],
  ["circumstantial", "adj.", "เกี่ยวกับเหตุการณ์", "Circumstantial evidence.", "C1", "—", "—", "—"],
  ["circumstantiality", "n.", "รายละเอียด", "Circumstantiality of detail.", "C1", "—", "—", "—"],
  ["circumstantially", "adv.", "อย่างละเอียด", "Describe circumstantially.", "C1", "—", "—", "—"],
  ["circumstantiate", "v.", "บรรยายละเอียด", "Circumstantiate the claim.", "C1", "—", "—", "—"],
  ["circumvallation", "n.", "เขตป้องกัน", "Circumvallation fortified.", "C1", "—", "—", "—"],
  ["circumvent", "v.", "เอาชนะจากการเล่นกลเกมเห่ตั้งใจ", "Circumvent the rules.", "C1", "—", "—", "—"],
  ["circumvention", "n.", "การหลีกเลี่ยง", "Circumvention of justice.", "C1", "—", "—", "—"],
  ["circumventive", "adj.", "ทำให้หลีกเลี่ยง", "Circumventive tactics.", "C1", "—", "—", "—"],
  ["circus", "n.", "สิ่งมหัศจรรย์", "The circus has acrobats.", "C1", "—", "—", "—"],
  ["circuses", "n.", "หลายสิ่งมหัศจรรย์", "Multiple circuses.", "C1", "—", "—", "—"],
  ["cirque", "n.", "วงกลมภูเขา", "A cirque is a valley.", "C1", "—", "—", "—"],
  ["cirrhosis", "n.", "โรคตับแข็ง", "Cirrhosis is liver disease.", "C1", "—", "—", "—"],
  ["cirrocumulus", "n.", "เมฆขาว", "Cirrocumulus clouds.", "C1", "—", "—", "—"],
  ["cirrostratus", "n.", "เมฆบาง", "Cirrostratus is thin cloud.", "C1", "—", "—", "—"],
  ["cirrus", "n.", "เมฆสูง", "Cirrus clouds are high.", "C1", "—", "—", "—"],
  ["cisalpine", "adj.", "อยู่ทางตะวันตกของ", "Cisalpine Gaul.", "C1", "—", "—", "—"],
  ["cisatlantic", "adj.", "อยู่ทางตะวันตกของมหาสมุทร", "Cisatlantic trade.", "C1", "—", "—", "—"],
  ["cistern", "n.", "ถังเก็บน้ำ", "A cistern stores water.", "C1", "—", "—", "—"],
  ["citadel", "n.", "ป้อมปราการ", "The citadel is fortified.", "C1", "—", "—", "—"],
  ["citation", "n.", "การอ้างอิง", "A citation of sources.", "C1", "—", "—", "—"],
  ["cite", "v.", "อ้างอิง", "Cite your sources.", "C1", "—", "—", "—"],
  ["cither", "n.", "เครื่องดนตรี", "Play the cither.", "C1", "—", "—", "—"],
  ["citified", "adj.", "ชนบทกลายเป็นเมือง", "Citified manners.", "C1", "—", "—", "—"],
  ["citizen", "n.", "พลเมือง", "A citizen has rights.", "C1", "—", "—", "—"],
  ["citizenly", "adj.", "มีคุณธรรม", "Citizenly conduct.", "C1", "—", "—", "—"],
  ["citizenry", "n.", "ประชาชน", "The citizenry votes.", "C1", "—", "—", "—"],
  ["citizenship", "n.", "สัญชาติ", "Citizenship is a right.", "C1", "—", "—", "—"],
  ["citole", "n.", "เครื่องดนตรี", "A citole is ancient.", "C1", "—", "—", "—"],
  ["citral", "n.", "สารเคมีน้ำมัน", "Citral is in lemongrass.", "C1", "—", "—", "—"],
  ["citrate", "n.", "ธาตุที่มีซิตริก", "Citrate is a salt.", "C1", "—", "—", "—"],
  ["citric", "adj.", "เกี่ยวกับส้ม", "Citric acid.", "C1", "—", "—", "—"],
  ["citrine", "adj.", "สีเหลืองอมเขียว", "Citrine color.", "C1", "—", "—", "—"],
  ["citron", "n.", "ส้มโชกุน", "A citron is a fruit.", "C1", "—", "—", "—"],
  ["citronella", "n.", "หญ้าไล่ยุง", "Citronella repels insects.", "C1", "—", "—", "—"],
  ["citrus", "n.", "ส้มตระกูล", "Citrus fruits are sour.", "C1", "—", "—", "—"],
  ["cittern", "n.", "เครื่องดนตรี", "A cittern is medieval.", "C1", "—", "—", "—"],
  ["city", "n.", "เมือง", "Live in the city.", "C1", "—", "—", "—"],
  ["city-state", "n.", "นครรัฐ", "Ancient city-states.", "C1", "—", "—", "—"],
  ["civet", "n.", "ชะมด", "A civet cat.", "C1", "—", "—", "—"],
  ["civic", "adj.", "เกี่ยวกับตัวเมือง", "Civic duty.", "C1", "—", "—", "—"],
  ["civicism", "n.", "ความเป็นพลเมือง", "Civicism promotes participation.", "C1", "—", "—", "—"],
  ["civics", "n.", "การศึกษาพลเมือง", "Study civics in school.", "C1", "—", "—", "—"],
  ["civil", "adj.", "มีน้ำใจ", "Civil behavior.", "C1", "—", "—", "—"],
  ["civilian", "n.", "ประชาชนธรรมชาติ", "Civilians in war.", "C1", "—", "—", "—"],
  ["civility", "n.", "ความสุภาพ", "Show civility.", "C1", "—", "—", "—"],
  ["civilization", "n.", "อารยธรรม", "Human civilization.", "C1", "—", "—", "—"],
  ["civilize", "v.", "สอนให้มีวัฒนธรรม", "Civilize the people.", "C1", "—", "—", "—"],
  ["civilized", "adj.", "มีวัฒนธรรม", "A civilized society.", "C1", "—", "—", "—"],
  ["civilizer", "n.", "ผู้สอนวัฒนธรรม", "The civilizer taught.", "C1", "—", "—", "—"],
  ["civilly", "adv.", "อย่างสุภาพ", "Speak civilly.", "C1", "—", "—", "—"],
  ["civvies", "n.", "เสื้อผ้าธรรมชาติ", "Soldiers in civvies.", "C1", "—", "—", "—"],
  ["clack", "v.", "ตัดเสียง", "Clack the tongue.", "C1", "—", "—", "—"],
  ["clad", "v.", "ห่มทับ", "Clad in armor.", "C1", "—", "—", "—"],
  ["claim", "v.", "อ้าง", "Claim the prize.", "C1", "—", "—", "—"],
  ["claimant", "n.", "ผู้เรียกร้อง", "A claimant to title.", "C1", "—", "—", "—"],
  ["clairvoyance", "n.", "ความเป็นจิตใจ", "Clairvoyance is claimed.", "C1", "—", "—", "—"],
  ["clairvoyant", "n.", "คนที่เห็นผ่า", "A clairvoyant reads minds.", "C1", "—", "—", "—"],
  ["clam", "n.", "หอย", "Eat clams.", "C1", "—", "—", "—"],
  ["clamant", "adj.", "เรียกร้องอย่างดัง", "A clamant need.", "C1", "—", "—", "—"],
  ["clamber", "v.", "ปีนขึ้น", "Clamber up rocks.", "C1", "—", "—", "—"],
  ["clammy", "adj.", "ชื้นเยื้อย", "Clammy hands.", "C1", "—", "—", "—"],
  ["clamor", "n.", "เสียงดัง", "A loud clamor.", "C1", "—", "—", "—"],
  ["clamorous", "adj.", "ดัง", "A clamorous crowd.", "C1", "—", "—", "—"],
  ["clamorous", "adj.", "เรียกร้อง", "Clamorous demands.", "C1", "—", "—", "—"],
  ["clamorously", "adv.", "อย่างดัง", "Speak clamorously.", "C1", "—", "—", "—"],
  ["clamorousness", "n.", "ความดัง", "Clamorousness increases.", "C1", "—", "—", "—"],
  ["clamp", "n.", "ที่บีบ", "A clamp holds tight.", "C1", "—", "—", "—"],
  ["clampdown", "n.", "การปราบปราม", "A clampdown on crime.", "C1", "—", "—", "—"],
  ["clan", "n.", "วงศ์", "The clan gathers.", "C1", "—", "—", "—"],
  ["clangor", "n.", "เสียงโลหะ", "A clangor of bells.", "C1", "—", "—", "—"],
  ["clangorous", "adj.", "ส่งเสียงดัง", "A clangorous sound.", "C1", "—", "—", "—"],
  ["clank", "n.", "เสียงลัก", "A metal clank.", "C1", "—", "—", "—"],
  ["clanking", "adj.", "ส่งเสียง", "Clanking chain.", "C1", "—", "—", "—"],
  ["clannish", "adj.", "ชอบอยู่รวมกลุ่มเพื่อ", "A clannish group.", "C1", "—", "—", "—"],
  ["clannishness", "n.", "ความชอบอยู่รวมกลุ่ม", "Clannishness divides.", "C1", "—", "—", "—"],
  ["clanship", "n.", "ความเป็นวงศ์", "Clanship bonds.", "C1", "—", "—", "—"],
  ["clansman", "n.", "สมาชิกวงศ์", "The clansman helps.", "C1", "—", "—", "—"],
  ["clanswoman", "n.", "หญิงสมาชิกวงศ์", "The clanswoman agrees.", "C1", "—", "—", "—"],
  ["clap", "v.", "ปัดมือให้เสียง", "Clap at the end.", "C1", "—", "—", "—"],
  ["claptrap", "n.", "คำพูดสวยงาม", "Claptrap convinces.", "C1", "—", "—", "—"],
  ["claque", "n.", "แฟนตัวจริง", "A claque applauds.", "C1", "—", "—", "—"],
  ["clarification", "n.", "การชี้แจง", "Clarification helps.", "C1", "—", "—", "—"],
  ["clarified", "adj.", "ชัดเจน", "Clarified butter.", "C1", "—", "—", "—"],
  ["clarifier", "n.", "สิ่งที่ชี้แจง", "A clarifier explains.", "C1", "—", "—", "—"],
  ["clarify", "v.", "ทำให้ชัดเจน", "Clarify the rules.", "C1", "—", "—", "—"],
  ["clarionet", "n.", "แครเรียต", "Play clarionet.", "C1", "—", "—", "—"],
  ["clarion", "n.", "หลวงจานตะหลิ่ง", "A clarion call.", "C1", "—", "—", "—"],
  ["clarity", "n.", "ความชัดเจน", "Clarity is important.", "C1", "—", "—", "—"],
  ["clash", "v.", "ชน", "Clash of swords.", "C1", "—", "—", "—"],
  ["clasp", "v.", "กอด", "Clasp hands.", "C1", "—", "—", "—"],
  ["clasper", "n.", "อวัยวะที่ใช้กอด", "Claspers hold tight.", "C1", "—", "—", "—"],
  ["class", "n.", "ชั้น", "Top class student.", "C1", "—", "—", "—"],
  ["classic", "adj.", "คลาสสิก", "A classic book.", "C1", "—", "—", "—"],
  ["classical", "adj.", "คลาสสิก", "Classical music.", "C1", "—", "—", "—"],
  ["classicism", "n.", "คลาสสิสิซึม", "Classicism values tradition.", "C1", "—", "—", "—"],
  ["classicist", "n.", "ผู้นักคลาสสิก", "A classicist scholar.", "C1", "—", "—", "—"],
  ["classicize", "v.", "ทำให้คลาสสิก", "Classicize the design.", "C1", "—", "—", "—"],
  ["classific", "adj.", "เกี่ยวกับการจำแนก", "Classific system.", "C1", "—", "—", "—"],
  ["classification", "n.", "การจำแนก", "Scientific classification.", "C1", "—", "—", "—"],
  ["classified", "adj.", "เป็นความลับ", "Classified information.", "C1", "—", "—", "—"],
  ["classifier", "n.", "สิ่งจำแนก", "A classifier organizes.", "C1", "—", "—", "—"],
  ["classify", "v.", "จำแนก", "Classify the items.", "C1", "—", "—", "—"],
  ["classiness", "n.", "ความมีระดับ", "Classiness in dress.", "C1", "—", "—", "—"],
  ["classless", "adj.", "ไม่มีชั้น", "A classless society.", "C1", "—", "—", "—"],
  ["classmate", "n.", "เพื่อนร่วมชั้น", "My classmate.", "C1", "—", "—", "—"],
  ["classroom", "n.", "ห้องเรียน", "Meet in classroom.", "C1", "—", "—", "—"],
  ["classy", "adj.", "มีระดับ", "A classy woman.", "C1", "—", "—", "—"],
  ["clast", "n.", "ชิ้นส่วน", "Rock clasts.", "C1", "—", "—", "—"],
  ["clastic", "adj.", "เป็นเศษ", "Clastic rocks.", "C1", "—", "—", "—"],
  ["clatter", "n.", "เสียงหลายๆ", "A clatter of hooves.", "C1", "—", "—", "—"],
  ["clattery", "adj.", "ส่งเสียงลัก", "A clattery machine.", "C1", "—", "—", "—"],
  ["Claude", "n.", "ชื่อบุคคล", "Claude is a name.", "C1", "—", "—", "—"],
  ["claughteous", "adj.", "เป็นธรรมชาติ", "Claughteous behavior.", "C1", "—", "—", "—"],
  ["clause", "n.", "วรรค", "A clause in contract.", "C1", "—", "—", "—"],
  ["clausular", "adj.", "เกี่ยวกับวรรค", "Clausular structure.", "C1", "—", "—", "—"],
  ["claustrophobia", "n.", "ความหวาดกลัวพื้นที่แคบ", "Claustrophobia is fear.", "C1", "—", "—", "—"],
  ["claustrophobic", "adj.", "แคบเหมือนอึง", "Claustrophobic feelings.", "C1", "—", "—", "—"],
  ["clave", "n.", "กุญแจ", "A clave is a club.", "C1", "—", "—", "—"],
  ["clavichord", "n.", "เครื่องดนตรี", "A clavichord is ancient.", "C1", "—", "—", "—"],
  ["clavicle", "n.", "กระดูกไห肩", "The clavicle is collarbone.", "C1", "—", "—", "—"],
  ["clavier", "n.", "แป้นพิมพ์", "Play the clavier.", "C1", "—", "—", "—"],
  ["claviger", "n.", "ผู้ถือกุญแจ", "A claviger guards.", "C1", "—", "—", "—"],
  ["clavier", "n.", "แป้นพิมพ์", "A clavier has keys.", "C1", "—", "—", "—"],
  ["claw", "n.", "กรงเล็บ", "A cat's claw.", "C1", "—", "—", "—"],
  ["claw-hammer", "n.", "ไม้ชะหลังดึง", "A claw-hammer pulls.", "C1", "—", "—", "—"],
  ["clawed", "adj.", "มีกรงเล็บ", "A clawed creature.", "C1", "—", "—", "—"],
  ["clawfoot", "n.", "เท้ากรงเล็บ", "A clawfoot bathtub.", "C1", "—", "—", "—"],
  ["clawless", "adj.", "ไม่มีกรงเล็บ", "A clawless animal.", "C1", "—", "—", "—"],
  ["clews", "n.", "ลูกหนองด้าย", "Clews of rope.", "C1", "—", "—", "—"],
  ["clay", "n.", "ดินเหนียว", "Mold with clay.", "C1", "—", "—", "—"],
  ["clayish", "adj.", "เหมือนดินเหนียว", "A clayish soil.", "C1", "—", "—", "—"],
  ["claylike", "adj.", "เหมือนดิน", "A claylike mixture.", "C1", "—", "—", "—"],
  ["claypal", "n.", "เพื่อน", "My claypal.", "C1", "—", "—", "—"],
  ["claypan", "n.", "ชั้นดินเหนียว", "A claypan forms.", "C1", "—", "—", "—"],
  ["claystone", "n.", "หินดิน", "Claystone is rock.", "C1", "—", "—", "—"],
  ["claytonia", "n.", "พืชชนิดหนึ่ง", "Claytonia grows wild.", "C1", "—", "—", "—"],
  ["clayware", "n.", "เครื่องสักปินต้อง", "Clayware pottery.", "C1", "—", "—", "—"],
  ["claymore", "n.", "ดาบสก็อต", "A claymore blade.", "C1", "—", "—", "—"],
  ["clayweed", "n.", "พืชชนิดหนึ่ง", "Clayweed in field.", "C1", "—", "—", "—"],
  ["clazzy", "adj.", "มีระดับ", "A clazzy look.", "C1", "—", "—", "—"]
];

const VOCAB_ALEVEL_TGAT_BASE = VOCAB_ALEVEL_TGAT.map((word, idx) => ({
  id: idx + 1,
  day: Math.ceil((idx + 1) / 30),
  ...word
}));

// Export for use in VocabUp
if (typeof window !== 'undefined') {
  window.VOCAB_ALEVEL_TGAT = VOCAB_ALEVEL_TGAT;
}
